### ISSUE TITLE
Wedgit

### ISSUE THREAD

**Issue by ManitDave** [microsoft/devhome#1360] opened 2023-08-03 17:22 UTC
### Dev Home version

0.301.198.0

### Windows build number

10.0.22621.2070

### Other software

OS Build Version: 10.0.22621.2070.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

When the application restarts the all widget got cleared. I have to add every time. 

### Expected result

They should stay all widget as I add them

### Actual result

New screen like application just got installed wverytime

### Included System Information

Physical Memory: 15.75GB (7.83GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-08-09 19:31
Hi @ManitDave . Can you check if you have any updates available for the Windows Web Experience Host in the store and update if so? If you're on an Insider build of Windows, I believe you should have an update available (you'll be on version 523.x). If you're not on an Insider build (you'll have version 423.x), you may have to wait a little longer for an update with the fix. You can also check what version you have by running get-appxpackage *webexp* in a powershell prompt.

**Comment by krschau** [comment] 2023-08-09 19:31
Duplicate of #742

**Closed by krschau** 2023-08-09 19:31 UTC
Labels: Issue-Bug, Needs-Triage
