### ISSUE TITLE
Clicking "add new widget" doesn't do anything

### ISSUE THREAD

**Issue by fleetyeets** [microsoft/devhome#1126] opened 2023-06-12 01:03 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.1000

### Other software

OS Build Version: 10.0.23475.1000.amd64fre.ni_prerelease.230602-1331
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Click Add New Widget

### Expected result

Add a new widget

### Actual result

Not add a new widget. 

### Included System Information

CPU: AMD Ryzen 5 1600 Six-Core Processor            
Physical Memory: 31.95GB (23.64GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-12 14:53
Duplicate of #866

**Comment by fleetyeets** [comment] 2023-06-12 22:21
Hello - Windows Web Experience purports to be on the most recent version and will not let me update.  For reference I have version 523.11500.0.0, which seems different from the other ticket's major version of 511, but - understand it may still be related.
![image](https://github.com/microsoft/devhome/assets/85968762/791a4b98-d2ea-4c72-a7a2-b567d11f799b)

**Comment by fleetyeets** [comment] 2023-06-13 22:21
[Dashboard_20230611-210146.log](https://github.com/microsoft/devhome/files/11739928/Dashboard_20230611-210146.log)

**Comment by fleetyeets** [comment] 2023-06-13 22:22
[Dashboard_20230613-182005.log](https://github.com/microsoft/devhome/files/11739929/Dashboard_20230613-182005.log)

**Comment by fleetyeets** [comment] 2023-06-13 22:23
In true CS fashion, it worked today.  I haven't changed the major/sub etc version between those two logs, all I did was close it again and open it again.  Hoping these logs help track down / squash the bug, anyways. :)

**Comment by fleetyeets** [comment] 2023-06-13 22:25
I also have the Dev Home GitHub Extension installed - given that this extension provides widgets, possible it is contributing here.

**Closed** 2023-10-18 17:50 UTC
Labels: Issue-Bug, Area-Dashboard, Issue-External
