### ISSUE TITLE
Can't pin GitHub widgets

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#1147] opened 2023-06-14 18:10 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.1000

### Other software

OS Build Version: 10.0.23475.1000.amd64fre.ni_prerelease.230602-1331
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Go to Dev Home Dashboard
2. Add PR widget
3. Enter a valid github URL
4. URL is found, but the pinning button is not available.

### Expected result

I should be able to pin widgets when trying to add them

### Actual result

I am unable to see the pinning action

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 47.71GB (26.1GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by joadoumie** [comment] 2023-06-14 18:17
I had Dev Home (Dev) on my machine. By deleting Dev Home (Dev) the issue resolved. I didn't have two instances of the GitHub extension on my machine though. 

Not sure if deleting Dev Home (Dev) actually solved the problem.

I am also noticing that if I have side by side installs Dev + Preview, I see multiple core widgets showing up. I am assuming that Dev Home sees Dev Home Dev as an extension and then pulls in the core extensions. It'd be great if we could have the extensibility model completely separate for building and testing vs. daily use.

**Comment by joadoumie** [comment] 2023-06-14 19:25
I couldn't see the pin button at all. It was just missing. I probably still have logs. Let me try to find them.

**Comment by joadoumie** [comment] 2023-06-14 19:28
[Dashboard_20230614-140645.log](https://github.com/microsoft/devhome/files/11749856/Dashboard_20230614-140645.log)

**Comment by krschau** [comment] 2023-06-14 20:37
Oh! Then you're seeing #574. I checked a fix in a bit ago, so you should be able to see it in dev/canary. I'm going to dupe this to that. For turning widgets on/off, I feel like there's already an issue I just wasn't finding, so let me look for that again and I'll open a new one if I can't find one.

**Comment by krschau** [comment] 2023-06-14 20:37
Duplicate of #574

**Closed by krschau** 2023-06-14 20:37 UTC
Labels: Issue-Bug, Needs-Triage, Needs-Team-Response
