### ISSUE TITLE
Unable to close add widget window

### ISSUE THREAD

**Issue by haki-user** [microsoft/devhome#915] opened 2023-05-28 09:15 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22000.1936

### Other software

OS Build Version: 10.0.22000.1936.amd64fre.co_release.210604-1628
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Goto dashboard
2. goto add widget
3. click on close(cross).
4. double click on close.

### Expected result

Window should get closed.

### Actual result

Nothing happens when clicking one time on close.
If double click then, entire app zoom out but not add widget window, like the restore button action.

![Screenshot 2023-05-28 144954](https://github.com/microsoft/devhome/assets/104914040/5ef3768b-701e-469e-80d0-c3faddfd8e4e)

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
Physical Memory: 7.7GB (1.28GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-30 18:27
Duplicate of #537

**Closed by krschau** 2023-05-30 18:27 UTC
Labels: Issue-Bug, Needs-Triage
