### ISSUE TITLE
Simplify the Finder tool

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/devhome#3470] opened 2024-07-19 20:01 UTC
### Suggested new feature or improvement

The button for the Finder tool right now does 2 things:

1. Finder tool, to target an app.
2. Go to expanded mode and go to the Process list page.

The “finder” aspect is a well-known pattern used in other apps such as ProcExp, ProcMon, WinSpy. Having it also go to expanded mode and navigate to the process list page is confusing. It’s also redundant, because if the user is not already targeting an app, then they can use the Expand custom chrome button to go to expanded mode, and this will by default open the process list page.

Remove the “expand the ProcessList” feature from the Finder tool. Instead, leave it to the user to use the Expand custom chrome item to expand the window. If there is no target app, the default page will be the ProcessList anyway.

See related issues
#3066 
#3431 
#3060

**Comment by timkur** [comment] 2024-08-29 21:14
Dupe of #3431

**Closed by timkur** 2024-08-29 21:14 UTC
Labels: Issue-Feature, Priority-2, Area-DI
