### ISSUE TITLE
All page title are using the wrong text style 

### ISSUE THREAD

**Issue by ianyyu** [microsoft/devhome#1141] opened 2023-06-13 18:25 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

All page title are using title
 <TextBlock Text="Title" Style="{StaticResource TitleTextBlockStyle}"/>

which is wrong 

### Expected result

All page title should be using the subtitle style 
" Text="Subtitle" Style="{StaticResource SubtitleTextBlockStyle}"/> "

Please also refer to figma files 

### Actual result

Wrong page title style 

### Included System Information

CPU: AMD EPYC 7763 64-Core Processor                
Physical Memory: 15.95GB (8.84GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-13 18:34
Duplicate of #567

**Closed by krschau** 2023-06-13 18:34 UTC
Labels: Issue-Bug, Needs-Triage
