### ISSUE TITLE
Link to Azure DevOps

### ISSUE THREAD

**Issue by RachBreeze** [microsoft/devhome#1167] opened 2023-06-18 11:11 UTC
### Suggested new feature or improvement

Be able to link to issues assigned to me in azure devops (and dismiss issues that I wont work on)

### Scenario

In the same way that GitHub Issues are listed in the dashboard it would be useful to have Azure DevOps issues listed

**Comment by krschau** [comment] 2023-06-19 14:27
Duplicate of #521

**Closed by krschau** 2023-06-19 14:27 UTC
Labels: Issue-Feature, Needs-Triage
