### ISSUE TITLE
Error: Get an app to open this 'ms-cloudpc'...

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2902] opened 2024-05-14 19:49 UTC
### Dev Home version

0.1401.495.0

### Steps to reproduce the bug

When running DevHome with a Sandbox and DevBox, but no Windows App installed, i get the following error when i choose the Environments page:

<img width="224" alt="image" src="https://github.com/microsoft/devhome/assets/2146880/f693cbed-f139-43f3-adbc-7e8f515aab02">

### Expected result

I did not expect an error

### Actual result

If we need to pop this error, than I should have been directed to the app that needs to be installed.

### Included Extensions Information

[Logs.zip](https://github.com/microsoft/devhome/files/15313214/Logs.zip)

**Comment by bbonaby** [comment] 2024-05-15 02:18
found the root cause of the issue was due to us attempting to get the Start menu pinning and taskbar pinning status without checking if Dev Box supported it (It won't support it if the Windows app version installed doesn't support it). 

Fixed by #2907

**Closed by bbonaby** 2024-05-15 02:18 UTC
Labels: Issue-Bug, Needs-Triage, Area-Environments
