### ISSUE TITLE
Dashboard does not recover when web experience pack is updated

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#449] opened 2023-05-17 04:20 UTC
### Dev Home version

0.103.135.0

### Windows build number

10.0.25865.1000

### Other software

OS Build Version: 10.0.25865.1000.amd64fre.rs_we_adept.230512-1700
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Dev home running
Be on dashboard
Web experience pack updates
nav to different screen
nav back to dashboard

### Expected result

widgets remain

### Actual result

No widgets recover

On app restart, 1 of 2 widgets showed up

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-13700K
Physical Memory: 63.78GB (42.63GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.102.135.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.103.135.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-02-08 19:44
Duplicate of #742

**Closed by krschau** 2024-02-08 19:44 UTC
Labels: Issue-Bug, Area-Dashboard, Priority-2
