### ISSUE TITLE
Rebooting The PC Widgets Disappers

### ISSUE THREAD

**Issue by Oscuro03** [microsoft/devhome#1152] opened 2023-06-15 13:35 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Putting widgets and reboot PC

### Expected result

The widgets will compare in the screen

### Actual result

Every time i reboot the pc i have to put widgets again

### Included System Information

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Physical Memory: 15.94GB (11.85GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-15 18:05
Duplicate of #742

**Closed by krschau** 2023-06-15 18:05 UTC
Labels: Issue-Bug, Needs-Triage
