### ISSUE TITLE
GPU widget does not detect temperature

### ISSUE THREAD

**Issue by rexmtorres** [microsoft/devhome#1998] opened 2023-12-03 17:36 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Pin/open the GPU widget either on the Dev Home dashboard or the widget board.

I have encountered this on both my machines with NVIDIA GTX 1060 GPU and Radeon RX 7800XT.

### Expected result

GPU widget should show the temperature of the GPU.

### Actual result

GPU widget only shows "--" for the temperature.

### Included System Information

CPU: AMD Ryzen 7 7700X 8-Core Processor             
Physical Memory: 63.75GB (50.04GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-12-04 19:43
Duplicate of #739

**Closed by krschau** 2023-12-04 19:43 UTC
Labels: Issue-Bug, Needs-Triage
