### ISSUE TITLE
Widget are not working on ARM64 - And it works on an Surface Laptop 4 (i7) with the same build.

### ISSUE THREAD

**Issue by jhochwald** [microsoft/devhome#878] opened 2023-05-25 20:57 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22631.1825

### Other software

OS Build Version: 10.0.22631.1825.arm64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Install Dev Home on an Surface Pro 9 (OS build 22631.1825)

### Expected result

Widgets should show results

### Actual result

All Widgets show: "This widget could not be displayed"

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_arm64__8wekyb3d8bbwe

**Comment by jhochwald** [comment] 2023-05-25 20:58
![image](https://github.com/microsoft/devhome/assets/1397168/d8c3beeb-5c3c-41f8-9b0b-e5a1b0c287d6)
This is what it look like!

**Comment by jhochwald** [comment] 2023-05-25 21:00
Whoops, this is a duplicate of #865 and #855 
Therefore, this can be ignored.

**Comment by mathewleeza** [comment] 2023-05-26 02:46
this is a duplicate of https://github.com/microsoft/devhome/issues/865 and https://github.com/microsoft/devhome/issues/855

**Closed by mathewleeza** 2023-05-26 02:46 UTC
Labels: Issue-Bug, Resolution-Duplicate, Needs-Triage

**Comment by krschau** [comment] 2023-05-30 17:38
Duplicate of #855
