### ISSUE TITLE
Do NOT install automatically on Enterprise SKU

### ISSUE THREAD

**Issue by Skorfulose** [microsoft/devhome#3904] opened 2024-09-27 08:32 UTC
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

The Dev Home app keeps getting pushed down to our corporate systems (Windows Enterprise SKU), even after manually removing it from provisioned apps and any installed instances. STOP DOING THAT!

### Actual result

Dev Home app keeps getting installed.

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i7-1365U
Physischer Speicher: 31.69GB (12.92GB free)
Prozessorarchitektur: x64

### Included Extensions Information

Erweiterungen: 
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Core Widget-Erweiterung)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Hyper-V-Erweiterung)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Windows-Subsystem für Linux-Erweiterung)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1800.625.0_x64__8wekyb3d8bbwe (Dev Home-GitHub-Erweiterung (Vorschau))

Widgetdienst: 
MicrosoftWindows.Client.WebExperience_524.24900.80.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-09-27 13:16
Duplicate of #1615, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703
We are working on implementing GPO policies (#3727)

**Closed by krschau** 2024-09-27 13:16 UTC
Labels: Issue-Bug, Needs-Triage
