### ISSUE TITLE
Dashboard keeps resetting

### ISSUE THREAD

**Issue by Seba244c** [microsoft/devhome#789] opened 2023-05-24 12:55 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to Dashboard, add as many widgets as you want, customize them as you want, restart your PC... The widgets are now gone!

### Expected result

I expected my widgets to survive my computer restarting.

### Actual result

After having setup my widgets i shut down laptop, and turning it on agian the widgets are gone. To confirm that this was an issue, i also tried doing it again. After restarting my system the widgets are gone. The widgets do survive closing and opening the application, but restarting the PC it does not.

### Included System Information

CPU: AMD Ryzen 5 4600H with Radeon Graphics         
Physical Memory: 7.87GB (3.01GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-24 20:47
@Seba244c Would you be able to share your log files under `C:\Users\<you>\AppData\Local\Packages\Microsoft.Windows.DevHome_8wekyb3d8bbwe\TempState`? You can share via a OneDrive link or open a Feedback Hub issue and attach a zip file there.

**Comment by krschau** [comment] 2023-05-24 21:28
Duplicate of #742

**Comment by Seba244c** [comment] 2023-05-25 12:04
@krschau Here's a link to a copy of my entire TempState folder [https://1drv.ms/f/s!AjRISoOvMxwk0sQvmVjraB-kMRUoYw?e=PcjqIy](https://1drv.ms/f/s!AjRISoOvMxwk0sQvmVjraB-kMRUoYw?e=PcjqIy)

**Comment by krschau** [comment] 2023-06-01 16:54
Closing since it's a dupe, to keep conversation about this in one place. Thanks for the logs!

**Closed by krschau** 2023-06-01 16:54 UTC
Labels: Issue-Bug, Area-Dashboard, Priority-0
