### ISSUE TITLE
Widgets disappear after restarting Dev Home

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2082] opened 2023-12-28 01:58 UTC
### Dev Home version

0.801.344.0

### Windows build number

10.0.22621.2861

### Other software

OS Build Version: 10.0.22621.2861.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

Add Some Widgets, then restart the application.

### Expected result

It should still be there.

### Actual result

It disappeared.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (3.2GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.800.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.801.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.300.344.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment] 2023-12-28 02:04
Logs: https://1drv.ms/f/s!Aqq-Je19xlrfhFh8beR0rTcSiR_z?e=jMdQx2

**Comment by krschau** [comment] 2023-12-28 15:58
Duplicate of #742

**Closed by krschau** 2023-12-28 15:58 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by skanda890** [comment] 2023-12-29 02:44
Check again.
