### ISSUE TITLE
Can't build the full solution nor update NuGet packages

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/devhome#1330] opened 2023-07-26 10:26 UTC
### Windows build number

22621.1992

### Other software

Visual Studio 2022 17.6.5

### Steps to reproduce the bug

I can't seem to be able to reliably build the whole solution nor to update NuGet packages. I followed all the steps to configure my machine, and have all necessary VS components installed. I also tried deleting and cloning the repo again, cleaning, uninstalling DevHome, etc. I have two issues:
- Trying to build all the solution fails
- Trying to update NuGet packages just fails and rolls back

If I build the whole solution, I get this:

```
Build started...
1>------ Build started: Project: DevHome.UITest, Configuration: Debug x64 ------
2>------ Build started: Project: DevHome.Common, Configuration: Debug x64 ------
1>DevHome.UITest -> C:\Users\sergiopedri\git\devhome\uitest\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.UITest.dll
2>Target assembly has already been patched. Exiting early as there is no work to do.
2>DevHome.Common -> C:\Users\sergiopedri\git\devhome\common\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.Common.dll
3>------ Build started: Project: DevHome.Settings, Configuration: Debug x64 ------
4>------ Build started: Project: DevHome.Dashboard, Configuration: Debug x64 ------
5>------ Build started: Project: SampleTool, Configuration: Debug x64 ------
4>Target assembly has already been patched. Exiting early as there is no work to do.
4>DevHome.Dashboard -> C:\Users\sergiopedri\git\devhome\tools\Dashboard\DevHome.Dashboard\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.Dashboard.dll
3>Target assembly has already been patched. Exiting early as there is no work to do.
3>DevHome.Settings -> C:\Users\sergiopedri\git\devhome\settings\DevHome.Settings\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.Settings.dll
6>------ Build started: Project: DevHome.SetupFlow, Configuration: Debug x64 ------
6>Target assembly has already been patched. Exiting early as there is no work to do.
6>DevHome.SetupFlow -> C:\Users\sergiopedri\git\devhome\tools\SetupFlow\DevHome.SetupFlow\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.SetupFlow.dll
7>------ Build started: Project: DevHome, Configuration: Debug x64 ------
5>Failed to resolve WinRT.Runtime.dll.
7>Target assembly has already been patched. Exiting early as there is no work to do.
5>SampleTool -> C:\Users\sergiopedri\git\devhome\tools\SampleTool\src\bin\x64\Debug\net6.0-windows10.0.22000.0\SampleTool.dll
7>DevHome -> C:\Users\sergiopedri\git\devhome\src\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.dll
7>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1500,5): error APPX1101: Payload contains two or more files with the same destination path 'WinRT.Runtime.dll'. Source files: 
7>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1500,5): error APPX1101: C:\Users\sergiopedri\git\devhome\packages\microsoft.windows.sdk.net.ref\10.0.22000.29\lib\net6.0\WinRT.Runtime.dll
7>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1500,5): error APPX1101: C:\Users\sergiopedri\git\devhome\packages\microsoft.windows.cswinrt\2.0.1\lib\net6.0\WinRT.Runtime.dll
7>Done building project "DevHome.csproj" -- FAILED.
8>------ Build started: Project: DevHome.SetupFlow.UnitTest (Tools\Dashboard\DevHome.SetupFlow.UnitTest), Configuration: Debug x64 ------
9>------ Build started: Project: SampleTool.UnitTest, Configuration: Debug x64 ------
10>------ Build started: Project: DevHome.SetupFlow.UnitTest (Tools\SetupFlow\DevHome.SetupFlow.UnitTest), Configuration: Debug x64 ------
11>------ Build started: Project: DevHome.Test, Configuration: Debug x64 ------
8>Failed to resolve WinRT.Runtime.dll.
11>Failed to resolve WinRT.Runtime.dll.
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018: The "GetSdkFileFullPath" task failed unexpectedly.
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018: System.ObjectDisposedException: Cannot access a disposed object.
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018: Object name: 'it is not allowed to use disposed Microsoft.VisualStudio.Telemetry.TelemetrySession object.'.
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.VisualStudio.Telemetry.TelemetryDisposableObject.RequiresNotDisposed()
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.VisualStudio.Telemetry.TelemetrySession.SerializeSettings()
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.Build.AppxPackage.Telemetry.Get(IBuildEngine4 buildEngine, String vsTelemetrySession)
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskHelper..ctor(IBuildEngine4 buildEngine, TaskLoggingHelper logger, Action execute, Func`2 exceptionHandler, Action cleanup, Func`1 manifestFileNameGetter, String vsTelemetrySession)
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskBase.Execute()
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
11>C:\Users\sergiopedri\git\devhome\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\MrtCore.PriGen.targets(380,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
11>Done building project "DevHome.Test.csproj" -- FAILED.
10>Failed to resolve WinRT.Runtime.dll.
9>Failed to resolve WinRT.Runtime.dll.
8>DevHome.SetupFlow.UnitTest -> C:\Users\sergiopedri\git\devhome\tools\Dashboard\DevHome.Dashboard.UnitTest\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.SetupFlow.UnitTest.dll
10>DevHome.SetupFlow.UnitTest -> C:\Users\sergiopedri\git\devhome\tools\SetupFlow\DevHome.SetupFlow.UnitTest\bin\x64\Debug\net6.0-windows10.0.22000.0\DevHome.SetupFlow.UnitTest.dll
9>SampleTool.UnitTest -> C:\Users\sergiopedri\git\devhome\tools\SampleTool\unittest\bin\x64\Debug\net6.0-windows10.0.22000.0\SampleTool.UnitTest.dll
========== Build: 6 succeeded, 5 failed, 7 up-to-date, 0 skipped ==========
```

Interestingly, I _can_ build and deploy the DevHome project on its own.

I get similar errors if I try to update some NuGet packages for the solution (ie. in multiple projects):

![](https://github.com/microsoft/devhome/assets/10199417/4dc4a216-aa34-4136-9dfd-878207ab1396)

### Expected result

I expect the full solution to build correctly and with no errors/warnings after cloning the repo and installing all requirements.

**Comment by krschau** [comment] 2023-07-26 14:50
@AmelBawa-msft Is this the build error you were seeing recently due to VS version?

**Comment by AmelBawa-msft** [comment] 2023-07-26 16:42
@krschau,  yes. A workaround that fixed this for me and another dev is rolling back to a previous version of Visual Studio using the Visual Studio Installer (17.6.5 -> 17.6.3).

@Sergio0694, if rolling back worked for you, please give a 👍to this thread: https://developercommunity.visualstudio.com/t/Unable-to-build-Windows-DevHome-after-up/10420396

**Comment by EricJohnson327** [comment] 2023-07-26 17:40
@Sergio0694 Added CommunityToolkit.Mvvm 8.2.1 to the upstream feed.  Please reopen this issue if this or @AmelBawa-msft suggestion don't resolve the issue.

**Comment by MattHyman** [comment] 2023-07-26 20:25
@EricJohnson327; can you please explain how you root caused this issue and why updating the NuGet fixed it?

**Comment by MattHyman** [comment] 2023-07-26 22:04
I have confirmed that this fix worked for me.

**Comment by Sergio0694** [comment] 2023-07-30 22:15
I still can't build on 17.6.5, same error, but I see the VS Feedback item has been closed...? 🤔

There's something weird with the DevHome solution and I'm not sure what it is. Let alone the fact that I can't build at all on 17.6.5, there's also the fact that if I try to build, then close VS, then try to clean the repo, it'll fail saying some files are still in use. I need to log out and log back into Windows again every single time in order to clean the solution (`git clean -fdx`) 😶

Also, not sure why this issue has been closed. This build error is completely unrelated from me trying to upgrade the MVVM Toolkit to 8.2.1, which was in fact blocked by that missing package approval. But I can't build main either 😅

I can confirm that **rolling back to VS 17.6.3 did solve the issue**, and I can now build the solution.

**Comment by AmelBawa-msft** [comment] 2023-08-04 16:32
PR merged. Closing. Re-activate if necessary.

**Closed by AmelBawa-msft** 2023-08-04 16:32 UTC
Labels: Issue-Bug, Area-Build, Resolution-Fix-Available

**Comment by Scottj1s** [comment] 2023-12-15 19:06
FYI - this seems to have helped others:
for VS builds: 
`>set MSBUILDDISABLENODEREUSE=1`
for MSBuilds: (above) or 
`>msbuild /nodeReuse:false ...`
