### ISSUE TITLE
No Data Gathering After Reboot The App

### ISSUE THREAD

**Issue by Oscuro03** [microsoft/devhome#1149] opened 2023-06-15 10:59 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Inserire i widget di sistema (CPU, …) e riavviare l'app

### Expected result

Mi aspettavo che la ricezione dei dati sarebbe ricominciata anche  dopo il riavvio

### Actual result

Una volta aggiunti i widget e chiusa e riaperta l'app si blocca la ricezione dei dati da CPU, Schede di rete, Memoria e GPU

### Included System Information

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Physical Memory: 15.94GB (10.57GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-15 13:27
Bing Translate:

Insert system widgets (CPU, ...) and restart the app

I expected that receiving data would start again even after rebooting

Once widgets are added and the app is closed and reopened, it blocks the reception of data from CPU, Network Adapters, Memory and GPU

**Comment by krschau** [comment] 2023-06-15 13:27
Duplicate of #728

**Closed by krschau** 2023-06-15 13:27 UTC
Labels: Issue-Bug, Needs-Triage
