### ISSUE TITLE
Jira add-on

### ISSUE THREAD

**Issue by Branpolo** [microsoft/devhome#3181] opened 2024-06-10 05:37 UTC
### Suggested new feature or improvement

Jira by Atlassian is an extremely popular tool for developers. It has nearly 90% of the bug and issue tracking market. It would be great to have a Jira extension to view and manage workloads.

### Scenario

View/update/create tasks within Dev.Home (eg using the Jira API)

**Comment by adrastogi** [comment] 2024-06-10 05:48
Thanks, @Branpolo! #1168 seems similar to this- if you agree, would you mind upvoting that one? I can duplicate this request against that one.

**Comment by krschau** [comment] 2024-06-10 13:18
Duplicate of #1168

**Closed by krschau** 2024-06-10 13:18 UTC
Labels: Issue-Feature, Needs-Triage
