### ISSUE TITLE
Stop auto-installing this kind of garbage on people's computers

### ISSUE THREAD

**Issue by mcgonrya** [microsoft/devhome#3974] opened 2024-11-12 15:43 UTC
Every time any of my computers gets an update, a random piece of garbage software auto-installs itself. Not sure who at microsoft gives the "ok" to do this, but it's really annoying.

Nobody asked for "Dev Home" to be installed on all their computers, so why is automatically installing it considered acceptable? Is there NO ONE at microsoft that sees this as being annoying? It's the same thing with some different garbage EVERY SINGLE UPDATE CYCLE.

Please stop.

**Comment by krschau** [comment] 2024-11-18 14:21
Duplicate of #1615, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703

**Closed by krschau** 2024-11-18 14:21 UTC
Labels: Needs-Triage
