### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by HarjitSi** [microsoft/devhome#2216] opened 2024-02-03 18:42 UTC
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22621.2428

### Other software

OS Build Version: 10.0.22621.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

There is no option to uninstall

### Expected result

First off it shouldn't be installed. There should be a way to uninstall.

### Actual result

app was installed without permission

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe

Widget Service:

**Comment by krschau** [comment] 2024-02-05 15:37
Duplicate of #1615

**Closed by krschau** 2024-02-05 15:37 UTC
Labels: Issue-Bug, Needs-Triage
