### ISSUE TITLE
Memory widget scrollable at medium

### ISSUE THREAD

**Issue by crutkas** [microsoft/devhome#1392] opened 2023-08-10 21:35 UTC
### Dev Home version

0.401.219.0

### Windows build number

10.0.25926.1001

### Other software

OS Build Version: 10.0.25926.1001.amd64fre.rs_we_adept.230805-1700
.NET Version: .NET 6.0.20

### Steps to reproduce the bug

have a stock memory widget with 100DPI

### Expected result

no scroll bars and fits in 1 medium size widget
![image](https://github.com/microsoft/devhome/assets/1462282/81bd6569-4a63-4286-a361-f7ca01dec329)

### Actual result

scroll bars and scrollable

### Included System Information

Physical Memory: 31.84GB (16.66GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome.Canary_0.401.219.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension.Canary_0.400.219.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-08-10 21:49
Duplicate of #1281

**Closed by krschau** 2023-08-10 21:49 UTC
Labels: Issue-Bug, Needs-Triage
