### ISSUE TITLE
DEV HOME APP CLOSES AFTER CLICKING ON ADD REPO

### ISSUE THREAD

**Issue by WMOriginalz15** [microsoft/devhome#2512] opened 2024-04-02 00:35 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3374

### Other software

OS Build Version: 10.0.22631.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

when i click on add repository the dev home app automatically closes

### Expected result

it's suppose to open another dialog windows for me to create my repo

### Actual result

it closes dev home app

### Included System Information

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Physical Memory: 23.87GB (15.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.310.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-04-02 14:05
Duplicate of #2485

**Closed by krschau** 2024-04-02 14:05 UTC
Labels: Issue-Bug, Needs-Triage
