### ISSUE TITLE
UAC prompt when installing new application makes the app seem broken

### ISSUE THREAD

**Issue by mrlacey** [microsoft/devhome#775] opened 2023-05-24 07:55 UTC
### Suggested new feature or improvement

Make the app not seem to be doing nothing when installing an app causes the UAC prompt to be opened in the background.
Or, ideally, cause the UAC prompt to be opened as the topmost app, not in the background.

### Scenario

Went to install an application.
clicked install
the app looked like it was being slow so went to do another task
after a while, I noticed the UAC icon in the taskbar.
Canceled the UAC prompt as I didn't know what had opened it
returned to the Dev Home app to see that the installation had failed due to being "canceled by the user"
clicked retry
then noticed the UAC icon in the taskbar appear after a few seconds.

**Comment by AmelBawa-msft** [comment] 2023-05-24 08:22
Likely duplicate of #732

**Comment by krschau** [comment] 2023-05-24 20:22
Duplicate of #732

**Closed by krschau** 2023-05-24 20:22 UTC
Labels: Issue-Feature, Needs-Triage
