### ISSUE TITLE
how the f.. did this got auto-installed by MS Store?

### ISSUE THREAD

**Issue by R-Adrian** [microsoft/devhome#2380] opened 2024-03-08 18:51 UTC
### Dev Home version

0.1101.416.0

### Windows build number

10.0.19045.4123

### Other software

OS Build Version: 10.0.19045.4123.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Discover this spyware/unwanted app suddenly popped in existence on MS Store in the library list of apps that *need* an update.
HUH?  Update for ... what? 
I never installed it / got informed consent about this spyware the first place... how did it get installed?

### Expected result

why the f did this get auto-installed and there is no way to uninstall it?
appwiz.cpl - no such app,
Settings -> apps & features has no such app listed either.

### Actual result

Actual result? got hijacked by Microsoft.

**Comment by R-Adrian** [comment] 2024-03-08 18:56
update: let it to chew on the so-called update, closed settings app, re-opened it... and only NOW there is a dev home EXTENSION app listed... but not the main app...
And i'm not allowed to uninstall even the "extension"... ?? Extension for what? The uninstall button is grayed out.

![image](https://github.com/microsoft/devhome/assets/16319504/b059c1aa-a49d-49ff-8150-6be06c988f4e)

![image](https://github.com/microsoft/devhome/assets/16319504/74f78581-c4d0-4791-af9b-a3ee3d6711bc)

**Comment by krschau** [comment] 2024-03-08 22:14
You should be able to uninstall the Dev Home GitHub Extension from the Apps & Features page. It's possible it was greyed out while it was still being installed.

Duplicate of #1615

**Closed by krschau** 2024-03-08 22:14 UTC
Labels: Issue-Bug, Needs-Triage
