### ISSUE TITLE
I'm trying to remove Dev Home

### ISSUE THREAD

**Issue by 2300000** [microsoft/devhome#3867] opened 2024-09-15 21:17 UTC
### Dev Home version

0.1701.597.0

### Windows build number

10.0.19045.4894

### Other software

OS Build Version: 10.0.19045.4894.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Hello, I'm trying to remove Dev Home, I've tried everything, all the advice on the Internet, except for the PowerShell program - I'm afraid to use it. Please tell me how to do this safely? Thank you in advance.

Best regards, Denis.

### Actual result

Nothing worked! I haven't tried PowerShell.

### Included System Information

CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
Physical Memory: 3.77GB (0.69GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.5.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-09-16 13:19
Duplicate of #1615

**Closed** 2024-09-16 13:19 UTC
Labels: Issue-Bug, Needs-Triage
