### ISSUE TITLE
'Account type' section header is out of spec (Settings > Accounts)

### ISSUE THREAD

**Issue by TWhiteDesigns** [microsoft/devhome#1144] opened 2023-06-13 20:01 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open Dev Home > Click on settings icon in lower left nav > Click on Accounts > Observe 'GitHub' section header text.

### Expected result

The text 'GitHub' which is the account type section header text. Appears to be too large (Spec calls for Body Large - 14px) and might be left aligned beyond the left margin (but likely not - could just be the size of the text and the letter G making it appear to sit too far left.

Additionally, there appears to be not even vertical space between the 'Add accounts' line item and the 'GitHub' header title. Figma has the text box for header titles at 42px tall. List items have 4px of padding.

### Actual result

Account type header title appears to be too large (Spec calls for Body strong - 14px)

Too little vertical spacing between 'Add account' line item and section header 'GitHub' 

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Physical Memory: 31.85GB (11.66GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.GitHub_1.0.0.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-13 20:12
@TWhiteDesigns Can you link to or screenshot the spec?

**Comment by TWhiteDesigns** [comment] 2023-06-13 21:25
Actual result: 
<img width="215" alt="image" src="https://github.com/microsoft/devhome/assets/127447480/ea26166c-d126-426d-9015-645b967d8d5f">

Expected result:
<img width="270" alt="image" src="https://github.com/microsoft/devhome/assets/127447480/5269982e-fae2-4d26-a81a-a4ed437c8e36">

**Comment by niels9001** [comment] 2023-06-13 22:02
@krschau @TWhiteDesigns I believe this is fixed in: https://github.com/microsoft/devhome/pull/688 (see screenshot)

**Closed** 2023-06-15 22:10 UTC
Labels: Issue-Bug, Needs-Triage, Area-Style, Needs-FitAndFinish

**Comment by krschau** [comment] 2023-06-16 14:39
Duplicate of #688
