### ISSUE TITLE
Repo not visible

### ISSUE THREAD

**Issue by CraftyRyte** [microsoft/devhome#1627] opened 2023-09-30 13:55 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

I cloned a repo, it showed go to dashboard, did not see it there

### Expected result

I was expecting a widget of that repo

### Actual result

I say nothing

### Included System Information

Physical Memory: 7.77GB (1.31GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by asklar** [comment] 2023-10-10 18:11
See #1049, would that solve this issue?

**Comment by CraftyRyte** [comment] 2023-10-11 01:05
Yep

**Comment by krschau** [comment] 2023-10-13 20:13
Duplicate of #702

**Closed by krschau** 2023-10-13 20:13 UTC
Labels: Issue-Bug, Needs-Triage
