### ISSUE TITLE
The close button is not functioning correctly in the short minimize model.

### ISSUE THREAD

**Issue by junaidnasir1001** [microsoft/devhome#2180] opened 2024-01-25 13:20 UTC
### Dev Home version

0.901.374.0

### Windows build number

10.0.23619.1000

### Other software

OS Build Version: 10.0.23619.1000.amd64fre.ni_prerelease.240112-1054
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

1. Open the De Home in short screen
2. click on "add new widgets"
3. now if you close the model it will not close 

### Expected result

Clicking the close button on any screen size the model should close the page.

### Actual result

The close button is not closing the Model.

### Included System Information

CPU: Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
Physical Memory: 7.89GB (1.28GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.901.374.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.1301.40.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-01-25 15:03
Duplicate of #537

**Closed by krschau** 2024-01-25 15:03 UTC
Labels: Issue-Bug, Needs-Triage
