### ISSUE TITLE
Cannot clone repos from GitHub account

### ISSUE THREAD

**Issue by yesseruser** [microsoft/devhome#1355] opened 2023-08-03 07:03 UTC
### Dev Home version

0.301.198.0

### Windows build number

10.0.22631.2129

### Other software

OS Build Version: 10.0.22631.2129.arm64fre.ni_release.220506-1250
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

1. Go to Machine configuration
2. Select End-to-end setup
3. Select add repository
4. Select Account
5. Tick a repo
6. Click Add, then Next and Next again
7. Click Set up
8. Observe the issue

### Expected result

The repository should have normally cloned to the selected folder.

### Actual result

It stated Couldn't clone <Repository name>. The repository did not clone.

### Included System Information

Physical Memory: 5.99GB (0.76GB free)
Processor Architecture: ARMx64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_arm64__8wekyb3d8bbwe

**Comment by dhoehna** [comment] 2023-08-07 19:06
Duplicate of #978

**Closed** 2023-08-07 19:06 UTC
Labels: Issue-Bug, Area-Machine-Config, Needs-Triage, Area-Machine-Config-Repo
