### ISSUE TITLE
Make the About column in the Settings fully down like in Phone Link

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2088] opened 2023-12-30 02:53 UTC
### Suggested new feature or improvement

Make the About column in the Settings fully down lik in Phone Link.

### Scenario

This is used to make Dev Home have a similar touch with Phone Link.

**Comment by krschau** [comment] 2024-01-06 18:57
Duplicate of #2063

**Closed by krschau** 2024-01-06 18:57 UTC
Labels: Area-Settings, Issue-Task, Needs-Design
