### ISSUE TITLE
Bloat

### ISSUE THREAD

**Issue by TempiresG** [microsoft/devhome#2997] opened 2024-05-25 19:59 UTC
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.3593

### Other software

OS Build Version: 10.0.22631.3593.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

1.have windows updates
2. Try uninstall bloatware

### Expected result

1.system without bloatware called "Dev Home"
2. able to uninstall bloatware called "Dev Home"

### Actual result

1.bloatware "Dev Home" is installed. 
2. Bloatware infects windows by not letting itself to be uninstalled like normal program, powershell needed. 

Why is this  bloatware even installed on every single windows in first place? why does Microsoft think every home user needs some dev tool? Why is it that non-tech savy users this bloatware is distributed to won't be able to uninstall?

**Comment by Aaron-Junker** [comment] 2024-05-26 18:43
Dev Home only installs itsself if you have developer intent checked in OOBE.

**Comment by krschau** [comment] 2024-05-30 14:21
Duplicate of #1615

**Closed by krschau** 2024-05-30 14:21 UTC
Labels: Issue-Bug, Needs-Triage
