### ISSUE TITLE
APPLICATION

### ISSUE THREAD

**Issue by AYUSHUP2518** [microsoft/devhome#1600] opened 2023-09-27 18:58 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

NOT ABLE TO INSTALL APPLICATIONS WHEN CLICKED ON INSTALLED APPS

### Expected result

APPS MUST BE INSTALLED BUT NO APSS IS SHOWING

### Actual result

NO APPS ARE SHOWN TO INSTALL

### Included System Information

Physical Memory: 7.7GB (1.34GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-09-27 23:30
Duplicate of #1596

**Closed by krschau** 2023-09-27 23:30 UTC
Labels: Issue-Bug, Needs-Triage
