### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by mika76** [microsoft/devhome#905] opened 2023-05-27 11:45 UTC
### Suggested new feature or improvement

Not sure if this was planned but I can only see this in the store on my Windows 11 pc - I see no reason why Windows 10 would not be supported.

### Scenario

There are lots of Windows 10 users.

**Comment by asklar** [comment] 2023-05-28 22:32
Widgets (which are used by the DevHome dashboard) are not currently supported on Windows 10.

**Comment by mika76** [comment] 2023-05-29 06:43
@asklar Do you mean they are used internally within the app, or that the app has a widget which can be added to the windows 11 widgets view?

**Comment by asklar** [comment] 2023-05-29 07:02
Widgets are part of the app (the "dashboard" feature/page), widgets are shown inside of the app.

**Comment by mika76** [comment] 2023-05-29 07:14
Ok I've just looked them up but are they not part of WinUI 3 which it states at https://learn.microsoft.com/en-us/windows/apps/winui/

> WinUI 3 works downlevel to Windows 10 October 2018 Update (Version 1809, OS build 17763).

**Comment by asklar** [comment] 2023-05-29 20:38
No, widgets are a separate component from WinUI. WinUI 3 works downlevel, but the Widget platform (which Widgets depends on) does not currently run on windows 10. We're looking into what it would take to bring devhome downlevel.

**Comment by krschau** [comment] 2023-05-30 18:14
Duplicate of #683

**Closed by krschau** 2023-05-30 18:14 UTC
Labels: Issue-Feature, Needs-Triage
