### ISSUE TITLE
Check for updates external apps

### ISSUE THREAD

**Issue by exldna** [microsoft/devhome#1267] opened 2023-07-08 09:44 UTC
### Suggested new feature or improvement

We have many tools and applications that installed on our devices that updates for we must track. I think, devhome can provide simple behaviour - just press one button to get all updates. For example I want to say devhome, where that can be found all tools for c++ dev like cmake, git, visual studio, clion and etc. and after that I would be able to get some notifications about new versions and clicked on button update all that apps.

### Scenario

manage apps
we should open devhome, select section calls like "installed apps", where we can show list for all tracking apps. also we can add new apps in list for any ways: install new app or search on device. and near with list of apps we can press check for updates and get all updates (something like in microsoft store)
get notifications
we would be able to turn off notifications in settings
when the new version of app available - user get notification about

### Additional details

May be we want to separate our tools for lists like tools for c++, tools for python, networking, etc. And provide that lists like final environments for development.

**Comment by denelon** [comment] 2023-07-11 18:07
Duplicate of #1067

* #1067

**Closed** 2023-07-11 18:08 UTC
Labels: Issue-Feature, Area-Machine-Config
