### ISSUE TITLE
I can not connect another Github acccount

### ISSUE THREAD

**Issue by andre-carbajal** [microsoft/devhome#2297] opened 2024-02-22 15:49 UTC
### Dev Home version

0.1101.416.0

### Windows build number

10.0.22631.3155

### Other software

OS Build Version: 10.0.22631.3155.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Login to a github account and then try to login to another github account.

### Expected result

![image](https://github.com/microsoft/devhome/assets/40127869/262f96a8-8da9-40ac-bcb4-268a44182052)

### Actual result

An error occurs that does not allow to start the session

### Included System Information

CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Physical Memory: 15.81GB (9.6GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHomeAzureExtension_0.600.416.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.40.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-02-22 17:15
This feature came out in yesterday's update.

**Comment by krschau** [comment] 2024-02-22 17:16
Duplicate of #2282

**Closed by krschau** 2024-02-22 17:16 UTC
Labels: Issue-Bug, Needs-Triage
