### ISSUE TITLE
Add an uninstall button.

### ISSUE THREAD

**Issue by HylianKirby** [microsoft/devhome#3972] opened 2024-11-11 03:13 UTC
### Suggested new feature or improvement

Not everyone wants or needs to use this software, and for people like me it just takes up unnecessary space. Add an uninstall button.

### Scenario

I don't know what this app does, nor do I care. I just want it off my device.

### Additional details

🖕

**Comment by mcgonrya** [comment] 2024-11-12 15:43
Microsoft needs to stop installing stuff like this without permission.

**Comment by krschau** [comment] 2024-11-18 14:21
Duplicate of #1615, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703

**Closed by krschau** 2024-11-18 14:21 UTC
Labels: Issue-Feature, Needs-Triage
