### ISSUE TITLE
Export current computer config

### ISSUE THREAD

**Issue by hannesne** [microsoft/devhome#829] opened 2023-05-24 22:42 UTC
### Suggested new feature or improvement

I would love to be able to export my current config, including applications that could be installed using winget and other mechanisms. 

### Scenario

I would use this when I have to shift to a new computer or rebuild my computer.

**Comment by AmelBawa-msft** [comment] 2023-05-24 23:22
Possibly a duplicate #721

**Comment by AmelBawa-msft** [comment] 2023-05-25 20:58
Closing to track all export config features in one issue.

**Closed by AmelBawa-msft** 2023-05-25 20:58 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by krschau** [comment] 2023-05-30 17:14
Duplicate of #721
