### ISSUE TITLE
Dev Home Settings: Breadcrumb title text and chevron glyph out of spec

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#570] opened 2023-05-18 21:56 UTC
### Steps to reproduce the bug

Description
Currently, (Build 102.130) The Settings title text has the improper color on the first title text 'Settings' when in an L2 page. The first title in the breadcrumb trail 'Settings' Should be shown in the Secondary text color, when viewing a settings L2 page. Additionally, the right chevron glyph is too small and not center aligned with the text.

**Comment by krschau** [comment] 2023-07-31 19:34
Duplicate of #1143

**Closed by krschau** 2023-07-31 19:34 UTC
Labels: Issue-Bug, Area-Settings, Priority-2, Area-Style
