### ISSUE TITLE
Azure DevOps

### ISSUE THREAD

**Issue by AgSurfer13** [microsoft/devhome#810] opened 2023-05-24 18:16 UTC
### Suggested new feature or improvement

Where is Azure DevOps?

### Scenario

All of my repos aree in Azure DevOps, not GitHub. Are you adding support for Azure DevOps?

**Comment by adrastogi** [comment] 2023-05-24 18:35
I believe this is being tracked by #521.

**Comment by krschau** [comment] 2023-05-24 21:11
Duplicate of #521

**Closed by krschau** 2023-05-24 21:11 UTC
Labels: Issue-Feature, Needs-Triage
