### ISSUE TITLE
Add repo already cloned to local drive

### ISSUE THREAD

**Issue by csymonds** [microsoft/devhome#737] opened 2023-05-23 17:50 UTC
### Suggested new feature or improvement

Unless I am missing it, I cannot seem to add a repo that I have already cloned to my local drive. I don't want to have to clone it again.

### Scenario

If I already have a repo cloned to my local computer, I would like to add that repo instead of having to clone again. If this is already possible, it is not obvious how to do it.

**Comment by krschau** [comment] 2023-05-23 18:01
Duplicate of #703

**Closed by krschau** 2023-05-23 18:01 UTC
Labels: Issue-Feature, Needs-Triage, Area-Repo Management

**Comment by krschau** [comment] 2023-05-25 14:21
Duplicate of #780
