### ISSUE TITLE
Not Saving System Resource Widgets

### ISSUE THREAD

**Issue by boombrusher** [microsoft/devhome#881] opened 2023-05-25 23:33 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Set sys widgets, close app, start app

### Expected result

widgets are saved after restarting app

### Actual result

not saved

### Included System Information

CPU: AMD Ryzen 5 2600 Six-Core Processor            
Physical Memory: 31.93GB (16.24GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-30 17:48
Duplicate of #724

**Closed by krschau** 2023-05-30 17:48 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Triage
