### ISSUE TITLE
Weird white line

### ISSUE THREAD

**Issue by Fish-Soup-Dev** [microsoft/devhome#1045] opened 2023-06-04 06:33 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.23471.1000

### Other software

OS Build Version: 10.0.23471.1000.amd64fre.ni_prerelease.230526-1341
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

When I drag to resize the window I see a line from the top left to the bottom right flicker on the screen.

### Expected result

To not see a line.

### Actual result

I saw a line

### Included System Information

CPU: AMD Ryzen 9 3900X 12-Core Processor            
Physical Memory: 31.93GB (19.94GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-14 21:49
Closing as I can't reproduce this. If you still see it, let me know. It would be helpful to know if there's a specific page where it happen, what theme your OS is in, and what theme your app is set to.

**Closed by krschau** 2023-11-14 21:49 UTC
Labels: Issue-Bug, Needs-Repro, Priority-3, Area-Core
