### ISSUE TITLE
PI process is started without the user launching it

### ISSUE THREAD

**Issue by kanismohammed** [microsoft/devhome#3412] opened 2024-07-11 18:56 UTC
### Steps to reproduce the bug

1. Launch Dev Home

### Expected result

PI does not start until it is launched by the user in the Utilities page.

### Actual result

PI launches without the user noticing.

**Comment by kanismohammed** [comment] 2024-07-11 18:56
![image](https://github.com/user-attachments/assets/58af3bcb-8bb0-4aa4-af6e-df09b8b5c7f5)

**Comment by jaholme** [comment] 2024-07-11 19:10
Fixed in #3308

**Closed by jaholme** 2024-07-11 19:10 UTC
Labels: Issue-Bug, Needs-Triage, Area-PI

**Comment by jaholme** [comment] 2024-07-11 19:12
If you have that fix and the experimental feature is enabled that is by design to support the Win-F12 hotkey.
