### ISSUE TITLE
Changing Theme To Dark Mode on First Launch Causes UI Errors

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#993] opened 2023-05-31 21:58 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Fresh Install of Dev Home from Microsoft Store 
2. Navigate to the Settings and change to dark mode 
3. The end-result is a extremely light UI that is not usable

### Expected result

The application changes to dark mode

### Actual result

The application UI experience became very light and didn't seem to function as expected.

### Included System Information

CPU: Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
Physical Memory: 63.95GB (57.02GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by joadoumie** [comment] 2023-05-31 21:58
<img width="949" alt="image" src="https://github.com/microsoft/devhome/assets/98557455/ba05c3e2-136d-4274-be25-3b5a565dea1c">

**Comment by cinnamon-msft** [comment] 2023-05-31 22:33
Duplicate of #511

**Comment by krschau** [comment] 2023-07-10 14:09
Reopening, this is a valid bug in v0.2

**Comment by pehammer** [comment] 2023-10-12 17:45
Sometimes the title remains wrong theme after a theme change, but everything else updates
<img width="571" alt="image" src="https://github.com/microsoft/devhome/assets/112589934/94d4f160-7c8e-4428-b990-9df58ebc87c0">

**Comment by krschau** [comment] 2023-10-27 14:46
> Sometimes the title remains wrong theme after a theme change, but everything else updates <img alt="image" width="571" src="https://user-images.githubusercontent.com/112589934/274685939-94d4f160-7c8e-4428-b990-9df58ebc87c0.png">

This was a separate regression, fixed by #1759

**Comment by krschau** [comment] 2024-08-20 20:27
I can no longer reproduce this on version 0.1701.

**Closed by krschau** 2024-08-20 20:27 UTC
Labels: Issue-Bug, Priority-2, Type-Style, Area-Core
