### ISSUE TITLE
Can't add account github

### ISSUE THREAD

**Issue by muftifachrudin** [microsoft/devhome#1674] opened 2023-10-10 02:41 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

i try this dev home app (preview) and download extensions GitHub to integrated code from project and not show pop up to integrated acc github

### Expected result

fix to add account GitHub and another integrated another GitHub acc

### Actual result

Dev Home still cannot add account github

### Included System Information

Physical Memory: 7.88GB (1.29GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by vineeththomasalex** [comment] 2023-10-13 20:48
Looks like a duplicate of #1634

**Closed by vineeththomasalex** 2023-10-13 20:48 UTC
Labels: Issue-Bug, Area-Account-Sign-In
