### ISSUE TITLE
Can't add second GitHub account

### ISSUE THREAD

**Issue by MicheleMontesi** [microsoft/devhome#2000] opened 2023-12-03 21:44 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

It says that something went wrong when I clicked add account

### Expected result

Form to add a second GitHub account

### Actual result

Error

**Comment by krschau** [comment] 2023-12-04 20:11
Duplicate of https://github.com/microsoft/devhomegithubextension/issues/276

**Closed by krschau** 2023-12-04 20:11 UTC
Labels: Issue-Bug, Needs-Triage
