### ISSUE TITLE
Abnormal display of content in the Dashboard

### ISSUE THREAD

**Issue by biiigwang** [microsoft/devhome#1887] opened 2023-11-13 01:38 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2428

### Other software

OS Build Version: 10.0.22631.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

1. Update the system to Windows 11 23H2,
2. Open Dev Home,
3. Enter the dashboard to add widgets and fix them.

### Expected result

I hope to display the content in the widget normally.

### Actual result

There are no numerical values in the content of the widget, only placeholders.
![Photo](https://github.com/microsoft/devhome/assets/26035594/6afc1a7d-419b-42b4-8cf5-445f0b394e3a)

### Included System Information

Physical Memory: 15.34GB (8.86GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-13 20:49
Duplicate of #1248

**Closed by krschau** 2023-11-13 20:49 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Triage
