### ISSUE TITLE
Error al cerrar ventana de widget

### ISSUE THREAD

**Issue by marco5x** [microsoft/devhome#802] opened 2023-05-24 17:40 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Al presionar la ventana de agregar widget, y presionar el botón X para cerrar. no cierra la ventana, y tengo que cerrar el programa y volver a entrar

### Expected result

Al presionar el botón X, en la ventana de widget se cierre la mencionada ventana

### Actual result

No cierra la ventana

### Included System Information

CPU: Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz
Physical Memory: 15.72GB (8.31GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-24 21:07
Duplicate of #537 

@marco5x If don't think this is a duplicate, please let me know.

**Comment by krschau** [comment] 2023-05-24 21:07
Duplicate of #537

**Closed by krschau** 2023-05-24 21:07 UTC
Labels: Issue-Bug, Needs-Triage
