### ISSUE TITLE
Cannot see any repo in dashboard after clone from the app

### ISSUE THREAD

**Issue by himself65** [microsoft/devhome#1653] opened 2023-10-04 00:42 UTC
### Dev Home version

0.503.261.0

### Windows build number

1000.22674.1000.0

### Steps to reproduce the bug

After I clone one repo from the app, I cannot see that repo in the app.

![image](https://github.com/microsoft/devhome/assets/14026360/e2d7e313-43a4-4dee-a838-47fe69284194)

### Expected result

I think the repo I cloned should be shown in somewhere.

### Actual result

Cannot find it in the app. When I clone twice, it's says the directory is not empty.

**Comment by asklar** [comment] 2023-10-10 18:10
See #1049, would this solve this problem?

**Comment by himself65** [comment] 2023-10-10 18:58
I think so

**Comment by krschau** [comment] 2024-03-15 14:23
Duplicate of #702

**Closed by krschau** 2024-03-15 14:23 UTC
Labels: Issue-Bug, Area-Machine-Config

**Comment by skanda890** [comment] 2024-04-06 13:26
It somewhat different.
