### ISSUE TITLE
Uses a lot of CPU while not doing anything

### ISSUE THREAD

**Issue by eggbean** [microsoft/devhome#3183] opened 2024-06-10 08:08 UTC
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22631.3672

### Other software

OS Build Version: 10.0.22631.3672.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

I just have the application open, not doing anything, yet it is using around 8% of my quite powerful CPU which leads to the computer making fan noise when it is usually silent.

### Expected result

I don't expect it to be using nearly 10% of my quite powerful CPU while not doing anything.

### Actual result

It is using nearly 10% of my quite powerful CPU while doing nothing.

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12700
Physical Memory: 47.65GB (29.66GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1400.505.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.10.0_x64__cw5n1h2txyewy

**Comment by HO-COOH** [comment] 2024-06-10 17:37
Please, this needs to be addressed. As a laptop user, it eats up one CPU core and will make the CPU boost to a very high clock because the CPU thinks its a single-threaded load, destroying battery life and makes it hot as a pan.

**Comment by dkbennett** [comment] 2024-06-17 20:26
Can you show a task manager breakdown of the CPU and memory usage?  Is this Dev Home or the CoreWidgetProvider, or Project Ironsides?

**Comment by krschau** [comment] 2024-06-17 21:29
@eggbean Please see dkbennett's [question](https://github.com/microsoft/devhome/issues/3183#issuecomment-2174362490) above. If it's the widgets, it's already tracked by #1398. If it's something else, we'll need to update the issue to be more specific.

**Comment by krschau** [comment] 2024-06-19 13:39
Duplicate of #716

**Closed by krschau** 2024-06-19 13:39 UTC
Labels: Issue-Bug, Needs-Author-Feedback
