### ISSUE TITLE
Add widgets window has duplicated Core panel (GPU, CPU, SSH, Memory, Network)

### ISSUE THREAD

**Issue by luislhg** [microsoft/devhome#1187] opened 2023-06-21 19:15 UTC
### Dev Home version

0.200.170.0

### Windows build number

10.0.22621.1848

### Steps to reproduce the bug

Open DevHome, Dashboard, + Add widget, and they will be duplicated.

### Expected result

A single section of widgets and not duplicated ones

### Actual result

![image](https://github.com/microsoft/devhome/assets/16278387/f7135899-f52c-4865-8479-1f87485d6736)

**Comment by krschau** [comment] 2023-06-21 22:02
@luislhg I'm assuming you had a previous version and then after updating, you started seeing this? It's interesting that you're seeing a second widget provider rather than the original just being updated. If you don't mind, I'd love to ask you for a couple things:

If you run `Get-AppxPackage *devhome*` in powershell, what does it produce?
It would also be helpful to see some logs. I'll copy/paste instructions for that in a separate comment because they're a little long.

**Comment by krschau** [comment] 2023-06-21 22:15
@luislhg Actually, before logs, I was looking at the other issue you opened. I think this is happening because you actually have two copies of Dev Home installed -- one from the store, and one from building and running in Visual Studio. We just today checked in #1184, which will differentiate the two widget providers. Instead of two "Core"s, you'll see "Core (Preview)" and "Core (Dev)". Additionally, we're going to work on making it so when you disable an extension, the widgets from that extension won't be shown. That will solve this issue for the case when you might have a store version and a locally built version of the Dev Home GitHub Extension -- you can just disable one.

However, the core widgets aren't an extension, so you won't be able to disable them the same way. I think what we need to do here is for the core widgets specifically, only enable the provider that matches the version of the app you're running.

If you're building a local copy anyway, besides pulling in the PR above, you can also play around with [IsIncludedWidgetProvider()](https://github.com/microsoft/devhome/blob/4cdb57c75fed33b5d5fb94b63a7c64eb0f795a6c/tools/Dashboard/DevHome.Dashboard/Helpers/WidgetHelpers.cs#LL69C24-L69C48) to only enable the widget providers you want.

**Comment by luislhg** [comment] 2023-06-21 22:17
@krschau I don't remember if I had this before updating, the previous version crashed all the time for me, but indeed I get three versions when running your powershell command.
One from my old dev installed, one from the previous version installed from store and the latest one updated from store.

`Name              : Microsoft.Windows.DevHome.Dev
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 0.0.0.0
PackageFullName   : Microsoft.Windows.DevHome.Dev_0.0.0.0_x64__8wekyb3d8bbwe
InstallLocation   :
IsFramework       : False
PackageFamilyName : Microsoft.Windows.DevHome.Dev_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : True
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.32530.0_x64__8wekyb3d8bbwe,
                    Microsoft.WindowsAppRuntime.1.3_3000.882.2207.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : None
Status            : Ok

Name              : Microsoft.Windows.DevHomeGitHubExtension
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 0.200.165.0
PackageFullName   : Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program
                    Files\WindowsApps\Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.WindowsAppRuntime.1.3_3000.882.2207.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

Name              : Microsoft.Windows.DevHome
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 0.200.170.0
PackageFullName   : Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.Windows.DevHome_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.32530.0_x64__8wekyb3d8bbwe,
                    Microsoft.WindowsAppRuntime.1.3_3000.882.2207.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok`

**Comment by krschau** [comment] 2023-06-21 22:45
@luislhg This is what I suspected -- you have two Dev Homes (Microsoft.Windows.DevHome is from the store, and Microsoft.Windows.DevHome.Dev is the one you built) and one GitHub Extension from the store (Microsoft.Windows.DevHomeGitHubExtension).

We each last commented around the same time so I'm not sure you saw what I said above about what I think is happening. From widgets' point of view, everything is working as designed (you technically *do* have two different versions of the Dev Home Core widget provider installed). But from Dev Home's point of view, we should only display the widget provider that came from the version of Dev Home that is currently running.

**Comment by luislhg** [comment] 2023-06-22 00:45
@krschau  I think you are right. I also had this widget issue when using the native Windows Widgets from the TaskBar. It shows me all widgets duplicated and consumes a bunch of resources I just disabled the entire widget feature from my OS/Taskbar.

**Comment by luislhg** [comment] 2023-06-22 00:48
I pulled latest changes and this is what I have now, a "Core" section and a "ms-resource:WidgetDis" section
![image](https://github.com/microsoft/devhome/assets/16278387/307152e1-5e91-4a9b-b008-c64835335b27)

**Comment by EricJohnson327** [comment] 2023-06-22 01:33
This is on me :(  There was feedback to change the resource name and I forgot to update this in the manifest:
DisplayName="ms-resource:WidgetsDisplayNameDev

It should be WidgetProviderDisplayNameDev.  I can fix this later tonight.

**Closed** 2023-06-26 22:52 UTC
Labels: Issue-Bug, Area-Dashboard
