### ISSUE TITLE
Excessive CPU usage while program's idle or closed

### ISSUE THREAD

**Issue by cal4** [microsoft/devhome#3257] opened 2024-06-19 04:10 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3737

### Other software

OS Build Version: 10.0.22631.3737.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Open Dev Home

### Expected result

Dev Home opens, CPU usage increases then is close to 0%

### Actual result

Dev Home opens, CPU usage increases and then hovers around 5-10% even if closed

### Included System Information

CPU: AMD Ryzen 5 5600X 6-Core Processor             
Physical Memory: 31.93GB (5.73GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.20.0_x64__cw5n1h2txyewy

**Comment by cal4** [comment] 2024-06-19 04:13
Killing the task via Task Manager solves the background usage problem, but obviously a workaround

**Comment by krschau** [comment] 2024-06-19 13:39
Duplicate of #716 (but I expect the work currently being tracked by #1335 wil help or fix)

**Closed by krschau** 2024-06-19 13:39 UTC
Labels: Issue-Bug, Needs-Triage
