### ISSUE TITLE
Dev Home crashes after clicking on Settings>Account

### ISSUE THREAD

**Issue by akpabiojnr01** [microsoft/devhome#2066] opened 2023-12-18 12:57 UTC
### Dev Home version

0.801.344.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

N/B: I wasn't signed(Logged) in.
Go to Settings>Account

### Expected result

To load the menu

### Actual result

Once I clicked on "account", the "account" option became grayed out, and after that, the Dev home app crashed.

### Included System Information

CPU: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
Physical Memory: 11.79GB (6.7GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.801.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.800.344.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment] 2023-12-22 11:04
Duplicate of #1639, #1634.

**Comment by simonwoodhead** [comment] 2023-12-22 11:49
@skanda890 Was there a solution? I started following the other issues but couldn't find one. If not, here are the details from my system which has the same error.

**Dev Home Version**
0.801.344.0

**Windows build number**
10.0.22631.0

**Included Extensions Information**

| Name  | Id | Version | Source |
|-|-|-|-|
| Dev Home (Preview) | Microsoft.DevHome | 0.801.344.0 | winget |
| Dev Home GitHub Extension (Preview) | Microsoft.Windows.DevHomeGitHubExtension_8wekyb3d8bbwe | 0.800.344.0 | |
| Dev Home Azure Extension (Preview) | Microsoft.Windows.DevHomeAzureExtension_8wekyb3d8bbwe | 0.300.344.0 | |

**Additional Details**

Same experience as reported above. The crash does not happen if you disable the github extension (but then of course you cannot log in!). Same error with the Azure extension.

[DevHome_TempState.zip](https://github.com/microsoft/devhome/files/13752011/DevHome_TempState.zip)

[DevHomeAzureExtension_TempState.zip](https://github.com/microsoft/devhome/files/13752016/DevHomeAzureExtension_TempState.zip)

[DevHomeGitHubExtension_TempState.zip](https://github.com/microsoft/devhome/files/13752032/DevHomeGitHubExtension_TempState.zip)

**Comment by skanda890** [comment] 2023-12-27 03:38
@simonwoodhead, I actually don't know. It just got fixed after the next build.

**Comment by skanda890** [comment] 2023-12-27 03:40
Probably check #1634

**Comment by pfeerick** [comment] 2023-12-31 04:34
Clean install of Windows 11 23H2 (22631.2861), just installed DevHome to try it out (from the Store). I only installed the GitHub extension, as I don't use Azure. When I go Settings -> Accounts, as the OP reported, the account option greys out, the app freezes and then crashes. The same happens if I go Machine configuration -> Clone repositories  and then select "Account". 

[DevHomeTempState.zip](https://github.com/microsoft/devhome/files/13800230/DevHomeTempState.zip)
[DevHomeGitHubExtensionTempState.zip](https://github.com/microsoft/devhome/files/13800231/DevHomeGitHubExtensionTempState.zip)

**Comment by skanda890** [comment] 2024-01-01 03:15
Yeah, something is up.

**Comment by skanda890** [comment] 2024-01-01 03:15
@simonwoodhead, I later realised that

**Comment by IAMGeeCee** [comment] 2024-01-05 09:10
I'm having the same issue. It crashes whenever I try to do anything related to GitHub at all for me, which almost renders it useless for me. My pc has a 4th gen i3, 8gb ddr3 and runs a modified version of windows 11 called AtlasOS 11, though I don't think that's the issue as I've never had problems with that kind of thing using Atlas before. (I also posted this on the duplicate thread)

**Closed** 2024-01-06 18:18 UTC
Labels: Issue-Bug, Area-Extensibility, Priority-1
