### ISSUE TITLE
[Environments ] Property fields in the environment cards do not update dynamically after an action is performed

### ISSUE THREAD

**Issue by bbonaby** [microsoft/devhome#2683] opened 2024-04-18 18:01 UTC
### Steps to reproduce the bug

This issue goes for all operations that could potentially change the properties of the environment. For example If you have a Hyper-V VM and you create a checkpoint in the menu flyout of the split button. The environment properties do not update to reflect this new information:

![image](https://github.com/microsoft/devhome/assets/105318831/2a17e2ad-f615-44c8-9c78-1e436e07309f)

### Actual result

Cards should update to reflect this new information.

**Comment by huzaifa-d** [comment] 2024-04-29 18:03
Duplicate as commented by the bot.

**Comment by krschau** [comment] 2024-05-01 16:38
@huzaifa-d If you close something as a duplicate, please use the proper trigger (either "Duplicate of #x" or "/dup x") so it is closed and tagged correctly.

**Comment by krschau** [comment] 2024-05-01 16:38
Duplicate of #2556

**Closed** 2024-05-01 16:39 UTC
Labels: Issue-Bug, Resolution-Duplicate, Priority-2, Area-Environments
