### ISSUE TITLE
Compatibility with Windows 10

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [microsoft/devhome#814] opened 2023-05-24 18:56 UTC
### Steps to reproduce the bug

According to the [product page](https://apps.microsoft.com/store/detail/dev-home-preview/9N8MHTPHNGVV), dev home is only available for windows 11. Please add compatibility for win 10 🙂🙏🏻

### Actual result

Can't install 😢

**Comment by Aaron-Junker** [comment] 2023-05-24 19:24
Duplicate of #683

**Comment by krschau** [comment] 2023-05-24 21:15
Duplicate of #683

**Closed by krschau** 2023-05-24 21:15 UTC
Labels: Issue-Bug, Needs-Triage
