### ISSUE TITLE
开发人员主页不能添加小组件 [Dev Home cannot add widgets]

### ISSUE THREAD

**Issue by 1508Li** [microsoft/devhome#1128] opened 2023-06-12 10:21 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22631.1835

### Other software

OS Build Version: 10.0.22631.1835.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

在开发人员主页中点小组件没有任何反应

### Expected result

能像你们宣传的那样使用小组件

### Actual result

根本使用不了

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
Physical Memory: 15.65GB (7.51GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-12 14:57
Bing Translate:

Dev Home cannot add widgets
In the Dev Home page, the widget does not respond
You can use widgets as you advertise
It doesn't work at all

**Comment by krschau** [comment] 2023-06-12 14:57
I think you're hitting an issue where you have an older version of the Windows Web Experience Host app and we should be prompting you to update from the store. Please try updating this and see if you still see this problem -- if you do, we'll reopen the issue.
https://apps.microsoft.com/store/detail/windows-web-experience-pack/9MSSGKG348SP

**Comment by krschau** [comment] 2023-06-12 14:57
Duplicate of #866

**Closed by krschau** 2023-06-12 14:57 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by 1508Li** [comment] 2023-06-13 06:12
Thank you! The issue has been perfectly solved！
