### ISSUE TITLE
no se guardan los elementos o widgets

### ISSUE THREAD

**Issue by johamja** [microsoft/devhome#947] opened 2023-05-30 06:10 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.amd64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

abrir la aplicacion

### Expected result

los elementos que tenia añadido 

### Actual result

ningún elemento

### Included System Information

CPU: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
Physical Memory: 7.83GB (2.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-30 19:22
Duplicate of #742

**Closed by krschau** 2023-05-30 19:22 UTC
Labels: Issue-Bug, Needs-Triage
