### ISSUE TITLE
Multiple GPUs in dashboard swapped

### ISSUE THREAD

**Issue by hutchx86** [microsoft/devhome#3652] opened 2024-08-20 21:54 UTC
### Dev Home version

0.1601.561.0

### Windows build number

10.0.26100.1586

### Other software

OS Build Version: 10.0.26100.1586.amd64fre.ge_release.240331-1435
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Open Dashboard and pin GPU widget

### Expected result

Intel iGPU showing activity, nVidia dGPU showing no activity.

### Actual result

On the dashboard GPU widget, my nvidia GPU is showing activity, while the intel iGPU is showing no activity. Task Manager reports the opposite. 

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12800H
Physical Memory: 31.67GB (17.91GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.6.1.0_x64__g91dtg5srk15g (Widgets for UniGetUI (formerly WingetUI))
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.22801.0.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.4.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-08-21 13:44
Duplicate of #2800

**Closed by krschau** 2024-08-21 13:44 UTC
Labels: Issue-Bug, Needs-Triage
