### ISSUE TITLE
Add my local repositories to Dev home

### ISSUE THREAD

**Issue by HotCakeX** [microsoft/devhome#879] opened 2023-05-25 22:07 UTC
### Suggested new feature or improvement

I have many repositories already fully up to date, downloaded and cloned on my computer, I want to add them to Dev Home instead of cloning them again.

### Scenario

GitHub Desktop lets me add a local repository to it which is a local copy of my GitHub repository, I want to do the same in Dev Home.

**Comment by adrastogi** [comment] 2023-05-26 04:42
@HotCakeX this sounds like a duplicate of #780 (I saw your comment there, so I'll close this one). Thanks!

**Closed by adrastogi** 2023-05-26 04:42 UTC
Labels: Resolution-Duplicate, Issue-Feature
