### ISSUE TITLE
Windows Experience Pack

### ISSUE THREAD

**Issue by pndjrpauln** [microsoft/devhome#2484] opened 2024-03-28 22:27 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3374

### Other software

OS Build Version: 10.0.22631.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Dev Home does not work with WEP 521; desktop widgets not functioning.

### Expected result

WEP 521 is the commercially available version of this system component. Dev Home should work with it!

### Actual result

Dev Home widgets page complains that the wrong version of Windows Experience Pack is installed

### Included System Information

CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Physical Memory: 15.85GB (7.59GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_521.20060.465.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-03-29 16:42
Please check your Windows Insider settings -- whatever ring you're on is not providing the highest versions.

**Comment by krschau** [comment] 2024-03-29 18:58
Duplicate of #2382

**Closed by krschau** 2024-03-29 18:58 UTC
Labels: Issue-Bug, Needs-Triage
