### ISSUE TITLE
Cant import Repos or apps or any existing items

### ISSUE THREAD

**Issue by BlackV** [microsoft/devhome#1943] opened 2023-11-22 03:47 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Open Dev home, Point it at existing ALREADY cloned repository, you CANT

OK Reclone repository (in app) add existing install VScode or VScommunity. you CANT

OK

### Expected result

import an existing repo if it exists, 99% of people will already have repos on their machines, I should be able to point at an existing repo 

attach existing app if it exists, 99% of people have these apps ALREADY installed, why cant you see those ?

### Actual result

what actually happens you have to cloned the repo all over again

what actually happens you can add apps to your  machine config

### Included System Information

CPU: AMD Ryzen 7 5800X 8-Core Processor             
Physical Memory: 31.9GB (7.69GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.200.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-27 15:23
Duplicate of #702

**Closed by krschau** 2023-11-27 15:23 UTC
Labels: Issue-Bug, Needs-Triage
