### ISSUE TITLE
Export Configuration

### ISSUE THREAD

**Issue by harperse** [microsoft/devhome#811] opened 2023-05-24 18:29 UTC
### Suggested new feature or improvement

Allow already installed applications to be added to the configuration, or base my configuration on already installed applications

### Scenario

Allows a fuller experience when creating the configurations

**Comment by AmelBawa-msft** [comment] 2023-05-24 19:20
Likely duplicate of #721

**Comment by asklar** [comment] 2023-05-24 21:58
Duplicate of #721

**Closed by asklar** 2023-05-24 21:58 UTC
Labels: Issue-Feature, Area-Machine-Config, Needs-Triage
