### ISSUE TITLE
Adding repos separately clears clone path of other repos when cloning

### ISSUE THREAD

**Issue by MattVon** [microsoft/devhome#1827] opened 2023-11-04 09:12 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2506

### Other software

OS Build Version: 10.0.22631.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

 Go to Machine configuration > Clone repositories

**First part**
- Click "+ Add repository"
- Select a single repository to clone (in my testing, I am cloning from my "Account")
- Leave Path as default value
- Click "Add"

Once added you will be redirected back to the Clone repositories page, from here do the following

**Second part**
- Click the pencil icon against the repo to edit it
- Change the clone path to something different
- Click "Save"

Once changed, repeat the **First part** and at the point of clicking "Add" the repo is added to the clone repositories list and any previous repos which had an edited clone path, are all reset to the default value when they were saved.

### Expected result

Any previous repositories in the list to maintain their clone path without being reset to their default value

### Actual result

Any previous repositories in the list are reset to the default value, presumably the value that could have been set from when originally adding the repo.

### Included System Information

Physical Memory: 31.92GB (20.92GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by hamnarauf** [comment] 2023-11-04 10:34
This has been fixed in https://github.com/microsoft/devhome/pull/1766. Hopefully, this PR will be included in the next release and cloning into different locations won't be an issue.

**Comment by krschau** [comment] 2023-11-06 17:41
Duplicate of #1387

**Closed by krschau** 2023-11-06 17:41 UTC
Labels: Issue-Bug, Area-Machine-Config, Priority-2
