### ISSUE TITLE
Add already cloned repo's to dev home

### ISSUE THREAD

**Issue by Abelkrijgtalles** [microsoft/devhome#1426] opened 2023-08-19 21:21 UTC
### Suggested new feature or improvement

A way to add already cloned repo's to dev home, instead of deleting them and then cloning them through dev home.

### Scenario

Users who have cloned repo's before installing dev home would want to add the already cloned repo's.

**Comment by adrastogi** [comment] 2023-08-20 20:53
Possible dupe of #799

**Closed** 2023-08-20 20:53 UTC
Labels: Issue-Feature
