### ISSUE TITLE
Moving the widgets in the dashboard

### ISSUE THREAD

**Issue by aavdberg** [microsoft/devhome#885] opened 2023-05-26 06:27 UTC
### Suggested new feature or improvement

Would love to see that you can rearrange the widgets in the dashboard.

### Scenario

When I have added widgets in the dashboard I want to rearrange with, so customize my dashboard.

**Comment by krschau** [comment] 2023-05-30 16:27
Duplicate of #673

**Closed by krschau** 2023-05-30 16:27 UTC
Labels: Issue-Feature, Needs-Triage, Issue-External
