### ISSUE TITLE
devops

### ISSUE THREAD

**Issue by Eves101** [microsoft/devhome#2294] opened 2024-02-22 09:13 UTC
### Suggested new feature or improvement

it would be nice if there was a possibilty to connect with a microsoft dev account to my repositories in devops.... untill then this is useless

### Scenario

connect with repos in devops

**Comment by Aaron-Junker** [comment] 2024-02-22 10:58
You can download the Dev home Azure extension to access devops repos.

https://github.com/microsoft/DevHomeAzureExtension

**Comment by krschau** [comment] 2024-02-22 17:13
Duplicate of #521

**Closed by krschau** 2024-02-22 17:13 UTC
Labels: Issue-Feature, Needs-Triage
