### ISSUE TITLE
Let me add existing repositories

### ISSUE THREAD

**Issue by gkinsman** [microsoft/devhome#783] opened 2023-05-24 10:02 UTC
### Suggested new feature or improvement

I already have a lot of repositories on my machine, but this tool wants to re-clone them given a URL. I want to be able to add existing folders, and then have this tool detect the remotes etc. 

Ideally, I'd be able to add a directory (with optional sub-directories) of folders with git repo's and it would pick them all up

### Scenario

I have existing repositories. Make it easy to add them here.

**Comment by gkinsman** [comment] 2023-05-24 10:03
This is a duplicate of https://github.com/microsoft/devhome/issues/780 and https://github.com/microsoft/devhome/issues/779

**Comment by bstordrup** [comment] 2023-05-24 10:25
Not a duplicate of #779, but yes, a duplicate of #780

**Comment by gkinsman** [comment] 2023-05-24 10:32
> Not a duplicate of #779, but yes, a duplicate of #780

It feels like there's a higher level feature here, in which we'd be able to add folders of repo's instead of just repo's directly. My folder setup looks like this:

`/projects/personal/projectA`
`/projects/personal/projectB`
`/projects/work/projectC`

I'd love to be able to add my `projects` directory, and have all of the nested projects be added. There might need to be some configuration around how deep to search, or folders to exclude to prevent node_modules from being problematic, but the idea is there!

**Comment by bstordrup** [comment] 2023-05-24 10:35
Like searching a folder structure for the `.git` subfolders and importing the repositories with the origin upsteam.

**Comment by gkinsman** [comment] 2023-05-24 10:45
Yeah! The remotes could be auto detected from the repo so it just needs to detect the folders with some smarts.

**Comment by bstordrup** [comment] 2023-05-24 10:49
Any idea where the information about repositories are stored locally?

**Comment by gkinsman** [comment] 2023-05-24 12:04
Yep, remotes and tracked branches are in `.git/config`

**Comment by dhoehna** [comment] 2023-05-24 16:37
Thank you so much for filing feedback about the repo tool!

QQ.  If the repo tool did find local repos, what would you want it to do with that information?  Suggest to clone in the location of existing repos, move your existing repos to a new clone location, something else?

I'm not angry or making a challange, I'm just curious.

**Comment by bstordrup** [comment] 2023-05-24 18:56
@gkinsman, I was more thinking about where DevHome stores information about which repos have been cloned.

**Comment by gkinsman** [comment] 2023-05-24 22:21
> Thank you so much for filing feedback about the repo tool!
> 
> QQ. If the repo tool did find local repos, what would you want it to do with that information? Suggest to clone in the location of existing repos, move your existing repos to a new clone location, something else?
> 
> I'm not angry or making a challange, I'm just curious.

You're right to go high level still - it's worth asking what the ultimate goal of this tool is to define what features might fit and what wouldn't.

Today I use Fork (https://git-fork.com/) to manage my git repos, but maybe Dev Home could one day be a portal to open Fork - who knows! I like the idea of a central place where I can view everything on my machine.

**Comment by dhoehna** [comment] 2023-05-24 22:23
>  I like the idea of a central place where I can view everything on my machine.
Yes.  This right here, I think is the essence of all the issues "I want to see my already cloned repos."

**Comment by gkinsman** [comment] 2023-05-24 22:47
> @gkinsman, I was more thinking about where DevHome stores information about which repos have been cloned.

Ah righto sorry - yeah I have no idea about that - would assume it's some program data location as it's a windows store app 👍

**Comment by asklar** [comment] 2023-05-27 20:04
Duplicate of #702

**Closed by asklar** 2023-05-27 20:04 UTC
Labels: Issue-Feature, Needs-Triage, Area-Repo Management
