### ISSUE TITLE
Add Repositories instead of clone

### ISSUE THREAD

**Issue by artvabas** [microsoft/devhome#1723] opened 2023-10-18 18:03 UTC
### Suggested new feature or improvement

Now you can only clone Repositories, means it will download a Repositories from GitHub in a new selected empty folder.

But what if Repositories from GitHub is already cloned by, for example Visual Studio, how can I add an existing Repositories without cloning it again.

So therefore "Add existing local Repositories" would be a nice feature.

### Scenario

Already have Repositories cloned by other applications, like Visual Studio and/or Code. So they already exist on my hard drive. 

Now with Dev Home, the only option is to clone, means creating new folder so that the files form Repositories will copy into it again.
But its already on my hard drive.

That's why add existing cloned Repositories will be a great feature.

**Comment by krschau** [comment] 2023-10-18 21:10
Duplicate of #702

**Closed by krschau** 2023-10-18 21:10 UTC
Labels: Issue-Feature, Needs-Triage
