### ISSUE TITLE
Ability to re-order dashboard widgets

### ISSUE THREAD

**Issue by marty0678** [microsoft/devhome#735] opened 2023-05-23 17:29 UTC
### Suggested new feature or improvement

Would like to be able to re-order my dashboard widgets, like I can with the Windows Widget pane

### Scenario

To be able to train muscle memory and quickly glance at information in a way that makes sense to me.

**Comment by bricelam** [comment] 2023-05-23 18:55
Duplicate of #673

**Closed** 2023-05-23 18:56 UTC
Labels: Issue-Feature, Area-Dashboard, Needs-Triage
