### ISSUE TITLE
High CPU usage by Dev Home (CoreWidgetProvider.exe)

### ISSUE THREAD

**Issue by Jevil7452** [microsoft/devhome#819] opened 2023-05-24 19:57 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.25370.1

### Other software

OS Build Version: 10.0.25370.1.amd64fre.zn_release.230516-0802
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Set up widgets in Dev Home, then add them to Widgets board. This seems to happen after the widgets board crashes?

### Expected result

No high CPU usage for no reason

### Actual result

High CPU usage
![image](https://github.com/microsoft/devhome/assets/98893064/722c8b0e-d5ba-48cb-bd75-93fd94e408b0)

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical Memory: 19.77GB (8.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-24 21:20
This is likely due to #760, so I'm going to close this one as a dupe.

**Comment by krschau** [comment] 2023-05-24 21:21
Duplicate of #760

**Closed by krschau** 2023-05-24 21:21 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by rifkitech** [comment] 2023-05-25 08:16
**What?!**

![Screenshot (65)](https://github.com/microsoft/devhome/assets/112795137/f85a2d77-0748-47b9-b7d4-7e5d5cbfcda1)

Intel Celeron be like ;)

**Comment by Illutax** [comment] 2024-06-28 08:03
Also, why does it use 3GB of RAM?
![image](https://github.com/microsoft/devhome/assets/2649244/ca15635e-e3ba-4c8e-9bfc-8340efc44f4b)

**Comment by anyonecan** [comment] 2024-07-26 11:47
Dev Home (Preview) is #2 in CPU usage shown in Task Manager App history. And until now, I don't recall ever opening it, much less showing graphs as in #760.
