### ISSUE TITLE
Dev Home and GitHub extension icons rendering as too small within Microsoft Store

### ISSUE THREAD

**Issue by embender** [microsoft/devhome#1019] opened 2023-06-01 19:23 UTC
### Steps to reproduce the bug

Go to Microsoft Store and search Dev Home, and you will notice these two icons when in the library of apps look much smaller than icons around it, making it hard to see the nice icon details and having the applications look out of place.

### Actual result

Icons would fill the box within Microsoft Store, there is a large gray border the takes up the majority of the icon space as opposed to the icon itself
<img width="813" alt="MicrosoftTeams-image" src="https://github.com/microsoft/devhome/assets/44589070/10a8dffd-c6eb-4776-a467-d9bbf70ca000">

**Comment by embender** [comment] 2023-06-01 19:23
@EricJohnson327 for visibility

**Comment by cinnamon-msft** [comment] 2023-06-05 16:43
Our icon is pulled from the app manifest, which follows what most other Microsoft apps do. I'm going to close this as by design.
![image](https://github.com/microsoft/devhome/assets/48369326/97f3a8c0-d64c-43e6-a858-a83d6431d63c)

**Closed by cinnamon-msft** 2023-06-05 16:43 UTC
Labels: Issue-Bug, Priority-2, Area-Core
