### ISSUE TITLE
GitHub login button doesn't work

### ISSUE THREAD

**Issue by Drkongy** [microsoft/devhome#1623] opened 2023-09-29 21:53 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

downloaded the extension, then my program froze, but didn't give me a not responding error.
Ended the task in task manager,
Opened the app again, and pressed the login to GitHub button.
 

### Expected result

A way for me to login to github

### Actual result

Nothing happend

### Included System Information

Physical Memory: 15.73GB (3.37GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by vineeththomasalex** [comment] 2023-10-16 21:05
This is either a dupe of #1634 or #1544. Closing as duplicate. Asking for logs to additional info on these bugs.

**Closed by vineeththomasalex** 2023-10-16 21:05 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Extensibility, Needs-Triage, Severity-Crash
