### ISSUE TITLE
Add widget buttons not working

### ISSUE THREAD

**Issue by LeMonsalve** [microsoft/devhome#928] opened 2023-05-29 03:07 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22623.1245

### Other software

OS Build Version: 10.0.22623.1245.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I just installed devhome, I connected my Github account and when I press any add widget button it just doesn't do anything, in fact I pressed it so many times that the app closed

### Expected result

A new screen is expected to appear with the available widgets

### Actual result

I press any add widget button it just doesn't do anything, in fact I pressed it so many times that the app closed

### Included System Information

CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Physical Memory: 15.84GB (8.9GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-30 19:39
Duplicate of #866

**Closed by krschau** 2023-05-30 19:39 UTC
Labels: Issue-Bug, Area-Dashboard, Needs-Triage
