### ISSUE TITLE
Dev Home launch on a fresh machine is taking a long time when the stub hydrates the app

### ISSUE THREAD

**Issue by kanismohammed** [microsoft/devhome#3675] opened 2024-08-21 22:24 UTC
### Steps to reproduce the bug

Click on the Dev Home Icon on a fresh machine.

### Expected result

Dev Home installs and is ready to use in a few seconds.

### Actual result

Dev Home install takes a long time.

**Comment by krschau** [comment] 2024-09-04 23:10
Duplicate of #1682

**Closed by krschau** 2024-09-04 23:10 UTC
Labels: Issue-Bug, Priority-2, Area-Core
