### ISSUE TITLE
issue in accounts page

### ISSUE THREAD

**Issue by Namefi** [microsoft/devhome#1997] opened 2023-12-03 09:58 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2506

### Steps to reproduce the bug

went to settings>account

### Expected result

to show me the accounts page

### Actual result

the app crashed

**Comment by vineeththomasalex** [comment] 2023-12-19 00:59
Without logs, marking this as duplicate of #1945 based on the behavior.

**Closed by vineeththomasalex** 2023-12-19 00:59 UTC
Labels: Issue-Bug, Resolution-Duplicate, Needs-Author-Feedback, Area-Account-Sign-In
