### ISSUE TITLE
add 2nd github account

### ISSUE THREAD

**Issue by ATLuis** [microsoft/devhome#1054] opened 2023-06-04 20:43 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

add 1st gtthub account.
try to add a 2nd github account

### Expected result

be able to have N github accounts

### Actual result

the 2nd login fails

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 15.77GB (2.94GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-05 15:05
Duplicate of #918

**Closed by krschau** 2023-06-05 15:05 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Account-Sign-In
