### ISSUE TITLE
The close X icon on "Add a widget" does nothing.

### ISSUE THREAD

**Issue by CharlesStover** [microsoft/devhome#1828] opened 2023-11-06 00:24 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Click add a widget. Try to click the close icon (X).

### Expected result

The modal should close.

### Actual result

Nothing.

### Included System Information

Physical Memory: 63.76GB (49.29GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by DavideDunne** [comment] 2023-11-06 03:57
The button seems to work only when the program window is on full screen.

**Comment by krschau** [comment] 2023-11-06 17:39
Duplicate of #537

**Closed by krschau** 2023-11-06 17:39 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
