### ISSUE TITLE
File Explorer Integration no errors on failure.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#3609] opened 2024-08-15 17:46 UTC
### Steps to reproduce the bug

Enable File Explorer Integration.
Go to Windows customization > File Explorer.
Click "Add Folder"
Add a repo that has dubious ownership.
Click the drop down.
Click "git"

### Expected result

A content dialog, or an error message, telling me why I can't attach the git extension to the repo.

### Actual result

The combo box stays on "Unassigned" and does not show an error message.

**Comment by DefaultRyan** [comment] 2024-08-16 00:19
Thanks! @ssparach has already been looking into this. Was this the result of adding a WSL repo?

**Comment by DefaultRyan** [comment] 2024-08-16 00:20
@dhoehna is this a duplicate of #3610 ?

**Comment by adrastogi** [comment] 2024-08-16 16:47
I think I tripped over this by picking a folder that didn't have a git repository in it (I picked the parent folder by mistake). The logs tipped me off, but having the UX tell me this would be nice. 

```
[2024/08/16 09:37:22.832 INF] (SourceControlIntegration) Validating source control extension with arguments: extensionCLSID = A65E46FF-F979-480d-A379-1FDA3EB5F7C5, rootPath = D:\src
[2024/08/16 09:37:23.795 ERR] (SourceControlIntegration) Could not open local repository.
[2024/08/16 09:37:23.795 ERR] (SourceControlIntegration) Unable to get repository at the given root path
[2024/08/16 09:37:23.797 ERR] (FileExplorerViewModel) Failed to validate source control extension
```

**Closed** 2024-09-05 18:32 UTC
Labels: Issue-Bug, In-PR, Area-FileExplorerIntegration
