### ISSUE TITLE
Dev Home cannot be uninstalled via GUI

### ISSUE THREAD

**Issue by hayos** [microsoft/devhome#3969] opened 2024-11-04 16:40 UTC
### Suggested new feature or improvement

Allow to uninstall Dev Home, preferably via 'Add/Remove Programs'.

As it is somehow no more possible to create local Environments, I wanted to uninstall/re-install Dev Home via Microsoft Store, Add/Remove programs or Dev Home (Preview) itself. In Dev Home itself it should be via Extensions -> 'Dev Home (Preview)' -> ... -> Uninstall.

Currently neither works. My version 0.1801.640.0.

If you have a look at the comments in Microsoft Store, you will soon realize that many (non-developer) users do not agree with the fact that they cannot uninstall Dev Home. (If they really have it installed or just see the installer application stays being their secret). The overall rating is at 1.4 stars, which is somwhat fourth floor subterrane.

This is a follow-up to the issue https://github.com/microsoft/devhome/issues/1615 which had been closed without any action.

### Scenario

**Scenario B**
As a knowledgeable developer I have installed the 'Dev Home (Preview)', but now it is of no use anymore and I'd like to uninstall it. 

**Scenario A**
As a simple user I want to uninstall the 'Dev Home (Preview)' app, which is actually just an installer to install the real app. But as I am a simple user, I do not know that and think this is bloatware that uses up my system resources.

**Scenario C**
As a simple user I accidentally installed the full 'Dev Home' software. For me it is just bloatware, I want to uninstall it.

**Comment by hayos** [comment] 2024-11-04 17:03
To give a pictorial insight into what my fellow German countrymen think about the fact that Dev Home isn't uninstallable, I provide some of the comments which have been given in the Microsoft Store. I translated them to English, to easen your reading. 

Disclaimer: The following ain't my wording.

- ******** my computer
  *
  my computer. Do you understand " ********
  my computer"? If not, tell my, I'll make you understand.
  ******** MY COMPUTER !!! ******** |
- Installs itself without being asked ...
  *
  Although the installation of apps has been deactivated - Microsoft is cheeky and bugs the computer without being asked. 
  Although this app was never part of the delivered OS. Would be a case for the EU Commission ... have been bribed by MS.
- ***** YOURSELF YOU **********
  *
  KEEP YOUR CRAPWARE IN YOUR ***** YOU INCOMPETENT USELESS SUBHUMANS !!! 
  THIS ******** IS AN ABSOLUTE IMPERTINENCE !!!
- Life Changing Experience
  \*****
  This app has changed my life. I showed it to my neighbor and his life was changed too. Together we showed it to all our neighbors and all our lives were changed.
  Since then we are a great community and share much more with each other.

I reckon the last one contains a bit of irony,

If the intention of the Dev Home software is to achieve the lowest possible rating in the Microsoft Store and to provoke a maximum of foul-mouthed comments, then the goal has been achieved exceptionally well.
I originally thought it was about working together to create software that helps people. Developers in this case.

**Don't be so ignorant towards the users!**

**Comment by krschau** [comment] 2024-11-05 19:56
Dev Home can't be uninstalled because it is a system component of Windows, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703
We are working on implementing GPO policies that will allow you to disable Dev Home. (#3727)

I understand the above was not your wording but I don't believe it is inline with our community guidelines, and as such, I'm closing this issue. It would be a duplicate of #1615 in any case.

**Closed by krschau** 2024-11-05 19:56 UTC
Labels: Issue-Feature, Needs-Triage
