### ISSUE TITLE
Account page is not showing up correctly

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3273] opened 2024-06-20 22:11 UTC
### Steps to reproduce the bug

Go to settings -> Accounts

### Expected result

![image](https://github.com/microsoft/devhome/assets/65691598/c8fa6f52-6733-41c7-8f37-1c52679aec14)

### Actual result

![image](https://github.com/microsoft/devhome/assets/65691598/866420bb-ec35-48a9-8c07-e21374ebfbd2)

**Comment by krschau** [comment] 2024-06-21 13:12
Duplicate of #3142

Please make sure you're on the latest version of Dev Home, this bug was fixed in the last release.

**Closed** 2024-06-21 13:12 UTC
Labels: Issue-Bug
