### ISSUE TITLE
Problem with adding additional GitHub account

### ISSUE THREAD

**Issue by crac2003** [microsoft/devhome#917] opened 2023-05-28 11:42 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Sign in with first account
2. setup single repo
3. try to add a new account
4. sign in button does nothing without any feedback

### Expected result

it should open a browser or provide a link which can be used to sign in with a new accoutn

### Actual result

application does nothing (no feedback)

### Included System Information

CPU: AMD Ryzen 7 3800XT 8-Core Processor            
Physical Memory: 127.92GB (105.89GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-30 19:36
Dupe of #918?

**Comment by cinnamon-msft** [comment] 2023-05-30 19:56
Yep :) /dup of #918

**Closed** 2023-05-30 19:57 UTC
Labels: Issue-Bug, Needs-Triage, Area-DevIdSignIn
