### ISSUE TITLE
Theme Switch

### ISSUE THREAD

**Issue by AchchuthaRengan** [microsoft/devhome#765] opened 2023-05-24 06:54 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1555

### Other software

OS Build Version: 10.0.22621.1555.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I switched to White Theme which my System theme is on dark mode, the theme is not properly applied to all pages. 

### Expected result

It must be applied to backgrounds to all tabs and cards

### Actual result

Not applied on background which is still black and changed only some cards on a tab

### Included System Information

CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
Physical Memory: 7.88GB (2.1GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-24 20:11
Duplicate of #511

**Closed** 2023-05-24 20:12 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Style
