### ISSUE TITLE
Dashboard was blank

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1656] opened 2023-10-05 08:11 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Open the app multiple times.

### Expected result

It should show the widgets properly.

### Actual result

Every widget will be 0.00.

### Included System Information

Physical Memory: 11.89GB (3.44GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-04-01 13:47
Duplicate of #1248

**Closed by krschau** 2024-04-01 13:47 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
