### ISSUE TITLE
Can't apply a configuration file to a DevBox.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/devhome#2875] opened 2024-05-10 19:20 UTC
### Steps to reproduce the bug

1. Have an already made DevBox.
2. Go to Machine Configuration -> Set up an environment
3. Select the DevBox
4. Add any options (I chose Powershell)
5. Start setting up.

### Expected result

No errors.

### Actual result

An error "We couldn't apply the configuration file onto asdfg"

**Comment by dhoehna** [comment] 2024-05-10 19:23
[Logs.zip](https://github.com/microsoft/devhome/files/15279149/Logs.zip)

**Comment by kanismohammed** [comment] 2024-05-10 20:59
duplicate of this issue https://github.com/microsoft/devhome/issues/2840

**Closed by kanismohammed** 2024-05-10 20:59 UTC
Labels: Issue-Bug, Area-Environments

**Comment by krschau** [comment] 2024-05-10 21:20
Duplicate of #2840
