### ISSUE TITLE
Create winget installation script

### ISSUE THREAD

**Issue by lyzzandro** [microsoft/devhome#1039] opened 2023-06-03 01:27 UTC
Edited: Translated used Bing Translator by @denelon 

Original Title:
Criar script de instalação do winget

### Suggested new feature or improvement

I'd like to manage my apps and their list for installation

Original:
Gostaria de gerenciar meus aplicativos e sua lista para instalação

### Scenario

I would like to manage my applications and their list for installation, just by clicking and adding them in a script, and then when I format my computer, use the script to quickly and easily install all of them

Original:
Gostaria de gerenciar meus aplicativos e sua lista para instalação, apenas clicando e adicionando eles em um script, para depois quando eu formatar o meu computador, usar o script para instalar de forma rápida e fácil todos eles

**Comment by AmelBawa-msft** [comment] 2023-06-05 13:35
Possibly related to this #721 ?

**Comment by denelon** [comment] 2023-06-05 20:18
I think this is more like supporting `winget import` and possibly `winget export`. Related to:
* #1067

**Comment by denelon** [comment] 2024-01-03 18:09
Duplicate of #795

**Closed** 2024-01-03 18:09 UTC
Labels: Issue-Feature, Area-Machine-Config, Area-Machine-Config-Install, Area-Machine-Config-DSC
