### ISSUE TITLE
Documentation missing - How to prevent Dev Home from Auto Installing

### ISSUE THREAD

**Issue by babywannabeastar** [microsoft/devhome#3879] opened 2024-09-18 12:27 UTC
Hello,

After a recent update I have discovered that Dev Home is auto installing in our environment. Is there a way to prevent this app from automatically installing (or any un-consented microsoft product)  via GPO? 

Not a dupe looking for a gpo related method to prevent this from happening in the future.

winver 23H2 OS Build 22631.4037

Thank You

**Comment by krschau** [comment] 2024-09-18 14:07
Duplicate of #1615
Please see this comment in particular: https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703

**Closed by krschau** 2024-09-18 14:07 UTC
Labels: Issue-Docs, Needs-Triage
