### ISSUE TITLE
Application missing means of disabling or uninstalling

### ISSUE THREAD

**Issue by dstack4273** [microsoft/devhome#3925] opened 2024-10-04 16:25 UTC
### Steps to reproduce the bug

View Add or remove programs, there is no ability to remove or disable Dev Home. All non-essential software should have those features, and since this doesn't - I'm reporting this as a bug rather than a feature request. 

That goes doubly so for preview channel software that is able to influence system performance so dramatically. The application can be removed via PowerShell, that should be extended to the Settings app. 

### Expected result

When viewing the system components list I should be able to control this software to include disabling or uninstalling.

### Actual result

I am only provided the ability to terminate, repair, or reset.

**Comment by krschau** [comment] 2024-10-04 20:44
Duplicate of #1615, see specifically https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703

**Closed by krschau** 2024-10-04 20:44 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by dstack4273** [comment] 2024-10-14 03:57
> Duplicate of [#1615](https://github.com/microsoft/devhome/issues/1615), see specifically [#1615 (comment)](https://github.com/microsoft/devhome/issues/1615#issuecomment-1856931703)

Sorry @krschau  - that issue has been open for nearly a year and doesn't seem have any response or resolution from Microsoft. Can anyone confirm that this is actually being resolved? By my count two semesters have passed since that ticket and nothign?
