### ISSUE TITLE
错误的GPU占用

### ISSUE THREAD

**Issue by PetYin** [microsoft/devhome#1826] opened 2023-11-04 01:31 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

在仪表板放置GPU组件。

### Expected result

应当正确显示两个GPU各自的占用。

### Actual result

错误的占用显示到了小组件上。独立显卡的占用被核显显示了。

### Included System Information

Physical Memory: 63.71GB (46.24GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-07 16:26
Bing Translate:

Wrong GPU occupancy #1826

Steps to reproduce the bug
Place the GPU component on the dashboard.

Expected result
The respective occupancy of both GPUs should be displayed correctly.

Actual result
The wrong occupancy is displayed on the widget. The occupancy of the discrete graphics card is shown by the nuclear display.

**Comment by krschau** [comment] 2023-11-07 16:27
Duplicate of #821

**Closed by krschau** 2023-11-07 16:27 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
