### ISSUE TITLE
Application hangs while adding a repository

### ISSUE THREAD

**Issue by Devesh192** [microsoft/devhome#2589] opened 2024-04-11 15:39 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631

### Steps to reproduce the bug

1. Open machine configuration tab
2. Click on set up local machine
3. Click on Add Repository

https://github.com/microsoft/devhome/assets/63630655/c16641b8-0ec3-4975-a281-29958ce2f3b0

### Actual result

It hangs down the whole application and after some time closes the whole application.

**Comment by krschau** [comment] 2024-04-11 15:43
Duplicate of #2485

**Closed by krschau** 2024-04-11 15:43 UTC
Labels: Issue-Bug, Needs-Triage
