### ISSUE TITLE
Widgets 

### ISSUE THREAD

**Issue by aoshea83** [microsoft/devhome#2049] opened 2023-12-14 01:02 UTC
### Dev Home version

0.801.344.0

### Windows build number

10.0.22635.2850

### Other software

OS Build Version: 10.0.22635.2850.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

In minimised mode, once 'widget' is selected, the widget pop-up window can not be closed unless a widget is selected or the entire window is maximised.

### Expected result

The pop-up window to close

### Actual result

the 'X' close window does nothing

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i5-1340P
Physical Memory: 7.7GB (0.49GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.801.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.800.344.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.300.344.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-12-14 16:33
Duplicate of #537

**Closed by krschau** 2023-12-14 16:33 UTC
Labels: Issue-Bug, Needs-Triage
