### ISSUE TITLE
Allow custom titles for widgets

### ISSUE THREAD

**Issue by shakersMSFT** [microsoft/devhome#1146] opened 2023-06-14 17:41 UTC
### Suggested new feature or improvement

I have multiple widgets for the same repo, but different issue queries I want to track. When I create multiple Issues widgets, they are all titled the same and its not immediately obvious to me what issue query I am tracking. It would be great if there was a way for me to rename or add a custom subtitle to widgets so I can identify the differences at a glance.

### Scenario

I am tracking multiple issues queries and I would like to know at a glance what the custom query each issue widget is tracking. Right now, I see the same widget type and repo but each widget is tracking something different. I would like to see, at a glance, the difference between each widget without having to go into each widget. 

<img width="469" alt="image" src="https://github.com/microsoft/devhome/assets/45182130/7a52584e-6710-47fb-a2e9-d145c4d71e27">

**Comment by krschau** [comment] 2023-06-14 18:45
@shakersMSFT I'm not sure if you're wanting to customize "Issues" or "microsoft/devhome" from your screenshots. The latter is a dupe of https://github.com/microsoft/devhomegithubextension/issues/139. The former is a much bigger deal, and would take us further away from our widgets working in the Windows Widget Board, so I'm less keen.

**Comment by cinnamon-msft** [comment] 2023-06-19 17:38
I'm betting this is a /dup of #139 :)

**Closed by cinnamon-msft** 2023-06-19 17:38 UTC
Labels: Issue-Feature, Area-Dashboard, Area-Widgets, Needs-Author-Feedback, Needs-Triage
