### ISSUE TITLE
Dashboard Settings Reset in Desktop Tool

### ISSUE THREAD

**Issue by thisguymartin** [microsoft/devhome#1342] opened 2023-07-31 01:35 UTC
### Dev Home version

0.301.198.0

### Windows build number

10.0.22621.1992

### Other software

OS Build Version: 10.0.22621.1992.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

 The desktop tool is facing an issue where dashboard settings are being reset, causing all previously pinned items to be lost. This problem is frustrating for the user, as they expect the tool to retain their dashboard settings as they had set them up previously. Consequently, the user is required to manually repin all the items again, which is a tedious and time-consuming process, leading to annoyance and dissatisfaction.

### Expected result

The desktop tool should retain and save the user's dashboard settings consistently. When the user reopens the tool, all the dashboards and their pinned items should remain in place as they were set up during the last usage.

### Actual result

Just turn off computer and log back in or re open app.

### Included System Information

Physical Memory: 31.94GB (20.44GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-07-31 14:37
@thisguymartin Please check if you have an update available in the store for the "Windows Web Experience Pack." There is a fix for this bug in version 523.17300.0.0. If you're on version 423, I'm not sure if there's a fix out yet but please take any updates available for that listing.

**Comment by krschau** [comment] 2023-07-31 14:37
Duplicate of #742

**Closed by krschau** 2023-07-31 14:37 UTC
Labels: Issue-Bug, Needs-Triage
