### ISSUE TITLE
Project Ironsides Hotkey is enabled on startup

### ISSUE THREAD

**Issue by derekwilling** [microsoft/devhome#3304] opened 2024-06-25 22:41 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3737

### Other software

OS Build Version: 10.0.22631.3737.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Do nothing and do not install or enable Project Ironsides.

### Expected result

The application should not arbitrarily add startup applications unless it asks the user for permission.

### Actual result

A new startup entry "Hotkey for Dev Home Project Ironsides" was added and enabled.

### Included System Information

CPU: AMD Ryzen 9 5950X 16-Core Processor            
Physical Memory: 63.92GB (50.43GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.20.0_x64__cw5n1h2txyewy

-----

Just an aside to this bug report. Why am I getting DevHome installed? Why is this application unable to be uninstalled from Windows 11?

**Comment by jaholme** [comment] 2024-06-27 00:28
This is by by-design. As we evolve Dev Home we may need to have startup tasks registered to run.

**Comment by andreww-msft** [comment] 2024-07-01 22:05
@derekwilling - thanks for your feedback. I agree that enabling a startup task without asking seems wrong. We do aim to tie enabling the startup task with enabling the feature in Dev Home - that's part of the evolving story that jaholme mentioned - so this will get better shortly. Note that right now, the first thing the startup task does is to check whether the user has enabled the feature, and if not it immediately exits.

I will keep this item open for now, assigned to me for tracking as we evolve the behavior.

**Comment by timkur** [comment] 2024-08-08 21:29
Dupe of #3465

**Closed by timkur** 2024-08-08 21:29 UTC
Labels: Issue-Bug, Priority-2, Area-PI

**Comment by ErroneousFatality** [comment] 2024-08-15 13:03
> Dupe of #3465

The referenced issue is not a duplicate of this issue. This issue was closed incorrectly.
