### ISSUE TITLE
Not clear how to connect to DevOps

### ISSUE THREAD

**Issue by MikeBarker-MSFT** [microsoft/devhome#1830] opened 2023-11-06 11:57 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

In the description on MS Store this app claims it works with Azure DevOps. Yet, when I try to add an account, there is no extension for DevOps available.

Repro:
1. Goto Introducing Dev Home
2. Connect accounts
3. Add account
4. Find Extensions

### Expected result

Expected: Extension available for DevOps

### Actual result

Actual: Only an extension for Github

### Included System Information

Physical Memory: 31.85GB (15.06GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-06 17:43
Duplicate of #521

**Closed by krschau** 2023-11-06 17:43 UTC
Labels: Issue-Bug
