### ISSUE TITLE
Dev Home crashes after clicking on account 

### ISSUE THREAD

**Issue by ianyyu** [microsoft/devhome#1671] opened 2023-10-09 17:39 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2283

### Other software

OS Build Version: 10.0.22621.2283.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Installed the GitHub extension, clicking on an account related things will crashes the app 

### Actual result

Here is a link for the [video](https://teams.microsoft.com/l/message/19:meeting_NzVmNWRkYmUtZDJlZi00OTEyLTgyNmUtYzRjY2U3MWIzNTgx@thread.v2/1696872943584?context=%7B%22contextType%22%3A%22chat%22%7D)

### Included System Information

Physical Memory: 63.95GB (52.21GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe

**Comment by ianyyu** [comment] 2023-10-09 17:39
@dhoehna

**Comment by krschau** [comment] 2023-10-11 14:53
I don't have access to the video, I hope dhoehna does.

**Comment by skanda890** [comment] 2023-10-12 10:33
Is it related to #1674 , #1657 , #1639 , #1638 or #1651

**Comment by vineeththomasalex** [comment] 2023-10-13 20:50
Looks like a duplicate of #1634

**Closed by vineeththomasalex** 2023-10-13 20:50 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Settings, Needs-Triage, Area-Account-Sign-In
