### ISSUE TITLE
DONT WORK Dashboard

### ISSUE THREAD

**Issue by Damn1selfCode** [microsoft/devhome#1702] opened 2023-10-14 17:21 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2428

### Other software

OS Build Version: 10.0.22621.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

No funciona el panel , no me muestra ninguna valor a excepcion del git .

### Expected result

![image](https://github.com/microsoft/devhome/assets/112675720/6ec2696f-57c7-4abc-aa0e-a949d656b825)

### Actual result

![image](https://github.com/microsoft/devhome/assets/112675720/76630985-d1c3-45a7-b3f7-a3c734cea2b7)

### Included System Information

Physical Memory: 23.96GB (7.56GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-10-16 19:33
Duplicate of #1248

**Closed by krschau** 2023-10-16 19:33 UTC
Labels: Issue-Bug, Needs-Triage
