### ISSUE TITLE
Unable to clone devops repo

### ISSUE THREAD

**Issue by ebmarquez** [microsoft/devhome#1254] opened 2023-07-05 17:02 UTC
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Followed the wizard to add a repo in azure devops git repo.

### Expected result

Clone devops git repo

### Actual result

Error code 0x80131500
Couldn't clone AzureStack-Solutions-OnRamp

### Included System Information

Physical Memory: 63.92GB (49.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment] 2023-07-05 17:13
Duplicate of #521

**Closed** 2023-07-05 17:13 UTC
Labels: Issue-Bug, Needs-Triage
