### ISSUE TITLE
Dev Home Crashes when trying to see available Applications

### ISSUE THREAD

**Issue by luislhg** [microsoft/devhome#807] opened 2023-05-24 17:55 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

A) Go to: Machine Configuration -> Install Applications
B) Scroll to the right until it has no further apps
C) Dev Home Crashes

### Expected result

I expected to see all apps and Dev Home to not crash

### Actual result

Dev Home crashes

### Included System Information

CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Physical Memory: 31.92GB (15GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by AmelBawa-msft** [comment] 2023-05-24 18:05
Likely a duplicate #768

**Comment by krschau** [comment] 2023-05-24 21:13
Duplicate of #768

**Closed by krschau** 2023-05-24 21:13 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Machine-Config
