### ISSUE TITLE
Link to developer settings

### ISSUE THREAD

**Issue by soroshsabz** [microsoft/devhome#1299] opened 2023-07-14 22:15 UTC
### Suggested new feature or improvement

ITNOA

I think it is good to link to Windows developer settings directly from Dev Home

### Scenario

In Dashboard or Introducing Dev Home menu, Add link to Windows developer settings

### Additional details

Maybe this feature can be done by Widget, but I think it is better to native of Dev Home instead of extra Widget

**Comment by cinnamon-msft** [comment] 2023-07-19 22:35
Are there developer settings you're actively visiting that you want quick access to? I'm curious why you want a direct link from Dev Home

**Comment by soroshsabz** [comment] 2023-07-20 07:29
@cinnamon-msft You can add this as, Widget, or add in Settings sub menu, or add new sub menu for this (as your UX approach)

But some important things in Developer Settings exists like below

* PowerShell Settings (Execution Policy)
* Terminal Settings

I think many developer wants to change these settings, so access from DevHome (as central control panel for developers) is good

**Comment by cinnamon-msft** [comment] 2023-07-21 16:36
These are settings that I believe would be set once and not often toggled. We are trying to be cautious in not replicating the Settings app, so I'm not keen on linking out to these if they're not being actively manipulated. I think I'll close this as by design for now and we can see if there are further requests for this. :)

**Closed by cinnamon-msft** 2023-07-21 16:36 UTC
Labels: Issue-Feature, Needs-Team-Response
