### ISSUE TITLE
Authenticating during repo cloning process is not succeeding.

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#1100] opened 2023-05-18 18:30 UTC
### Steps to reproduce the bug

Description
When trying to sign into a GitHub account through the repo cloning window, I am able to authorize PG Internal to my account, but the experience in Dev Home doesn't seem to recognize my account. Clicking Connect does not result in an error, but the next page where you are supposed to choose a repo is completely unpopulated. The pop up window screen moves past the connect screen before I give the extension access.

**Comment by krschau** [comment] 2023-06-08 16:28
Duplicate of #1099

**Closed by krschau** 2023-06-08 16:28 UTC
Labels: Issue-Bug, Area-Machine-Config, Priority-2
