### ISSUE TITLE
Dark Mode Feature Not Working Correctly

### ISSUE THREAD

**Issue by Suman196pokhrel** [microsoft/devhome#870] opened 2023-05-25 19:14 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. go to settings
2. go to preferences
3. select dark mode

### Expected result

I was expecting for the text to change from black to white.
and for background color from white to any dark color

### Actual result

only the text changed from black to white but the background stayed on the same color. nothing changed

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12700H
Physical Memory: 15.75GB (9.52GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-30 17:44
Duplicate of #511

**Closed by krschau** 2023-05-30 17:44 UTC
Labels: Issue-Bug, Needs-Triage, Area-Style
