### ISSUE TITLE
When I change the theme, the text becomes black + Theme colour stays the same.

### ISSUE THREAD

**Issue by Burakuslendera** [microsoft/devhome#796] opened 2023-05-24 16:25 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.25300.1000

### Other software

OS Build Version: 10.0.25300.1000.amd64fre.rs_prerelease.230210-1451
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Setting > Preferences > Light Mode

### Expected result

I expected the application to change it's entire look to light theme

### Actual result

It only changed the colour of text to black, which became unreadable due to the rest of the application not changing themes
Some UI elements changed their colour to white, but the main background still made the most text unreadable.

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by Burakuslendera** [comment] 2023-05-24 16:29
![image](https://github.com/microsoft/devhome/assets/72018039/92823580-8abf-4873-8731-1dee7d626d6c)
![image](https://github.com/microsoft/devhome/assets/72018039/4b169e74-b24d-4ccc-a871-5e42ae2266a6)

**Comment by Burakuslendera** [comment] 2023-05-24 16:36
When I make it default, the colour of the topbar text does not change

**Comment by Burakuslendera** [comment] 2023-05-24 16:36
![image](https://github.com/microsoft/devhome/assets/72018039/c44e528e-6b57-43de-bdd0-74f1c3202413)

**Comment by krschau** [comment] 2023-05-24 20:50
Duplicate of #511

**Closed by krschau** 2023-05-24 20:50 UTC
Labels: Issue-Bug, Needs-Triage
