### ISSUE TITLE
Wider support for GIT solutions.

### ISSUE THREAD

**Issue by GunnerAg** [microsoft/devhome#1304] opened 2023-07-17 10:08 UTC
### Suggested new feature or improvement

Bring up support for more GIT platform options such as Bitbucket or GitLab.

### Scenario

Many users and companies use other GIT solutions instead of GitHub, despite GitHub being a Microsofts GIT solution, allowing this would improve the usability of dev home.

Just as we can connect to GitHub, adding plugins that would enable connection to other services that use GIT, would allow users that have projects on other platforms to use the features of dev home for GIT management.

**Comment by krschau** [comment] 2023-07-17 14:44
The GitLab ask is tracked by #794.
The BitBucket ask is tracked by #954. That one was closed by its author, but I'll reopen it for tracking.
Please give those issues a thumbs up to show your support. If there are any other specific Git solutions you're looking for, we should have a separate issue to track each.

**Comment by krschau** [comment] 2023-07-17 14:44
Duplicate of #794

**Comment by krschau** [comment] 2023-07-17 14:45
Duplicate of #954

**Closed by krschau** 2023-07-17 14:45 UTC
Labels: Issue-Feature, Needs-Triage
