### ISSUE TITLE
CPU等小组件无法使用

### ISSUE THREAD

**Issue by duxingzhe** [microsoft/devhome#3258] opened 2024-06-19 05:25 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3737

### Other software

OS Build Version: 10.0.22631.3737.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

打开开发者人员主页，添加CPU等组件

### Expected result

显示与预览提供一样的界面

### Actual result

提示初始化错误的英文。

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
物理内存: 15.74GB (5.62GB free)
处理器构造: x64

### Included Extensions Information

扩展: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (核心小组件扩展)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V 扩展)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (开发人员主页 GitHub 扩展(预览))

小组件服务: 
MicrosoftWindows.Client.WebExperience_524.13200.20.0_x64__cw5n1h2txyewy
![exception](https://github.com/microsoft/devhome/assets/8346252/7aada439-6350-45f6-9a13-e5467ffb7b48)

Someone reported that this problem is solved. But I still can't use thses widgets normally.

**Comment by krschau** [comment] 2024-06-19 13:41
Bing Translate:
Widgets such as CPUs cannot be used

Open the Developer Home page and add components such as CPUs
The display provides the same interface as the preview

English with initialization error.

**Comment by krschau** [comment] 2024-06-19 13:44
Duplicate of #1117

**Closed by krschau** 2024-06-19 13:44 UTC
Labels: Issue-Bug, Needs-Triage
