### ISSUE TITLE
Sync vs refresh

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3822] opened 2024-09-10 07:20 UTC
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.4112

### Other software

OS Build Version: 10.0.22631.4112.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

On the environments page there is a sync button. That is an interesting verb choice. Sync usually communicates aligning content across two sources. 
I would have expected this verb to be more like "Refresh"

### Expected result

Refresh button

### Actual result

Sync button 

![image](https://github.com/user-attachments/assets/59d09c92-18a8-4991-a0d3-1d9e2ade44b5)

### Included System Information

CPU: Intel(R) Core(TM) Ultra 7 165H
Physical Memory: 31.64GB (11.94GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.23700.10.0_x64__cw5n1h2txyewy

**Comment by huzaifa-d** [comment] 2024-09-24 16:31
Closing as duplicate of #3355

**Closed by huzaifa-d** 2024-09-24 16:31 UTC
Labels: Issue-Bug, Area-Machine-Config
