### ISSUE TITLE
"This widget could not be displayed" is incorrectly displayed.

### ISSUE THREAD

**Issue by mrlacey** [microsoft/devhome#774] opened 2023-05-24 07:54 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Attempt to add a new widget to the dashboard
Choose an item from the "core" group (e.g. GPU, Memory, CPU, etc.)

### Expected result

Show the widget or a message/indication that something is loading.

### Actual result

The message "This widget could not be displayed" is displayed for a few seconds (while the widget loads.) 

Because the loading is so slow, I assumed the option was unavailable, and I selected different items to see if I could add that widget instead.

I went through all the "Core" widgets several times before happening to stay on one long enough for it to actually load.
I was about to raise a bug that none of these widgets worked.
Then I thought that some were failing to load and that was why the message was displayed.

I've come to the conclusion that you're using a message that says "this isn't available" when it should say "this is loading".
**loading != unavailable**

### Included System Information

CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Physical Memory: 15.92GB (3.8GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-24 20:40
Duplicate of #722

**Closed by krschau** 2023-05-24 20:40 UTC
Labels: Issue-Bug, Area-Dashboard, Needs-Triage
