### ISSUE TITLE
"Add a widget" pop up doesn't resize properly, making it impossible to close w/o kb

### ISSUE THREAD

**Issue by aloshTM** [microsoft/devhome#2039] opened 2023-12-12 03:24 UTC
### Dev Home version

0.7.323.0

### Windows build number

10.0.22631.2715

### Steps to reproduce the bug

1. Go to your dashboard
2. Make your windows size pretty small, like a square
3. Click on the "Add a widget" button
3]4. The title buttons (close, minimize and maximize) cover the X of the widget add pop up

### Expected result

The title bar of the pop up should be below the title bar of the windows to fit smaller window sizes and allow closing

### Actual result

The title bar of the pop up is always aligned with the title bar of the window so without resizing left or right, it makes it impossible to close the pop up

https://github.com/microsoft/devhome/assets/74996153/d5fffda9-5952-4bc5-898b-6a732c6cc90a

**Comment by krschau** [comment] 2023-12-12 14:55
Duplicate of #537

**Closed by krschau** 2023-12-12 14:55 UTC
Labels: Issue-Bug, Needs-Triage
