### ISSUE TITLE
Tentar usar conta

### ISSUE THREAD

**Issue by Djonathan-Briesch** [microsoft/devhome#1966] opened 2023-11-27 19:52 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22631.2715

### Other software

OS Build Version: 10.0.22631.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

abrir o Dev Home, Abrir configurações e clicar em conta

### Expected result

Abrir algo para conectar uma conta

### Actual result

O aplicativo trava e fecha

### Included System Information

CPU: Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
Physical Memory: 7.78GB (2.49GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.200.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-27 20:36
Bing Translate:

Try to use account 

Steps to reproduce the bug
Open Dev Home, Open Settings and click on Account

Expected result
Open something to connect an account

Actual result
The app crashes and closes

**Comment by vineeththomasalex** [comment] 2023-12-19 01:00
Without logs, marking this as duplicate of #1945 based on described behavior.

**Closed by vineeththomasalex** 2023-12-19 01:00 UTC
Labels: Issue-Bug, Resolution-Duplicate, Needs-Author-Feedback, Severity-Crash, Area-Account-Sign-In
