### ISSUE TITLE
Dev home widgets not showing graphs

### ISSUE THREAD

**Issue by ahsan7162** [microsoft/devhome#2138] opened 2024-01-16 12:07 UTC
### Dev Home version

0.901.374.0

### Windows build number

10.0.22631.2861

### Steps to reproduce the bug

1. Download latest release from the github
2. Add cpu or gpu usage widget
![image](https://github.com/microsoft/devhome/assets/60193296/3a7ea66b-11e2-488e-a400-6548b809d8e6)
3. pin widget
![image](https://github.com/microsoft/devhome/assets/60193296/6a0a1e31-4d9d-498b-817c-26ee9a6dcf06)

### Expected result

I was expecting to get the graphs as shown in product screen shots
![image](https://github.com/microsoft/devhome/assets/60193296/fb287a36-21c5-4c8e-88f7-1d4dc1641d0e)

### Actual result

![image](https://github.com/microsoft/devhome/assets/60193296/d79e9ffd-0a62-47f2-a961-19f50aca987b)
got this instead

### Included System Information

[mysystem.txt](https://github.com/microsoft/devhome/files/13949639/mysystem.txt)

### Included Extensions Information

I have github, azure and winget extension installed

**Comment by ahsan7162** [comment] 2024-01-16 12:09
this is happening for all dev home widgets (not extension widgets)

**Comment by krschau** [comment] 2024-01-24 17:15
Duplicate of #1248

**Closed by krschau** 2024-01-24 17:15 UTC
Labels: Issue-Bug, Needs-Triage
