### ISSUE TITLE
Dev Home installs itself without interaction

### ISSUE THREAD

**Issue by ghost** [microsoft/devhome#3770] opened 2024-09-05 15:04 UTC
### Dev Home version

0.1701.597.0

### Windows build number

10.0.19045.4780

### Other software

OS Build Version: 10.0.19045.4780.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

turn on your computer

### Expected result

Not installing software that I don't want or need

### Actual result

Software was installed that is useless and takes my valuable disk space.

### Included System Information

CPU: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
Physical Memory: 7.83GB (2.02GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.4.0.0_x64__8wekyb3d8bbwe

**Comment by fuckoff-github** [comment] 2024-09-05 15:10
Fuck your AI powered bot. Its answers are useless.

**Comment by krschau** [comment] 2024-09-05 15:19
Duplicate of #1615

**Closed by krschau** 2024-09-05 15:19 UTC
Labels: Issue-Bug, Needs-Triage
