### ISSUE TITLE
Computer goes up to 100% when executing tasks

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#500] opened 2023-05-18 00:39 UTC
### Steps to reproduce the bug

Description
When the tasks are running My CPU goes up to 100% causing the rest of my computer to slow down.

**Comment by dhoehna** [comment] 2023-06-19 19:53
Closing by design.  However, the number of parallel tasks can be easily changed.

**Closed by dhoehna** 2023-06-19 19:53 UTC
Labels: Issue-Bug, Area-Performance, Area-Quality, Area-Machine-Config, Priority-3, Area-Machine-Config-Loading
