### ISSUE TITLE
Multiple GitHub accounts

### ISSUE THREAD

**Issue by MikkelGutt1996** [microsoft/devhome#2270] opened 2024-02-16 07:24 UTC
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.3155

### Other software

OS Build Version: 10.0.22631.3155.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Add one GitHub account from settings.
Add a second account, click "Sign in to github.com"

### Expected result

Possibility to add a second account

### Actual result

Error Message With the text "Somethig went wrong"

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK
Physical Memory: 31.68GB (12.26GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.40.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-02-16 15:08
Duplicate of https://github.com/microsoft/devhomegithubextension/issues/276

This feature is coming in the 0.11 release.

**Closed by krschau** 2024-02-16 15:08 UTC
Labels: Issue-Bug, Needs-Triage
