### ISSUE TITLE
DevHome update breaks widget layout on dashboard

### ISSUE THREAD

**Issue by Wraiyth** [microsoft/devhome#3885] opened 2024-09-18 22:37 UTC
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

1. Open DevHome after an update
2. Observe that the Dashboard layout is broken.

### Expected result

DevHome should continue to show the dashboard layout as configured.

### Actual result

Today when I opened Dev Home (after it successfully working yesterday), the dashboard widget layout was missing and I could not see the GitHub extension
I believe there was an update that occurred for DevHome and now the widget layout is completely broken. 

![image](https://github.com/user-attachments/assets/521249cc-a9f1-47f1-9af8-2ea00ba50391)

### Included System Information

CPU: Intel(R) Core(TM) i9-14900HX
Physical Memory: 63.71GB (40.97GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.536.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Preview))
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Git)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.24900.10.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.5.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-09-23 13:02
Duplicate of #2945

**Closed** 2024-09-23 13:02 UTC
Labels: Issue-Bug, Needs-Triage
