### ISSUE TITLE
Light theme not working

### ISSUE THREAD

**Issue by Seba244c** [microsoft/devhome#781] opened 2023-05-24 09:06 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Go to settings>preferences, and change the theme to Light

### Expected result

I expected the application to change it's entire look to light theme

### Actual result

It only changed the color of text to black, which became unreadable due to the rest of the application not changing themes
Some UI elements changed their color to white, but the main background still made most text unreadable.

### Included System Information

CPU: AMD Ryzen 5 4600H with Radeon Graphics         
Physical Memory: 7.87GB (2.53GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-24 20:32
Duplicate of #511

**Closed by krschau** 2023-05-24 20:32 UTC
Labels: Issue-Bug, Needs-Triage
