### ISSUE TITLE
Unable to add/clone any repositories

### ISSUE THREAD

**Issue by Izzmo** [microsoft/devhome#2645] opened 2024-04-17 02:20 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22621.3447

### Other software

OS Build Version: 10.0.22621.3447.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

1. Machine Configuration
2. Clone Repositories
3. Click + Add repository button

### Expected result

Should open some dialog which allows me to specify and add/clone a repository down.

### Actual result

The app hangs and crashes after 15 seconds.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
Physical Memory: 7.85GB (1.17GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.700.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-04-17 14:18
Duplicate of #2485

**Closed by krschau** 2024-04-17 14:18 UTC
Labels: Issue-Bug, Needs-Triage
