### ISSUE TITLE
Error in Dashboard: We're having trouble displaying widgets. Restarting Dev Home may help

### ISSUE THREAD

**Issue by ddieppa** [microsoft/devhome#3802] opened 2024-09-09 13:47 UTC
### Dev Home version

0.1701.597.0

### Windows build number

10.0.26120.1542

### Other software

OS Build Version: 10.0.26120.1542.amd64fre.ge_release.240331-1435
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Just Open Dev Home, in the dashboard the widgets wont be there instead there is an error message:
We're having trouble displaying widgets. Restarting Dev Home may help.

### Expected result

Expect to see the widgets in the dashboard

### Actual result

Reopen Dev Home multiple times, same issue

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-1250U
Physical Memory: 15.63GB (5.51GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1200.597.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.24900.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-09-11 16:49
Duplicate of #2945

I believe this is the issue where the widget service isn't starting. You should be able to start it yourself by bringing up the Windows Widget Board directly (instructions are in that issue).

**Closed by krschau** 2024-09-11 16:49 UTC
Labels: Issue-Bug, Needs-Triage
