### ISSUE TITLE
GPU顯示錯誤

### ISSUE THREAD

**Issue by 432HzElics** [microsoft/devhome#1904] opened 2023-11-16 10:15 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

我使用的是外皆顯示卡GPU 3060資源
但在開發人員首頁的GPU顯示卻是內建Intel顯示卡的資源

### Actual result

我使用的是外皆顯示卡GPU 3060資源
但在開發人員首頁的GPU顯示卻是內建Intel顯示卡的資源

### Included System Information

Physical Memory: 47.88GB (41.34GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-17 19:01
Bing Translate:

GPU shows error

Steps to reproduce the bug
I'm using an external graphics card GPU 3060 resource
However, the GPU display on the developer's home page is a resource with built-in Intel graphics cards

Expected result
No response

Actual result
I'm using an external graphics card GPU 3060 resource
However, the GPU display on the developer's home page is a resource with built-in Intel graphics cards

**Comment by krschau** [comment] 2023-11-17 19:02
Duplicate of #821

**Closed by krschau** 2023-11-17 19:02 UTC
Labels: Issue-Bug, Needs-Triage
