### ISSUE TITLE
Add a "Launch Dev Home when Windows starts" setting

### ISSUE THREAD

**Issue by asklar** [microsoft/devhome#1042] opened 2023-06-04 00:37 UTC
### Suggested new feature or improvement

Add a "Launch Dev Home when Windows starts" setting

### Scenario

this would a) dashboard is up and b) ensure extensions catch up to changes that happened since the last time they ran

**Comment by crutkas** [comment] 2023-06-09 05:52
I like this idea a lot

**Comment by krschau** [comment] 2024-01-10 21:37
Duplicate of #624

**Closed by krschau** 2024-01-10 21:37 UTC
Labels: Issue-Feature, Area-Settings, In-PR
