### ISSUE TITLE
GitHub Extension doesn't work with Organisations

### ISSUE THREAD

**Issue by cyberangel67** [microsoft/devhome#1684] opened 2023-10-12 12:18 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22631.2428

### Other software

OS Build Version: 10.0.22631.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Log in and try to use an organisation will not use it

### Expected result

Can use main account and all organisations

### Actual result

can only use main account

### Included System Information

Physical Memory: 63.85GB (40.37GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-10-13 20:05
Duplicate of #1683

**Closed by krschau** 2023-10-13 20:05 UTC
Labels: Issue-Bug, Area-Machine-Config, Needs-Triage
