### ISSUE TITLE
When I click on Dashboard the Dashboard stopped and then after sometime it crashed

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2496] opened 2024-04-01 04:15 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22621.3374

### Other software

OS Build Version: 10.0.22621.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Go to Dashboard.

### Expected result

It should load the empty Dashboard.

### Actual result

Dev Home crashed.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (1.92GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.435.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.700.442.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

### A picture

![image](https://github.com/microsoft/devhome/assets/99239826/c7b205cd-adf1-4a02-ad6d-6ad4b7fd6d2b)

**Comment by krschau** [comment] 2024-04-01 13:54
Duplicate of #2401

**Closed by krschau** 2024-04-01 13:54 UTC
Labels: Issue-Bug, Needs-Triage
