### ISSUE TITLE
GPU temperature is not displayed properly

### ISSUE THREAD

**Issue by GeneralXikto** [microsoft/devhome#2912] opened 2024-05-15 01:07 UTC
### Dev Home version

0.1301.477.0

### Windows build number

10.0.22631

### Steps to reproduce the bug

pin a GPU widget > observe the lack of GPU temprature

### Expected result

something like the temperature reading in task manager
![image](https://github.com/microsoft/devhome/assets/55162317/0f5ffd80-90fb-4cec-ac29-60fa9ffd0500)

### Actual result

The GPU temperature reading is empty
![image](https://github.com/microsoft/devhome/assets/55162317/a567812c-a613-4472-a898-b2fb73358d58)

### Included System Information

System Model:              Nitro AN715-51

**Comment by krschau** [comment] 2024-05-15 14:31
Duplicate of #739

**Closed** 2024-05-15 14:31 UTC
Labels: Issue-Bug

**Comment by krschau** [comment] 2024-05-15 15:51
Sure! If you look at that other issue, at the bottom of the description there's a little 🙂 icon. If you click it, it shows a few options for icons you can add, one of which is a 👍
![image](https://github.com/microsoft/devhome/assets/47155823/2cc0cb3c-13a0-4b8c-baba-659ce60e5f80)
