### ISSUE TITLE
Doesn't show data

### ISSUE THREAD

**Issue by PiterGoCompany** [microsoft/devhome#1767] opened 2023-10-27 08:54 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

After adding a widget, it doesn't display data, only default widget view.

### Expected result

Displays widget data.

### Actual result

Displays default widget view. 

![image](https://github.com/microsoft/devhome/assets/9109223/14c07ef9-8854-4814-9f7c-f1a3af35b788)

### Included System Information

Physical Memory: 31.73GB (14.04GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-10-27 13:53
Duplicate of #1248

**Closed by krschau** 2023-10-27 13:53 UTC
Labels: Issue-Bug, Needs-Triage
