### ISSUE TITLE
Widget Support for Input.Toggle and Input.ChoiceSet

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#1082] opened 2023-06-07 06:51 UTC
### Suggested new feature or improvement

I am unable to use the adaptive card elements Input.Toggle or Input.ChoiceSet in the widgets that I create. These are card elements for Adaptive Card Version 1.5

### Scenario

Users can create new widgets that utilize these elements.

**Comment by krschau** [comment] 2023-06-07 13:29
We were tracking this with #644. The only reason I want to use that one going forward instead of this one is that we specifically mention that issue number in a TODO in the code, so I'm going to put the content of this over there.

**Comment by krschau** [comment] 2023-06-07 13:29
Duplicate of #644

**Closed by krschau** 2023-06-07 13:29 UTC
Labels: Issue-Feature, Area-Widgets, Priority-2
