### ISSUE TITLE
Auto Starts without my knowledge

### ISSUE THREAD

**Issue by aagha** [microsoft/devhome#2674] opened 2024-04-18 16:38 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3447

### Other software

OS Build Version: 10.0.22631.3447.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Turn on Windows

### Expected result

Does not start without my knowledge

### Actual result

Starts without my knowledge

### Included System Information

CPU: AMD Ryzen 7 6800HS Creator Edition
Physical Memory: 27.69GB (1.44GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by cinnamon-msft** [comment] 2024-06-21 16:55
Thanks for the feedback, this is helpful to know! We're experimenting with auto-launching to see if it would be valuable. I'm going to close this issue since it's technically by design, but I appreciate you filing because it helps us learn how this experience is being received.

**Closed by cinnamon-msft** 2024-06-21 16:55 UTC
Labels: Issue-Bug, Needs-Triage
