### ISSUE TITLE
GPU usage is incorrect

### ISSUE THREAD

**Issue by singham2000** [microsoft/devhome#1669] opened 2023-10-09 06:51 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

just run any application it didn't show correct information
GPU tested is GT710

### Expected result

99-100%

### Actual result

4-4 %

### Included System Information

Physical Memory: 7.94GB (0.91GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment] 2023-10-09 16:04
Is this related to the #1656 issue?

**Comment by singham2000** [comment] 2023-10-09 17:04
No, usage is shown but it doesn't match with the usage shown in the  task
manager.

**Comment by skanda890** [comment] 2023-10-12 10:24
Yes , Sometimes the Network usage and the GPU usage is shown wrong.

**Comment by krschau** [comment] 2024-03-15 14:21
Duplicate of #791

**Closed by krschau** 2024-03-15 14:21 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
