### ISSUE TITLE
Crash in add repostory

### ISSUE THREAD

**Issue by sidinei-silva** [microsoft/devhome#2494] opened 2024-03-31 20:41 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3374

### Other software

OS Build Version: 10.0.22631.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Click in add repository

### Expected result

Open select repository

### Actual result

Crash app

### Included System Information

CPU: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
Memória Física: 15.77GB (8.56GB free)
Arquitetura do processador: x64

### Included Extensions Information

Extensões: 
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe

Serviço de widget: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-04-01 13:27
Duplicate of #2485

**Closed by krschau** 2024-04-01 13:27 UTC
Labels: Issue-Bug, Needs-Triage
