### ISSUE TITLE
Add integration with Azure DevOps

### ISSUE THREAD

**Issue by slinnor** [microsoft/devhome#1212] opened 2023-06-27 12:01 UTC
### Suggested new feature or improvement

It will be nice as we can manage our GitHub to be able to also manage Azure DevOps repositories and projects.

### Scenario

Managing Azure DevOps where you can login to your organization, you will be able to see all projects and list of repositories inside of it.

**Comment by krschau** [comment] 2023-06-27 13:20
Duplicate of #521

**Closed by krschau** 2023-06-27 13:20 UTC
Labels: Issue-Feature, Needs-Triage
