### ISSUE TITLE
Doesn't clone all repos

### ISSUE THREAD

**Issue by santhoshdasari786** [microsoft/devhome#2273] opened 2024-02-16 17:44 UTC
### Dev Home version

0.1001.389.0

### Windows build number

10.0.22631.3155

### Other software

OS Build Version: 10.0.22631.3155.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

I have permissions to clone an repo from other organizations but my dev home doesn't allow me to clone and it doesn't show on the list

### Expected result

i am expecting that repo to be clone

### Actual result

it throws an error saying i dont have permission

### Included System Information

CPU: AMD Ryzen 7 5700U with Radeon Graphics         
Physical Memory: 15.34GB (6.11GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.140.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-02-28 18:45
Duplicate of #831

**Closed by krschau** 2024-02-28 18:45 UTC
Labels: Issue-Bug, Area-Machine-Config, Needs-Triage, Area-Machine-Config-Repo
