### ISSUE TITLE
Add widget doesn't work - blank window pops up

### ISSUE THREAD

**Issue by CZEMacLeod** [microsoft/devhome#3621] opened 2024-08-16 15:16 UTC
### Dev Home version

0.1601.561.0

### Windows build number

10.0.26120.1350

### Other software

OS Build Version: 10.0.26120.1350.amd64fre.ge_release.240331-1435
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Click add widget on the home dashboard page

### Expected result

A window with a list of widgets to pick from

### Actual result

Empty window

### Included System Information

CPU: AMD Ryzen 9 7940HS w/ Radeon 780M Graphics     
Physical Memory: 61.81GB (44.24GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.6.1.0_x64__g91dtg5srk15g (Widgets for UniGetUI (formerly WingetUI))
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHomeAzureExtension_0.1100.561.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.536.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.21802.0.0_x64__cw5n1h2txyewy

**Comment by CZEMacLeod** [comment] 2024-08-16 15:22
For troubleshooting, I've just downloaded the vsix from this repo and went to install it.
Odd error/warning message that doesn't make sense:
![image](https://github.com/user-attachments/assets/f1a58b3e-6df3-4feb-8ef4-464b8753800f)
Those are the same version numbers, so I _don't_ have a newer version installed, I just want to re-install this version?

**Comment by krschau** [comment] 2024-08-16 15:47
@CZEMacLeod I don't know a lot of about how the Store does things, but if you still had the 0.1601.5610 version installed, I'm not surprised at that message (even though I agree the wording could be better). I'm going to dupe this issue to another that was opened recently, but it would be helpful if you could share your app logs from a run where you saw this (message will pop up with instructions). /logs

**Comment by krschau** [comment] 2024-08-16 15:48
Duplicate of #3594

**Closed by krschau** 2024-08-16 15:48 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by CZEMacLeod** [comment] 2024-08-16 17:30
Here are the logs...
[devhome logs.zip](https://github.com/user-attachments/files/16639780/devhome.logs.zip)
