### ISSUE TITLE
widgets are flashing when updates it

### ISSUE THREAD

**Issue by RangeSauce** [microsoft/devhome#3375] opened 2024-07-07 19:47 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3810

### Other software

OS Build Version: 10.0.22631.3810.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

1. open dev home
2. add the widgets to the dashboard
3. navigate to dashboard

and see the flash.

### Expected result

cpu/gpu and network widgets are not flashing.

### Actual result

they are flashes.

### Included System Information

CPU: 13th Gen Intel(R) Core(TM) i5-1335U
Physical Memory: 15.69GB (4.26GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.536.0_x64__8wekyb3d8bbwe (Dev Home Microsoft Game Dev Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.30.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-07-08 15:45
Duplicate of #864

**Closed by krschau** 2024-07-08 15:45 UTC
Labels: Issue-Bug, Needs-Triage
