### ISSUE TITLE
Allow to change order of widgets dragging

### ISSUE THREAD

**Issue by vulopez** [microsoft/devhome#851] opened 2023-05-25 13:26 UTC
### Suggested new feature or improvement

# 📝 Description

Will be good if in the panel the widgets could be rearranged by yourself, by drag and drop, and not just for addition order.

### Scenario

# 🖼️ Scenario

Rearranging widgets to reorder them as is needed for the project or wants the user.

**Comment by krschau** [comment] 2023-05-25 13:49
Duplicate of #673

**Closed by krschau** 2023-05-25 13:49 UTC
Labels: Issue-Feature, Needs-Triage
