### ISSUE TITLE
WSL Integration

### ISSUE THREAD

**Issue by evertoont** [microsoft/devhome#809] opened 2023-05-24 18:08 UTC
### Suggested new feature or improvement

A direct integration with WSL would help a lot in managing Dev tools

### Scenario

I think most developers use WSL for coding. So your repositories, SSH keys and the like are connected directly to WSL.

**Comment by adrastogi** [comment] 2023-05-24 18:34
Similar request here: #748

**Comment by krschau** [comment] 2023-05-24 21:10
Duplicate of #748

**Closed by krschau** 2023-05-24 21:10 UTC
Labels: Issue-Feature, Needs-Triage
