### ISSUE TITLE
widget not saved

### ISSUE THREAD

**Issue by jhasmany-fernandez** [microsoft/devhome#1125] opened 2023-06-11 12:18 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.23475.1000

### Other software

OS Build Version: 10.0.23475.1000.amd64fre.ni_prerelease.230602-1331
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

The dashboard does not maintain the widgets added after the system restarts.

### Expected result

that the widgets already assigned to the main dashboard are maintained

### Actual result

Assign the GitHub widgets to the dashboard and restart the computer and the widget is deleted

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-12650H
Physical Memory: 15.63GB (7.52GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-12 14:51
Duplicate of #742

**Closed by krschau** 2023-06-12 14:51 UTC
Labels: Issue-Bug, Needs-Triage
