### ISSUE TITLE
App Crashing SSH KeyChain

### ISSUE THREAD

**Issue by CheoWalker** [microsoft/devhome#3899] opened 2024-09-25 12:51 UTC
### Dev Home version

0.1801.625.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.8

### Steps to reproduce the bug

Go to Dashboard
Click on any of the listed SSH Keychain

### Expected result

Expect for it to open up in terminal and connect remotely to a server via SSH.

### Actual result

When clicking any of the SSH Keys, the application crashes.

### Included System Information

CPU: AMD Ryzen 7 5800X 8-Core Processor             
Physical Memory: 63.93GB (34.32GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1801.625.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1800.625.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1300.624.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.24900.80.0_x64__cw5n1h2txyewy
Microsoft.WidgetsPlatformRuntime_1.5.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-09-25 20:22
Duplicate of #3888

**Closed by krschau** 2024-09-25 20:22 UTC
Labels: Issue-Bug, Needs-Triage
