### ISSUE TITLE
Adding widget crashes dashboard

### ISSUE THREAD

**Issue by pinnet** [microsoft/devhome#1160] opened 2023-06-16 09:37 UTC
### Dev Home version

0.200.165.0

### Windows build number

10.0.23481.1000

### Other software

OS Build Version: 10.0.23481.1000.amd64fre.ni_prerelease.230609-1655
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

After adding network widget app crashed and adding subsequent widgets also caused application to exit.

### Expected result

not to crash

### Actual result

application crashed

### Included System Information

CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Physical Memory: 31.96GB (21.83GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-16 13:54
Duplicate of #745

**Closed by krschau** 2023-06-16 13:54 UTC
Labels: Issue-Bug, Needs-Triage
