### ISSUE TITLE
Select another langage than the current OS langage

### ISSUE THREAD

**Issue by miiitch** [microsoft/devhome#770] opened 2023-05-24 07:13 UTC
### Suggested new feature or improvement

Allow the selection of the langage in Dev Home:
* current OS langage
* specific langage 

### Scenario

I used to work in english, I'd like to use english in Dev Home even if my computer is in French

**Comment by asklar** [comment] 2023-05-24 07:38
Duplicate of #767

**Closed by asklar** 2023-05-24 07:38 UTC
Labels: Issue-Feature, Needs-Triage

**Comment by krschau** [comment] 2023-05-24 20:14
Duplicate of #708
