### ISSUE TITLE
Dev Box Context ... Menu missing required shortcuts

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#2933] opened 2024-05-16 05:45 UTC
### Suggested new feature or improvement

The Environments page has a ... context menu for shortcut commands. These currently include Restart and delete. That menu should also have a direct link to the install applications, clone repositories, add a dev drive, and setup an environment commands on the "machine configuration" page. This allows you the skip the device selection on those pages because the user already provided that context by using the menu on the desired dev box. 

### Scenario

Save developers time, improve discoverability, reduce many mouse clicks, increase engagement.

**Comment by huzaifa-d** [comment] 2024-07-02 19:56
Duplicate of #2668

**Closed by huzaifa-d** 2024-07-02 19:56 UTC
Labels: Issue-Feature, Needs-Triage, Area-Environments
