### ISSUE TITLE
Can't show GPU temperature

### ISSUE THREAD

**Issue by KasuganoHaruku** [microsoft/devhome#1213] opened 2023-06-27 16:23 UTC
### Dev Home version

0.200.170.0

### Windows build number

10.0.23486.1000

### Other software

OS Build Version: 10.0.23486.1000.amd64fre.ni_prerelease.230616-1447
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add GPU information unit to the dashboard

### Expected result

Show GPU temperature

### Actual result

Can't show GPU temperature

### Included System Information

Physical Memory: 31.83GB (22.49GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-27 18:39
Duplicate of #739

**Closed by krschau** 2023-06-27 18:39 UTC
Labels: Issue-Bug, Area-Widgets
