### ISSUE TITLE
Make widgets freely resizable (or give horizontal resize options)

### ISSUE THREAD

**Issue by iamshital** [microsoft/devhome#2388] opened 2024-03-11 19:31 UTC
### Suggested new feature or improvement

Make widget freely resizable not just vertical resize. Or at least add support for few fixed horizontal resize views.

### Scenario

I added a widget to view my PRs. I can only resize vertically and long sentences broken in multiple lines feels like strain on my eyes.

**Comment by krschau** [comment] 2024-03-11 21:02
Duplicate of #724

**Closed by krschau** 2024-03-11 21:02 UTC
Labels: Issue-Feature, Needs-Triage
