### ISSUE TITLE
Widgets get deleted on app restart

### ISSUE THREAD

**Issue by Sandido** [microsoft/devhome#1138] opened 2023-06-13 15:36 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

When I add GitHub widgets then restart the app, the widgets are often deleted from the dashboard. 

### Expected result

I want my widgets to be saved between sessions. 

### Actual result

My widgets are often deleted. 

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 15.6GB (3.41GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-13 16:33
Duplicate of #742

**Closed by krschau** 2023-06-13 16:33 UTC
Labels: Issue-Bug, Needs-Triage
