### ISSUE TITLE
DevHome does not inform the user when Hyper-V services are not running.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#2552] opened 2024-04-08 18:25 UTC
### Steps to reproduce the bug

For some reason my hyper-v services were not running. Not sure why. Therefore no local VM's were showing up.
I eventually enabled \ disabled hyper-v and rebooted.

If the check box is enabled, but the service is not working, we should warn the user and suggest a reboot or other fix. Or maybe a trouble shooting page.

Things that I can think where there could be issues:

- Service running and not working
- Service not enabled though hyper-v enabled on PC.
- Probably the same, but some other service is preventing hyper-v from working. Like docker service maybe?

We do not want to nag the user if they do not want or the PC does not support the hyper-v service.

### Actual result

I had to figure out why it was not working. This was not a devhome specific issue. This was Hyper-V manager was not working correctly.

**Comment by krschau** [comment] 2024-05-08 16:11
Duplicate of #2784

**Closed by krschau** 2024-05-08 16:11 UTC
Labels: Issue-Bug, Priority-2, Area-Environments
