### ISSUE TITLE
Extension's title doesn't align to content

### ISSUE THREAD

**Issue by roxk** [microsoft/devhome#1906] opened 2023-11-16 17:39 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2506

### Other software

OS Build Version: 10.0.22631.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

1. Launch dev home
2. Enlarge window so that content is center-aligned
3. Go to dashboard, observe title is aligned to content
4. Go to extensions, observe title isn't aligned to content

### Expected result

At (4), extensions' title is consistently aligned as other page.

![image](https://github.com/microsoft/devhome/assets/16918354/edfe4e8b-1618-4a38-b767-c9f0019f6337)

### Actual result

At (4), extensions' title is mis-aligned.

![image](https://github.com/microsoft/devhome/assets/16918354/07788835-702b-48f1-afbc-d84cf570a008)

**Comment by krschau** [comment] 2023-11-17 18:49
Duplicate of #1686

**Closed by krschau** 2023-11-17 18:49 UTC
Labels: Issue-Bug, Needs-Triage
