### ISSUE TITLE
malware installed on windows 10

### ISSUE THREAD

**Issue by coltEli** [microsoft/devhome#3350] opened 2024-07-03 15:10 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.19045.4529

### Other software

OS Build Version: 10.0.19045.4529.amd64fre.vb_release.191206-1406
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

run windows ten 

### Expected result

not have random Microsoft software randomly installed without my consent

### Actual result

dev home installed automatically without my input

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
Microsoft.WidgetsPlatformRuntime_1.3.0.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2024-07-08 15:33
Duplicate of #1615

**Closed by krschau** 2024-07-08 15:33 UTC
Labels: Issue-Bug, Needs-Triage
