### ISSUE TITLE
The type initializer for 'CoreWidgetProvider.Helpers.SystemData' threw an exception.

### ISSUE THREAD

**Issue by MaiderGoku** [microsoft/devhome#2673] opened 2024-04-18 15:21 UTC
### Dev Home version

0.1201.442.0

### Windows build number

22631.3447

### Steps to reproduce the bug

Step 1: Open Dev Home Preview
Step 2: Navigate to Dashboard
![Screenshot 2024-04-18 202814](https://github.com/microsoft/devhome/assets/105241930/80c4d149-98fb-4a74-b16b-212751635de7)

### Expected result

Resource monitor working properly
![1685525668_performance_widgets_1](https://github.com/microsoft/devhome/assets/105241930/07d74a91-0816-4943-a9e1-924bc2100899)

### Actual result

Error:
The type initializer for
'CoreWidgetProvider.Helpers.SystemData'
threw an exception.

![Screenshot 2024-04-18 202814](https://github.com/microsoft/devhome/assets/105241930/88abacbc-b3cf-4976-81d0-08cca8c2e01b)

### Included System Information

System Information
[SysInfo.txt](https://github.com/microsoft/devhome/files/15026993/SysInfo.txt)

### Included Extensions Information

![Screenshot 2024-04-18 204529](https://github.com/microsoft/devhome/assets/105241930/8cdd9721-42ea-46e6-bfc0-c6af3529eba2)

**Comment by krschau** [comment] 2024-04-18 15:53
Duplicate of #1117

**Closed by krschau** 2024-04-18 15:53 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by BillEisenman** [comment] 2024-06-12 03:16
This is NOT a Duplicate as I can show it on Windows 11

**Comment by krschau** [comment] 2024-06-12 13:47
Updated other bug's title to reflect it being seen on Windows 11 as well.

**Comment by BillEisenman** [comment] 2024-06-12 15:49
Dev Home version
0.1401.505

Windows build number
Edition	Windows 11 Pro
Version	23H2
Installed on	‎4/‎27/‎2024
OS build	22631.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0

Other software
No response

Steps to reproduce the bug
Step 1: Open Dev Home Preview
Step 2: Navigate to Dashboard

Error: The type initializer for 'CoreWidgetProvider.Helpers.SystemData' threw an exception.

Actual Result:
![image](https://github.com/microsoft/devhome/assets/51295461/b896f8f5-2e96-4ff0-a198-eaa9fe2469fa)

Included System Information:
[FastTrakMobile_MsInfo32_Data_Collection_20240612.txt](https://github.com/user-attachments/files/15807629/FastTrakMobile_MsInfo32_Data_Collection_20240612.txt)

Included Extensions Information:
![image](https://github.com/microsoft/devhome/assets/51295461/5f2913cb-5a3a-4150-b4e0-f23b3e1c89e7)
