### ISSUE TITLE
Cannot add widgets

### ISSUE THREAD

**Issue by ekwarg** [microsoft/devhome#1004] opened 2023-06-01 06:16 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1325

### Other software

OS Build Version: 10.0.22621.1325.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Nothing happens when I click on "add widgets". Sometimes, the application crashes instead.

### Expected result

Be able to install widgets

### Actual result

Nothin or crash

### Included System Information

CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Physical Memory: 7.92GB (1.36GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-01 15:10
Duplicate of #866

**Closed by krschau** 2023-06-01 15:10 UTC
Labels: Issue-Bug, Needs-Triage
