### ISSUE TITLE
Keeps crashing when I try to add a repository

### ISSUE THREAD

**Issue by stereoforever** [microsoft/devhome#2491] opened 2024-03-29 22:06 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3374

### Other software

OS Build Version: 10.0.22631.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

just hit + Add repository

### Expected result

the popup dialog to add a new repository

### Actual result

the program shuts down

### Included System Information

CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Physical Memory: 63.92GB (51.32GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.435.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.4.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-03-31 18:46
Duplicate of #2485

**Closed by krschau** 2024-03-31 18:46 UTC
Labels: Issue-Bug, Needs-Triage
