### ISSUE TITLE
I lost all the items on the dash board again

### ISSUE THREAD

**Issue by martin-morin** [microsoft/devhome#1063] opened 2023-06-05 18:36 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.23471.1000

### Other software

OS Build Version: 10.0.23471.1000.amd64fre.ni_prerelease.230526-1341
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Set the dash board
Close the application
Restart the PC 
Open the dashboard

All of the items on the dashboard are lost.

### Expected result

Retain the items I set on the dashboard

### Actual result

The dashboard is empty

### Included System Information

CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
Physical Memory: 31.81GB (12.79GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-05 19:30
Duplicate of #742

**Closed by krschau** 2023-06-05 19:30 UTC
Labels: Issue-Bug, Needs-Triage
