### ISSUE TITLE
Dev Home lags for approximately 4 seconds

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1874] opened 2023-11-11 05:12 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Go to Dashboard>Add New Widget

### Expected result

It should show a preview of the processes.

### Actual result

It said "Could not show the widget" for approximately 4 seconds ( or something like that I don't completely remember )

### Included System Information

Physical Memory: 11.89GB (3.46GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-13 20:43
Duplicate of #722

**Closed by krschau** 2023-11-13 20:43 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by skanda890** [comment] 2023-11-16 12:43
Not a duplicate of #722.  In #722 it says 2-3 seconds. But in this issue, it says 4 seconds that is the difference. So, re-open this issue.
