### ISSUE TITLE
仪表板无法固定组件

### ISSUE THREAD

**Issue by wang1000001000** [microsoft/devhome#2020] opened 2023-12-08 07:19 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22635.2841

### Other software

OS Build Version: 10.0.22635.2841.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

点击固定无反应

### Actual result

ee

### Included System Information

CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
Physical Memory: 15.81GB (7.73GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.200.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-12-11 18:27
Bing Translate:

Dashboard can't pin component #2020

Steps to reproduce the bug
Click Pin no response

**Comment by krschau** [comment] 2023-12-11 18:29
I suspect this is a duplicate of #1551.

**Closed by krschau** 2023-12-11 18:29 UTC
Labels: Issue-Bug, Needs-Triage
