### ISSUE TITLE
The Environment page is loading for too long

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#2448] opened 2024-03-21 15:54 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22621.3296

### Other software

OS Build Version: 10.0.22621.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Enable everything in the Experimental Settings.

### Expected result

It should load immediately.

### Actual result

It was loading for a very long time.

### Included System Information

CPU: Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz
Physical Memory: 11.89GB (2.28GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeAzureExtension_0.600.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1100.422.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.DevHomeMicrosoftGameDevExtension_0.400.435.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

### A picture

![image](https://github.com/microsoft/devhome/assets/99239826/cb4f8e36-4538-44c7-a021-a428f913bb37)

**Comment by skanda890** [comment] 2024-03-21 15:57
After too long it loaded, but still make the loading time less.

**Comment by skanda890** [comment] 2024-03-22 06:21
After one day, again it is loading.

**Comment by skanda890** [comment] 2024-04-02 06:17
> Does the latest version also take long for you to load?

Huh, which version, because in v12 it is still happening.

**Comment by krschau** [comment] 2024-06-24 16:57
Duplicate of #3003

**Closed by krschau** 2024-06-24 16:57 UTC
Labels: Issue-Bug, Priority-2, Area-Environments
