### ISSUE TITLE
Next network button does nothing

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3630] opened 2024-08-16 19:30 UTC
### Dev Home version

0.1701.592.0

### Steps to reproduce the bug

Pin network widget
Click "next network"

### Expected result

I should see the next network

### Actual result

Nothing happens

**Comment by krschau** [comment] 2024-08-16 19:48
Do you have more than one network?

Duplicate of #1075

**Closed by krschau** 2024-08-16 19:48 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Triage
