### ISSUE TITLE
Option to select language

### ISSUE THREAD

**Issue by esibruti** [microsoft/devhome#2547] opened 2024-04-06 13:59 UTC
### Suggested new feature or improvement

I think most developers are used to working with the tools in English because the translations but our native languages often don't represent their meaning correctly. My suggestion would be to add an option to change the language of the app instead of changing the Windows language. I speak for myself, I like to have Windows in Portuguese and use the development tools in English. 

### Scenario

I, Bruno, have Windows with the language of Portuguese of Portugal but I want to use the programming/development tools in English.

### Additional details

I think it's a very practical feature for us programmers of other languages.

**Comment by krschau** [comment] 2024-04-08 13:48
Duplicate of #708

**Closed by krschau** 2024-04-08 13:48 UTC
Labels: Issue-Feature, Needs-Triage
