### ISSUE TITLE
Default widgets do not work

### ISSUE THREAD

**Issue by Taron-art** [microsoft/devhome#1952] opened 2023-11-24 09:13 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22631.2506

### Other software

OS Build Version: 10.0.22631.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

1. On my machine the default widgets just do not show anything other than placeholders. 

### Expected result

Default CPU widget shows graph and processes

### Actual result

Default CPU widget shows placeholders:
![зображення](https://github.com/microsoft/devhome/assets/12997554/4c417486-3b8c-4482-b27d-796b6b936af6)

### Included System Information

CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Physical Memory: 31.78GB (21.7GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-27 15:27
Duplicate of #1248

**Closed by krschau** 2023-11-27 15:27 UTC
Labels: Issue-Bug, Needs-Triage
