### ISSUE TITLE
Bug SSH Widget on Dashboard

### ISSUE THREAD

**Issue by SourcierDeVerite** [microsoft/devhome#1614] opened 2023-09-28 13:33 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Try to modify the SSH Widget on the Dashboard and close it with no changes

### Expected result

The modify windows closes

### Actual result

Nothing append

### Included System Information

Physical Memory: 23.35GB (8.75GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-09-28 16:14
Hi @SourcierDeVerite. Does the size of your Dev Home window mean that the top of the modify window is directly on top of the main window's title bar? Like this?
![image](https://github.com/microsoft/devhome/assets/47155823/23eec05f-eb3e-4ffd-9f6a-9400f6a7c9aa)

I'm thinking this might be a dupe of #537

**Comment by SourcierDeVerite** [comment] 2023-09-28 18:26
Hi.
Yes, that’s exactly it. I didn’t realize because my screen is zoomed in 150% so the SSH window is taken all the size of the DevHub window. I tried putting the zoom at 100% and  and it works perfectly. Mayby another is that we cant move the SSH windows with drag and drop. 

Zoom 150%: 

![Capture d'écran 2023-09-28 202027](https://github.com/microsoft/devhome/assets/78081509/bfef8b98-bd21-4e90-a47c-699f1ad5d7b5)

Zoom 100%:

![Capture d'écran 2023-09-28 202027](https://github.com/microsoft/devhome/assets/78081509/58de0674-af05-43b5-8e52-99f2bf705e4f)

**Comment by krschau** [comment] 2023-09-28 19:47
Is drag and drop not working for you? You should be able to click a widget and drag it onto another widget in order to move it.

**Comment by SourcierDeVerite** [comment] 2023-09-29 06:10
It's work for the widget, but not for the setting windows of a widget. When I try, it moves the main window (which is behind) or it doesn’t do anything. I also can't change its size.

**Comment by krschau** [comment] 2023-10-18 16:22
I see. That's by design -- ContentDialogs are not designed to be movable or resizable. I'm going to dupe this back under #537 -- when that gets fixed, you won't need to move the dialog.

**Comment by krschau** [comment] 2023-10-18 16:22
Duplicate of #537

**Closed by krschau** 2023-10-18 16:22 UTC
Labels: Issue-Bug, Area-Dashboard, Needs-Team-Response
