### ISSUE TITLE
Risk of stopping a process by mistake

### ISSUE THREAD

**Issue by maximedrouhin** [microsoft/devhome#1124] opened 2023-06-11 05:15 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Ensure there isn't any process running that is heavy on the CPU. Add the CPU widget and kill a process.

### Expected result

The process you wanted to kill should get killed.

### Actual result

Depending on your processes and their CPU load, the processes move around so much, that it's almost impossible to kill the one you want. So you either have to accept that the buttons are useless, or you can choose to risk it and you might kill a process by mistake...

**Comment by krschau** [comment] 2023-08-01 20:27
I know this was opened first, but I'm going to dupe it to 1284 because that one has a PR attached.

**Comment by krschau** [comment] 2023-08-01 20:27
Duplicate of #1284

**Closed by krschau** 2023-08-01 20:27 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Design, Needs-PM
