### ISSUE TITLE
Error displaying a list of Dev Box under Environments Tab

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3691] opened 2024-08-23 17:53 UTC
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.4037

### Other software

OS Build Version: 10.0.22631.4037.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Go to environments with Azure extension enabled.

### Expected result

See a list of Dev Boxes I have.

### Actual result

Nothing shows up. There is an error box related to Dev Box on the bottom right corner.

### Included System Information

CPU: Intel(R) Core(TM) i9-14900HX
Physical Memory: 31.71GB (16.36GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeAzureExtension_0.1100.561.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))
Microsoft.Windows.DevHomeGitHubExtension_0.1600.561.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.18500.10.0_x64__cw5n1h2txyewy

**Comment by jiayac** [comment] 2024-08-23 17:54
![image](https://github.com/user-attachments/assets/148f11e4-a449-46f0-8c3b-eaaebd003622)

**Comment by huzaifa-d** [comment] 2024-09-03 20:51
Does this repro, @jiayac? Could you provide the logs please?

**Comment by Dorisls** [comment] 2024-09-30 05:55
Cannot reproduce in Dev home version **0.1801.625.0**. Seems to be fixed now.

**Comment by arkthur** [comment] 2024-10-04 16:28
I can still reproduce this.

Logs:
```log
[2024/10/04 13:20:36.287 INF] (DevHome) Launched with args: 
[2024/10/04 13:20:38.955 INF] (DevHome) Dev Home Started.
[2024/10/04 13:20:40.338 INF] (SetupFlowOrchestrator) Moving to MainPageViewModel
[2024/10/04 13:20:40.339 INF] (SetupPageViewModelBase) Executing post-navigation tasks for page MainPageViewModel
[2024/10/04 13:20:40.350 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/10/04 13:20:40.946 INF] (AppManagementInitializer) Initializing app management
[2024/10/04 13:20:40.946 INF] (AppManagementInitializer) Initialize catalogs from all data sources
[2024/10/04 13:20:40.947 INF] (CatalogDataSourceLoader) Initializing package list from data source WinGetPackageRestoreDataSource
[2024/10/04 13:20:40.979 WRN] (WinGetPackageRestoreDataSource) Restore data source skipped with status: NotAvailable
[2024/10/04 13:20:40.979 INF] (CatalogDataSourceLoader) Initializing package list from data source WinGetPackageJsonDataSource
[2024/10/04 13:20:40.980 INF] (WinGetPackageJsonDataSource) Reading package list from JSON file C:\Program Files\WindowsApps\Microsoft.Windows.DevHome_0.1801.640.0_x64__8wekyb3d8bbwe\Assets/AppManagementPackages.json
[2024/10/04 13:20:41.067 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) WinGet COM Server is available
[2024/10/04 13:20:41.443 INF] (MainPageViewModel) IWinGet COM Server is available. Showing package install item
[2024/10/04 13:20:41.444 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) Checking if AppInstaller has an update ...
[2024/10/04 13:20:41.460 INF] (CatalogDataSourceLoader) Initializing package list from data source WinGetFeaturedApplicationsDataSource
[2024/10/04 13:20:41.461 INF] (WinGetFeaturedApplicationsDataSource) Getting featured applications from all extensions
[2024/10/04 13:20:41.687 INF] (AppManagementInitializer) Ensuring AppInstaller is registered ...
[2024/10/04 13:20:41.688 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/10/04 13:20:41.707 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) WinGet COM Server is available
[2024/10/04 13:20:41.974 INF] (DevHome) Activated with kind Launch
[2024/10/04 13:20:42.156 INF] (AppManagementInitializer) AppInstaller is already registered
[2024/10/04 13:20:42.157 INF] (AppManagementInitializer) Ensuring app management initialization
[2024/10/04 13:20:42.178 INF] (WidgetServiceService) Checking for WidgetService on Windows 11
[2024/10/04 13:20:42.178 INF] (WidgetServiceService) Checking for WidgetsPlatformRuntime...
[2024/10/04 13:20:42.186 INF] (DevHome.Services.Core.Services.PackageDeploymentService) Found package Microsoft.WidgetsPlatformRuntime_1.6.0.0_x64__8wekyb3d8bbwe
[2024/10/04 13:20:42.189 INF] (WidgetServiceService) ValidatePackage found MeetsMinVersion
[2024/10/04 13:20:42.189 INF] (DashboardView) WidgetServiceState meets min version
[2024/10/04 13:20:42.190 INF] (DashboardView) SubscribeToWidgetCatalogEvents
[2024/10/04 13:20:42.244 INF] (AppManagementInitializer) Configuration is unstubbed
[2024/10/04 13:20:44.018 INF] (DashboardView) Is first dashboard run = False
[2024/10/04 13:20:44.029 INF] (DashboardView) Get widgets for current host
[2024/10/04 13:20:44.315 INF] (DashboardView) Found 7 widgets for this host
[2024/10/04 13:20:44.320 INF] (DashboardView) Restore pinned widgets
[2024/10/04 13:20:44.329 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":3}
[2024/10/04 13:20:45.153 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.156 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":1}
[2024/10/04 13:20:45.159 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.166 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":5}
[2024/10/04 13:20:45.168 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.170 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":6}
[2024/10/04 13:20:45.172 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.173 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":0}
[2024/10/04 13:20:45.175 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.176 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":4}
[2024/10/04 13:20:45.177 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.178 INF] (DashboardView) GetWidgetCustomState: {"host":"DevHome","position":2}
[2024/10/04 13:20:45.180 INF] (WidgetHelpers) Found provider Id = Microsoft.Windows.DevHome_8wekyb3d8bbwe!App!!CoreWidgetProvider, include = True
[2024/10/04 13:20:45.206 INF] (DashboardView) Insert widget in pinned widgets, id = 4c133b33-5a9c-4ac2-84f9-6d01a3aad3bb, index = 0
[2024/10/04 13:20:48.766 INF] (DashboardView) Insert widget in pinned widgets, id = e4d52455-1ec3-4647-84c8-707910494465, index = 1
[2024/10/04 13:20:49.079 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) AppInstaller update available = False
[2024/10/04 13:20:49.080 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/10/04 13:20:49.094 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) WinGet COM Server is available
[2024/10/04 13:20:49.124 INF] (WidgetAdaptiveCardRenderingService) Get HostConfig file 'HostConfigLight.json'
[2024/10/04 13:20:49.137 INF] (DashboardView) Insert widget in pinned widgets, id = c6326f60-927e-4937-b462-e113bed524fa, index = 2
[2024/10/04 13:20:49.186 INF] (DashboardView) Insert widget in pinned widgets, id = 10b6f9e8-c866-45d0-80fb-44fdf4d7a856, index = 3
[2024/10/04 13:20:49.383 INF] (DashboardView) Insert widget in pinned widgets, id = 912c9745-4090-4da2-a1e3-639e6c501af7, index = 4
[2024/10/04 13:20:49.416 INF] (DashboardView) Insert widget in pinned widgets, id = 195e2d73-fb1c-4c0c-a3f0-5fca5b944c6d, index = 5
[2024/10/04 13:20:49.446 INF] (DashboardView) Insert widget in pinned widgets, id = 48447973-53c7-4487-9cfd-a4f5d7c43a1b, index = 6
[2024/10/04 13:20:49.874 INF] (DashboardView) Done restoring pinned widgets
[2024/10/04 13:20:57.901 INF] (AppManagementInitializer) Loading catalogs from all data sources at launch time to reduce the wait time when this information is requested
[2024/10/04 13:20:57.902 INF] (CatalogDataSourceLoader) Loading winget packages from data source WinGetPackageRestoreDataSource
[2024/10/04 13:20:57.908 WRN] (WinGetPackageRestoreDataSource) Load catalogs skipped because no restore device information was found
[2024/10/04 13:20:57.911 INF] (AppManagementInitializer) Loaded 0 catalogs []
[2024/10/04 13:20:57.911 INF] (CatalogDataSourceLoader) Loading winget packages from data source WinGetPackageJsonDataSource
[2024/10/04 13:20:57.914 INF] (WinGetPackageJsonDataSource) Attempting to read JSON package catalog Popular applications
[2024/10/04 13:20:57.927 INF] (DevHome.Services.WindowsPackageManager.Services.Operations.WinGetGetPackageOperation) Packages loaded from cache []
[2024/10/04 13:20:57.927 INF] (DevHome.Services.WindowsPackageManager.Services.Operations.WinGetGetPackageOperation) Package URIs not found in cache [x-ms-winget://winget/Microsoft.VisualStudio.2022.Community, x-ms-winget://winget/Microsoft.VisualStudioCode, x-ms-winget://winget/Microsoft.PowerShell, x-ms-winget://winget/Git.Git, x-ms-winget://winget/Notepad++.Notepad++, x-ms-winget://winget/Microsoft.SQLServerManagementStudio, x-ms-winget://winget/Microsoft.PowerToys, x-ms-winget://winget/7zip.7zip, x-ms-winget://winget/Google.AndroidStudio, x-ms-winget://winget/JetBrains.IntelliJIDEA.Community, x-ms-winget://winget/JetBrains.PyCharm.Community, x-ms-winget://winget/Python.Python.3.11, x-ms-winget://winget/Microsoft.DotNet.SDK.7, x-ms-winget://winget/Docker.DockerDesktop, x-ms-winget://winget/PuTTY.PuTTY, x-ms-winget://winget/Unity.Unity.2022, x-ms-winget://winget/Orwell.Dev-C++, x-ms-winget://winget/Codeblocks.Codeblocks, x-ms-winget://winget/SublimeHQ.SublimeText.4, x-ms-winget://winget/vim.vim, x-ms-winget://winget/Postman.Postman, x-ms-winget://winget/GitHub.GitHubDesktop, x-ms-winget://winget/OpenJS.NodeJS]
[2024/10/04 13:20:57.930 INF] (DevHome.Services.WindowsPackageManager.Services.Operations.WinGetGetPackageOperation) Getting packages [Microsoft.VisualStudio.2022.Community, Microsoft.VisualStudioCode, Microsoft.PowerShell, Git.Git, Notepad++.Notepad++, Microsoft.SQLServerManagementStudio, Microsoft.PowerToys, 7zip.7zip, Google.AndroidStudio, JetBrains.IntelliJIDEA.Community, JetBrains.PyCharm.Community, Python.Python.3.11, Microsoft.DotNet.SDK.7, Docker.DockerDesktop, PuTTY.PuTTY, Unity.Unity.2022, Orwell.Dev-C++, Codeblocks.Codeblocks, SublimeHQ.SublimeText.4, vim.vim, Postman.Postman, GitHub.GitHubDesktop, OpenJS.NodeJS] from parsed uri catalog name: winget
[2024/10/04 13:20:57.930 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting packages: [Microsoft.VisualStudio.2022.Community, Microsoft.VisualStudioCode, Microsoft.PowerShell, Git.Git, Notepad++.Notepad++, Microsoft.SQLServerManagementStudio, Microsoft.PowerToys, 7zip.7zip, Google.AndroidStudio, JetBrains.IntelliJIDEA.Community, JetBrains.PyCharm.Community, Python.Python.3.11, Microsoft.DotNet.SDK.7, Docker.DockerDesktop, PuTTY.PuTTY, Unity.Unity.2022, Orwell.Dev-C++, Codeblocks.Codeblocks, SublimeHQ.SublimeText.4, vim.vim, Postman.Postman, GitHub.GitHubDesktop, OpenJS.NodeJS] from PredefinedWinget
[2024/10/04 13:20:58.046 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Performing search on catalog PredefinedWinget
[2024/10/04 13:21:10.307 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) Attempting to create a dummy out-of-proc PackageManager COM object to test if the COM server is available
[2024/10/04 13:21:10.318 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetDeployment) WinGet COM Server is available
[2024/10/04 13:21:10.591 INF] (DashboardView) UnsubscribeFromWidgetCatalogEvents
[2024/10/04 13:21:12.569 INF] (LandingPageViewModel) Adding any new create compute system operations to ComputeSystemCards list
[2024/10/04 13:21:13.606 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Found 23 results from catalog PredefinedWinget [Microsoft.VisualStudio.2022.Community, Microsoft.VisualStudioCode, Microsoft.PowerShell, Git.Git, Notepad++.Notepad++, Microsoft.SQLServerManagementStudio, Microsoft.PowerToys, 7zip.7zip, Google.AndroidStudio, JetBrains.IntelliJIDEA.Community, JetBrains.PyCharm.Community, Python.Python.3.11, Microsoft.DotNet.SDK.7, Docker.DockerDesktop, PuTTY.PuTTY, Unity.Unity.2022, Orwell.Dev-C++, Codeblocks.Codeblocks, SublimeHQ.SublimeText.4, vim.vim, Postman.Postman, GitHub.GitHubDesktop, OpenJS.NodeJS]
[2024/10/04 13:21:13.606 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Microsoft.VisualStudio.2022.Community
[2024/10/04 13:21:14.472 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package Microsoft.VisualStudio.2022.Community
[2024/10/04 13:21:14.553 WRN] (DevHome.Services.WindowsPackageManager.Services.Operations.WinGetGetPackageOperation) Failed to get package metadata [PublisherUrl] for package Microsoft.VisualStudio.2022.Community; defaulting to 
[2024/10/04 13:21:14.555 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Microsoft.VisualStudioCode
[2024/10/04 13:21:14.589 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Microsoft.VisualStudioCode
[2024/10/04 13:21:14.637 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Microsoft.PowerShell
[2024/10/04 13:21:15.269 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Microsoft.PowerShell
[2024/10/04 13:21:15.305 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Git.Git
[2024/10/04 13:21:16.031 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package Git.Git
[2024/10/04 13:21:16.058 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Notepad++.Notepad++
[2024/10/04 13:21:16.702 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package Notepad++.Notepad++
[2024/10/04 13:21:16.731 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Microsoft.SQLServerManagementStudio
[2024/10/04 13:21:16.862 ERR] (EnvironmentsNotificationHelper) Error after retrieving Compute systems for provider: Provider Id: Microsoft.DevBox 
DisplayText: Unable to retrieve all Dev Boxes for italo_masserano@outlook.com. One or more errors occurred. (WAM Error  
 Error Code: 3399614467 
 Error Message: (pii) 
 Internal Error Code: 558133255 
) 
DiagnosticText:  
ExtendedError: System.Runtime.InteropServices.COMException (0x80131500)
[2024/10/04 13:21:17.346 INF] (ComputeSystemViewModel) Registering ComputeSystemViewModel 'Ubuntu' from provider 'Microsoft WSL' with WeakReferenceMessenger
[2024/10/04 13:21:17.351 INF] (ComputeSystemViewModel) Registering pin operations for Ubuntu in background took 00:00:00.0001876
[2024/10/04 13:21:17.362 INF] (ComputeSystemViewModel) Registering ComputeSystemViewModel 'docker-desktop' from provider 'Microsoft WSL' with WeakReferenceMessenger
[2024/10/04 13:21:17.362 INF] (ComputeSystemViewModel) Registering pin operations for docker-desktop in background took 00:00:00.0000075
[2024/10/04 13:21:17.383 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Microsoft.SQLServerManagementStudio
[2024/10/04 13:21:17.411 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Microsoft.PowerToys
[2024/10/04 13:21:18.048 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Microsoft.PowerToys
[2024/10/04 13:21:18.094 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package 7zip.7zip
[2024/10/04 13:21:18.723 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package 7zip.7zip
[2024/10/04 13:21:18.734 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Google.AndroidStudio
[2024/10/04 13:21:19.359 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package Google.AndroidStudio
[2024/10/04 13:21:19.371 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package JetBrains.IntelliJIDEA.Community
[2024/10/04 13:21:20.086 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package JetBrains.IntelliJIDEA.Community
[2024/10/04 13:21:20.116 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package JetBrains.PyCharm.Community
[2024/10/04 13:21:20.761 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package JetBrains.PyCharm.Community
[2024/10/04 13:21:20.784 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Python.Python.3.11
[2024/10/04 13:21:21.422 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Python.Python.3.11
[2024/10/04 13:21:21.432 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Microsoft.DotNet.SDK.7
[2024/10/04 13:21:21.611 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Microsoft.DotNet.SDK.7
[2024/10/04 13:21:21.637 WRN] (DevHome.Services.WindowsPackageManager.Services.Operations.WinGetGetPackageOperation) Failed to get package metadata [PublisherUrl] for package Microsoft.DotNet.SDK.7; defaulting to 
[2024/10/04 13:21:21.638 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Docker.DockerDesktop
[2024/10/04 13:21:22.268 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Docker.DockerDesktop
[2024/10/04 13:21:22.305 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package PuTTY.PuTTY
[2024/10/04 13:21:22.927 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package PuTTY.PuTTY
[2024/10/04 13:21:22.935 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Unity.Unity.2022
[2024/10/04 13:21:23.572 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Unity.Unity.2022
[2024/10/04 13:21:23.602 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Orwell.Dev-C++
[2024/10/04 13:21:24.229 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package Orwell.Dev-C++
[2024/10/04 13:21:24.235 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Codeblocks.Codeblocks
[2024/10/04 13:21:24.863 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Codeblocks.Codeblocks
[2024/10/04 13:21:24.868 WRN] (DevHome.Services.WindowsPackageManager.Services.Operations.WinGetGetPackageOperation) Failed to get package metadata [PublisherUrl] for package Codeblocks.Codeblocks; defaulting to 
[2024/10/04 13:21:24.870 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package SublimeHQ.SublimeText.4
[2024/10/04 13:21:25.511 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package SublimeHQ.SublimeText.4
[2024/10/04 13:21:25.521 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package vim.vim
[2024/10/04 13:21:26.163 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package vim.vim
[2024/10/04 13:21:26.254 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package Postman.Postman
[2024/10/04 13:21:26.881 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package Postman.Postman
[2024/10/04 13:21:26.901 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package GitHub.GitHubDesktop
[2024/10/04 13:21:27.524 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = Unknown for package GitHub.GitHubDesktop
[2024/10/04 13:21:27.545 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Getting applicable installer info for package OpenJS.NodeJS
[2024/10/04 13:21:28.160 INF] (DevHome.Services.WindowsPackageManager.Services.WinGetPackageFinder) Elevation requirement = ElevatesSelf for package OpenJS.NodeJS
[2024/10/04 13:21:28.217 INF] (WinGetPackageJsonDataSource) Obtaining icon information for JSON packages: [(Visual Studio Community 2022, winget), (Microsoft Visual Studio Code, winget), (PowerShell, winget), (Git, winget), (Notepad++, winget), (Microsoft SQL Server Management Studio, winget), (PowerToys (Preview), winget), (7-Zip, winget), (Android Studio, winget), (IntelliJ IDEA Community Edition, winget), (PyCharm Community Edition, winget), (Python 3.11, winget), (Microsoft .NET SDK 7.0, winget), (Docker Desktop, winget), (PuTTY, winget), (Unity 2022, winget), (Dev-C++, winget), (Code::Blocks, winget), (Sublime Text 4, winget), (Vim, winget), (Postman, winget), (GitHub Desktop, winget), (Node.js, winget)]
[2024/10/04 13:21:28.455 INF] (AppManagementInitializer) Loaded 1 catalogs [Popular applications]
[2024/10/04 13:21:28.455 INF] (CatalogDataSourceLoader) Loading winget packages from data source WinGetFeaturedApplicationsDataSource
[2024/10/04 13:21:28.456 INF] (WinGetFeaturedApplicationsDataSource) Getting featured applications from all extensions
[2024/10/04 13:21:28.456 INF] (AppManagementInitializer) Loaded 0 catalogs []
[2024/10/04 13:21:28.457 INF] (AppManagementInitializer) Finished ensuring app management initialization
[2024/10/04 13:21:28.457 INF] (AppManagementInitializer) Completed app management initialization
```

**Comment by arkthur** [comment] 2024-10-13 05:59
Can no one else reproduce this now?

**Closed** 2024-10-23 14:49 UTC
Labels: Issue-Bug, Needs-Author-Feedback, Priority-1, Status-No recent activity, Area-Environments
