### ISSUE TITLE
Add an existing repository

### ISSUE THREAD

**Issue by aL3891** [microsoft/devhome#854] opened 2023-05-25 14:35 UTC
### Suggested new feature or improvement

The ability to add an already cloned repository seems to be missing

### Scenario

The vast majority of developers will already have cloned their code when starting to use dev home, it should be possible to add any existing git repository to the application

### Additional details

Dev home in general seems very focused on github specifically, you will get a lot of pushback on this if git isn't supported generally, or even better, other hosts like gitlab and bitbucket have specific plugins as well.
It will not be enough to say that the community can build plugins for those, you should really really consider building these out of the box or you will lose alot of developer mindshare that will you'll have to fight tooth and nail to get back.
Likewise, many developers work across many different repos, using different hosts and often also different accounts on the same provider, you'll need to support this as well

**Comment by krschau** [comment] 2023-05-25 15:54
@danieltharris An ADO extension is covered in issue #521

**Comment by krschau** [comment] 2023-05-25 15:54
Duplicate of #780

**Comment by HotCakeX** [comment] 2023-05-25 22:16
I agree that there needs to be a way to add our locally cloned repository folders to Dev Home, but it doesn't make any sense that Dev Home developers should create 3rd party extensions for other services. that defeats the whole purpose of community and open-source nature.

Can't be an OSS supporter and then expect a single company to create everything for you. That's were community comes into play.

**Closed** 2023-05-27 04:21 UTC
Labels: Resolution-Duplicate, Issue-Feature, Area-Widgets
