### ISSUE TITLE
Why was this thing suddenly installed on my machine without any sort of consent on my part?

### ISSUE THREAD

**Issue by fthevenet** [microsoft/devhome#2399] opened 2024-03-13 09:11 UTC
### Dev Home version

0.1101.416.0

### Windows build number

10.0.19045.4123

### Steps to reproduce the bug

Absolutely none that I can tell; this just seemed to appear out of the blue. **That is a problem, in case its not obvious...** 

### Expected result

Not having things installed that I didn't vet.

### Actual result

Not having things installed that I didn't vet.

**Comment by krschau** [comment] 2024-03-13 13:41
Duplicate of #1615

**Closed by krschau** 2024-03-13 13:41 UTC
Labels: Issue-Bug, Needs-Triage
