### ISSUE TITLE
Step execution count goes out of sync

### ISSUE THREAD

**Issue by carlheinrichhancke** [microsoft/devhome#969] opened 2023-05-31 02:10 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22631.1825

### Other software

OS Build Version: 10.0.22631.1825.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I was installing 7 components using the End-to-End configuration option. These components were:
- Visual Studio 2022 Community
- Git
- PowerShell
- Postman
- Ubuntu (for WSL2)
- Docker Desktop
- Azure Data Studio

The "Executing Step..." counter on the installation screen started at 5, i.e. "Executing Step 5/7". After the first 3 applications were installed, it just remained at "Executing Step 7/7".

### Expected result

The counter should accurately start at "Executing Step 1/7", incrementing as applications are installed.

### Actual result

The counter appears to initialize at the wrong place, incorrectly indicating which step it's on.

### Included System Information

CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Physical Memory: 15.92GB (9.71GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by dhoehna** [comment] 2023-06-19 19:15
Closing as by design.

The X/Y stepper shows how many tasks have started.  Because 5 tasks start immediately the stepper goes to 5/Y.  Then, when one task is done, another task starts and the stepper goes to 6/Y.

@carlheinrichhancke in your case, once three tasks were done the remaining tasks started.

The progress bar, above the execution count, keeps track of the number of completed tasks.  That will advance only when a task is completed.

**Closed by dhoehna** 2023-06-19 19:15 UTC
Labels: Issue-Bug, Area-Machine-Config, Priority-2, Area-Machine-Config-Loading
