### ISSUE TITLE
我无法固定小组件

### ISSUE THREAD

**Issue by ChinaIceF** [microsoft/devhome#2032] opened 2023-12-10 03:16 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22635.2850

### Other software

OS Build Version: 10.0.22635.2850.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

打开应用，仪表盘，添加小组件，点击固定后没有任何反应

### Expected result

解决这个问题

### Actual result

如题，无论通过何种途径，我都无法添加小组件

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
Physical Memory: 95.84GB (83.76GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-12-11 18:34
Bing Translate:

I can't pin the widget

Steps to reproduce the bug
Open the app, dashboard, add widget, click pin and nothing happens

Expected result
Fix this

Actual result
As the title suggests, I can't add widgets either way

**Comment by krschau** [comment] 2023-12-11 18:34
I suspect this is a duplicate of #1551

**Closed by krschau** 2023-12-11 18:34 UTC
Labels: Issue-Bug, Needs-Triage
