### ISSUE TITLE
GitHub Add Account not open any browser

### ISSUE THREAD

**Issue by ImBIOS** [microsoft/devhome#2034] opened 2023-12-10 05:16 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

I just try to add my first githubb account

### Expected result

a browser or tab opened with GitHub auth page

### Actual result

nothing happen, no browser opened, no new tabs.

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Physical Memory: 15.79GB (8.11GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeAzureExtension_0.200.323.0_x64__8wekyb3d8bbwe

**Comment by sekanbas** [comment] 2023-12-10 16:46
I am having the same problem

**Comment by krschau** [comment] 2023-12-11 18:35
Duplicate of https://github.com/microsoft/devhomegithubextension/issues/108

**Closed by krschau** 2023-12-11 18:35 UTC
Labels: Issue-Bug, Needs-Triage
