### ISSUE TITLE
Dev Drive w/ WSL Integration

### ISSUE THREAD

**Issue by lasersPew** [microsoft/devhome#1771] opened 2023-10-28 13:38 UTC
### Suggested new feature or improvement

Heya! WSL is a nice addition to my workflow alongside Dev Home. Yet, this is one of the thing specific to Dev Home I somehow would love to have.

I know this is already a feature esp in Windows though I would love for it to be accessible and editable in WSL2. I tried mounting things and I always get read-only errors when I edit or use git.

### Scenario

This feature would be very useful especially if you've came from `Machine Configuration page` as it would greatly speedup the development process.

**Comment by krschau** [comment] 2023-10-30 15:18
Duplicate of #748

**Closed by krschau** 2023-10-30 15:18 UTC
Labels: Issue-Feature, Needs-Triage
