### ISSUE TITLE
Multiple GitHub accounts failing

### ISSUE THREAD

**Issue by twg-dn** [microsoft/devhome#1660] opened 2023-10-06 09:40 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

I have 2 edge browsers with different profiles. Both have different GitHub accounts signed in. 
I click add account and it opened 1 of the profiles and I added successfully.
I opened the next browser so it loads the other profile.
I click add account in dev home.
Broswer opens and I log in

### Expected result

Account to be added

### Actual result

Something went wrong. consider sending feedback screen :) 

### Included System Information

Physical Memory: 31.68GB (18.43GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe

**Comment by mikebattista** [comment] 2023-10-06 16:41
Duplicate of #918 

Multiple GitHub accounts is not yet supported but is something we intend to support in the future pending some improvements in GitHub itself.

**Closed by mikebattista** 2023-10-06 16:41 UTC
Labels: Issue-Bug, Needs-Triage
