### ISSUE TITLE
Accounts (as administrator)

### ISSUE THREAD

**Issue by RAASORG** [microsoft/devhome#1279] opened 2023-07-12 20:40 UTC
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Abrir Dev Home
Abrir configuración de Dev Home
Seleccionar cuentas

### Expected result

Abrir la configuración de Cuentas

### Actual result

Se cierra el proceso. Esto solo sucede si ejecuto Dev Home como administrador

### Included System Information

Physical Memory: 7.35GB (3.02GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-07-12 21:46
Bing Translate:

**Title**
Accounts (as administrator)

**Steps to reproduce the bug**
Open Dev Home
Open Dev Home Settings
Select accounts

**Expected result**
Open Accounts settings

**Actual result**
The process closes. This only happens if I run Dev Home as an administrator

**Comment by vmsaif** [comment] 2023-09-30 05:23
In my case, it crashes either admin or non-admin mode. 

Microsoft Windows [Version 10.0.22621.2361]

**Comment by krschau** [comment] 2023-10-18 16:49
Duplicate of #1634

**Closed by krschau** 2023-10-18 16:49 UTC
Labels: Issue-Bug, Severity-Crash, Area-Account-Sign-In
