### ISSUE TITLE
Dev Drive creation should be managed in the Dev Home app

### ISSUE THREAD

**Issue by Georgios1999** [microsoft/devhome#1613] opened 2023-09-28 10:47 UTC
### Suggested new feature or improvement

When choosing to create a Dev Drive in the Clone Repository window in the initial setup of Dev Home, make it so that it does not redirect the user to Settings. Instead, the user should be able to set it up in Dev Home and manage it later in Settings. Or if that is not possible, make it so that Dev Home, automatically detects when a Dev Drive is created and automatically sets the Clone Location when Cloning a repository to that Drive

### Scenario

Switching to settings to complete the setup is confusing because you do not know if Dev Home recognizes it is done, and you might have to redo the setup

**Comment by bbonaby** [comment] 2023-09-29 07:22
Hi @Georgios1999 I believe you're talking about the 'Create dev drive' button in the setup flow main page that launches the settings app. While we are in the process of rethinking this and understand this feedback. You can actually create a Dev Drive from within the setup flow by either going into the end to end setup, or the clone repository page. Within that page, once you select the 'Add Repository' button there should be a checkbox in the dialog that will allow you to create a new Dev Drive from Dev Home. During the actual setup we'll create the Dev Drive first and then clone your repositories onto the Dev Drive.

Also, about your second comment about Dev Home automatically detecting that you have Dev Drive created and then defaulting to it as the clone location for your repositories. This feature is already in Dev Home today and once a Dev Drive is created either through the Windows settings app or through Dev Home, it will be the default path in the clone repository page. The next time you enter the clone repository page and select the 'Add Repository' button

**Comment by Georgios1999** [comment] 2023-09-30 10:14
Hi @bbonaby! Glad to hear you are aware of this and that you are working on it. I already see improvements in Dev Home. Thanks for replying! Should I close the issue now?

**Comment by krschau** [comment] 2023-10-16 19:36
Hey @Georgios1999! I'm going to mark this as a duplicate of another issue, which will close it, but it will also raise awareness over on that issue. Feel free to 👍 it as well.

**Closed** 2023-10-16 19:36 UTC
Labels: Issue-Feature, Needs-Triage
