### ISSUE TITLE
[Arm64][Widgets] Unable to use Core Widgets on Arm64 due to bug in System.Management.dll

### ISSUE THREAD

**Issue by snickler** [microsoft/devhome#865] opened 2023-05-25 17:12 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.25357.1

### Steps to reproduce the bug

- Install Dev Home from Winget or Store
- Add any of the Core Widgets like GPU, CPU or Memory
- Note a "This widget could not be displayed" message in the pinned widget

### Expected result

Data read from the Core Widgets to be displayed.

### Actual result

![image](https://github.com/microsoft/devhome/assets/4016293/5b2deec7-cbad-466a-ba9f-43d297fd35a8)

```
Application: CoreWidgetProvider.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.ManagementPath' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (193): Failed to load required native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type type)
   at System.Management.ManagementPath.CreateWbemPath(String path)
   at System.Management.ManagementPath..cctor()
   --- End of inner exception stack trace ---
   at System.Management.ManagementScope._Clone(ManagementScope scope, IdentifierChangedEventHandler handler)
   at System.Management.ManagementObjectSearcher..ctor(ManagementScope scope, ObjectQuery query, EnumerationOptions options)

```

Some quick searching on this particular problem led me to a commit that fixes this bug in the .NET 8 Preview 4 version of the System.Management NuGet package

https://github.com/dotnet/runtime/commit/258b44f656e8c018fec46cce7b374e2d2c9af819

### Included System Information

Surface Pro X
Windows 11 Canary 10.0.25357.1

**Comment by snickler** [comment] 2023-05-25 17:17
Oops, this is a dup of #855 . I've added the culprit in my details.

**Comment by krschau** [comment] 2023-05-30 17:39
Duplicate of #855

**Closed by krschau** 2023-05-30 17:39 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Triage
