### ISSUE TITLE
Cannot view system widgets

### ISSUE THREAD

**Issue by GGProGaming** [microsoft/devhome#1637] opened 2023-10-01 22:27 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.23550.1000

### Other software

OS Build Version: 10.0.23550.1000.amd64fre.ni_prerelease.230915-1324
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

Try to add system widget

### Expected result

Widgets show the proper data

### Actual result

Everything shows as {example} (example) and when you try to add more, it doesn't show a preview and says it can't add it. 

### Included System Information

Physical Memory: 63.73GB (44.34GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.501.261.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-10-16 19:33
Duplicate of #1248

**Closed by krschau** 2023-10-16 19:33 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Triage
