### ISSUE TITLE
Some widgets disappear from the dashboard after a reboot

### ISSUE THREAD

**Issue by infinitepower18** [microsoft/devhome#983] opened 2023-05-31 16:01 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Every time I reboot my PC (or shut down and turn the PC on again), some of the widgets disappear from the dashboard. Sometimes it removes all the widgets from the dashboard.

### Expected result

The widgets should not be removed from the dashboard after a reboot.

### Actual result

Some widgets get randomly removed after a reboot.

### Included System Information

CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
Physical Memory: 15.83GB (8.19GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-31 17:03
Duplicate of #742

**Closed as completed by krschau** 2023-05-31 17:03 UTC
Labels: Issue-Bug, Resolution-Duplicate, Area-Dashboard
