### ISSUE TITLE
Incongruence Color Switching from Dark to Light Theme

### ISSUE THREAD

**Issue by Gabryx360** [microsoft/devhome#1884] opened 2023-11-12 17:35 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2338

### Other software

OS Build Version: 10.0.22631.2338.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

• Open the app
• Tap on Settings
• Tap on Theme Preferences
• Tap on Accordion and select the Light theme

### Expected result

I expect every section of the app, text and screen, to be consistent with the theme set

### Actual result

The app doesn't apply the light theme evenly. 
It is impossible to read the text in the left sidebar.

![image](https://github.com/microsoft/devhome/assets/92781286/dfd09843-d154-4998-90cc-1d51e467bc29)

### Included System Information

Physical Memory: 5.88GB (2.14GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-13 20:48
Duplicate of #993

**Closed** 2023-11-13 20:48 UTC
Labels: Issue-Bug, Needs-Triage, Type-Style, Area-Core
