### ISSUE TITLE
WSL distro/app installation

### ISSUE THREAD

**Issue by pgarcia002** [microsoft/devhome#967] opened 2023-05-30 22:19 UTC
### Suggested new feature or improvement

In the application installation process, it should enable a user to install WSL (or even chose a distro as well).

### Scenario

With WSL being a large aspect of Windows development, it would be super useful to have that kind of support + integration with this app.

**Comment by krschau** [comment] 2023-05-31 13:25
Duplicate of #748

**Closed by krschau** 2023-05-31 13:25 UTC
Labels: Issue-Feature, Needs-Triage
