### ISSUE TITLE
自定义安装应用程序路径

### ISSUE THREAD

**Issue by ChenKangluit** [microsoft/devhome#3964] opened 2024-11-01 14:20 UTC
### Suggested new feature or improvement

自定义安装应用程序路径

### Scenario

加个可选安装程序路径功能很简单吧

**Comment by krschau** [comment] 2024-11-05 19:59
Bing translate:

Custom install app path #3964
Customize the path to install the application
It's easy to add an optional installer path

**Comment by krschau** [comment] 2024-11-05 20:00
Duplicate of #2956

**Closed by krschau** 2024-11-05 20:00 UTC
Labels: Issue-Feature, Needs-Triage
