### ISSUE TITLE
Dev Home crashes after pinning a widget

### ISSUE THREAD

**Issue by Georgios1999** [microsoft/devhome#1197] opened 2023-06-23 19:36 UTC
### Dev Home version

0.200.170.0

### Windows build number

10.0.23481.1000

### Other software

OS Build Version: 10.0.23481.1000.amd64fre.ni_prerelease.230609-1655
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open Dev Home, and select any widget to pin to the Dashboard (in my case, it was Network, and GPU, which both resulted in a crash). Also, while navigating back to the Dashboard tab, the app once again crashes

### Expected result

The widgets get pinned

### Actual result

The app suddently closes. Good news though! When I open it again, the widgets are actually pinned in the Dashboard

### Included System Information

Physical Memory: 63.92GB (54.97GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-23 19:55
Duplicate of #745

**Closed by krschau** 2023-06-23 19:55 UTC
Labels: Issue-Bug, Needs-Triage
