### ISSUE TITLE
Fix build issues in SamplePlugin solution

### ISSUE THREAD

**Issue by adrastogi** [microsoft/devhome#1377] opened 2023-08-07 18:18 UTC
### Dev Home version

N/A

### Windows build number

Microsoft Windows [Version 10.0.23522.1000]

### Steps to reproduce the bug

1. Create a clone of the repository.
2. Navigate to the `SamplePlugin` folder at the root of the repository and open the `SamplePlugin.sln`. 
3. Build the solution (e.g., Ctrl+Shift+B or right-clicking the solution and selecting Build).

### Expected result

The solution builds cleanly. 

### Actual result

The user hits an error first with a Dev Home SDK DLL not being found (which can be remediated by building that project under the PluginSDK folder of the solution (sorry, didn't note the exact specifics here when I was going through the scenario)).

After that error is resolved, there are a longer list that are (likely) due to interface breaking changes or additions that haven't been reflected in the sample code. 

(Are the samples compiled as part of the build? If not, might be a useful thing to do- if desired, I can file a separate issue to track that idea.)

Snippet from the build log:

```
1>Build FAILED.
1>
1>C:\Users\UserName\source\repos\devhome\SamplePlugin\DevIDProvider.cs(15,32,15,46): error CS0246: The type or namespace name 'IDevIdProvider' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\UserName\source\repos\devhome\SamplePlugin\DevIDProvider.cs(43,35,43,49): error CS0246: The type or namespace name 'IDevIdProvider' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\UserName\source\repos\devhome\SamplePlugin\DevIDProvider.cs(43,35,43,49): error CS0538: 'IDevIdProvider' in explicit interface declaration is not an interface
1>C:\Users\UserName\source\repos\devhome\SamplePlugin\RepositoryProvider.cs(13,37,13,56): error CS0535: 'RepositoryProvider' does not implement interface member 'IRepositoryProvider.ParseRepositoryFromUrlAsync(Uri)'
1>C:\Users\UserName\source\repos\devhome\SamplePlugin\RepositoryProvider.cs(13,37,13,56): error CS0535: 'RepositoryProvider' does not implement interface member 'IRepositoryProvider.DisplayName'
```

**Comment by EricJohnson327** [comment] 2023-08-14 21:02
This is getting fixed after the SDK changes go through: https://github.com/microsoft/devhome/pull/337

**Comment by krschau** [comment] 2024-08-21 13:46
Duplicate of #3650

**Closed by krschau** 2024-08-21 13:46 UTC
Labels: Issue-Bug, Area-Build, Priority-2
