### ISSUE TITLE
The pop-up's mask when Dev Home links GitHub account cannot cover the title bar

### ISSUE THREAD

**Issue by LiCaoZ** [microsoft/devhome#1247] opened 2023-07-01 11:52 UTC
### Dev Home version

0.200.170.0

### Windows build number

10.0.23493.1000

### Other software

OS Build Version: 10.0.23493.1000.amd64fre.ni_prerelease.230624-1828
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

*Dev Home - Settings - Account - Add account*

![image](https://github.com/microsoft/devhome/assets/67832651/a27ae073-9a5b-4521-bb32-f4cb63071ce2)

### Expected result

The mask should cover all the window, including the title bar.

### Actual result

As the screenshot shows, the mask doesn't cover the title bar.

![image](https://github.com/microsoft/devhome/assets/67832651/a27ae073-9a5b-4521-bb32-f4cb63071ce2)

### Included System Information

Physical Memory: 11.89GB (2.67GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions:
Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-07-05 14:10
Duplicate of #583

**Closed by krschau** 2023-07-05 14:10 UTC
Labels: Issue-Bug, Needs-Triage
