### ISSUE TITLE
The widget automatically deleted after restart/shut down

### ISSUE THREAD

**Issue by FakhriF** [microsoft/devhome#848] opened 2023-05-25 09:38 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.25370.1

### Other software

OS Build Version: 10.0.25370.1.amd64fre.zn_release.230516-0802
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I pin the "widget" like RAM, GPU, etc. But it was deleted automatically after I restart the laptop. So when I open this app again, I must pin again those "widget".

### Expected result

The "widget" always saved even the laptop restart, shut down, etc. So I don't need to pin again.

### Actual result

The widget is lost/"deleted". So, I need to pin it again.

### Included System Information

CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
Physical Memory: 9.95GB (5.31GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-25 13:46
Duplicate of #742

**Closed by krschau** 2023-05-25 13:46 UTC
Labels: Issue-Bug, Needs-Triage
