### ISSUE TITLE
Cross button not working of Add Widget Screen.

### ISSUE THREAD

**Issue by DevOpRohan** [microsoft/devhome#746] opened 2023-05-23 20:35 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

1. Click on dashboard
2. Add a new widget
3. Click on core
4. Click on GPU
5. Click on Cross button, It isn't working

### Expected result

I don't want to add the gpu widget, but it wasn't working. So, It forced me to add an widget

### Actual result

It should just close that scree, instead it make the whole window smaller

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical Memory: 15.75GB (9.27GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-05-23 21:44
@DevOpRohan Are you seeing this all the time, or only when the window size is such that the X button is on top of the title bar? We have this issue open, which I think is what you're probably seeing: #537

**Comment by DevOpRohan** [comment] 2023-05-23 21:57
> @DevOpRohan Are you seeing this all the time, or only when the window size is such that the X button is on top of the title bar? We have this issue open, which I think is what you're probably seeing: #537

All the time, even windows is in full screen mode.

And in small window, the top portion of add widget(isn't visible)

**Comment by krschau** [comment] 2023-05-23 22:04
The issue when the window is small is basically the same as #584.

Could I please see a screenshot of an instance where clicking the X button won't close the Add Widget dialog?
When you hover over the X, does the button change color?
You said this:
>It should just close that scree, instead it make the whole window smaller

Can you elaborate on that?

**Comment by DevOpRohan** [comment] 2023-05-24 19:42
1.
![image](https://github.com/microsoft/devhome/assets/86923317/3092bc27-ac9f-4804-ac81-fd3d77af3917)

2: Single click on X doesn't working

3. Double click on X result into this:
![image](https://github.com/microsoft/devhome/assets/86923317/e55de5e4-5229-4652-9730-473eb83a67f7)

**Comment by krschau** [comment] 2023-05-24 21:04
@DevOpRohan Thanks for the screenshots. It looks like this is indeed a duplicate of #537. You can see the X is over the title bar.

Please excuse my bad drawing:
![image](https://github.com/microsoft/devhome/assets/47155823/93d05baf-d382-4c58-8a21-697ba3d60610)
The title bar is the area above the blue line, the X button highlighted in yellow is on top of it.

Thanks for bringing up that this is a big problem on your screen size.

**Comment by krschau** [comment] 2023-05-24 21:04
Duplicate of #537

**Closed by krschau** 2023-05-24 21:04 UTC
Labels: Issue-Bug, Area-Dashboard, Needs-Triage, Needs-Team-Response
