### ISSUE TITLE
[Environments reliability] Dev Box operations: Error retrieving adaptive card on Dev Box creation

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#3408] opened 2024-07-11 09:24 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3737

### Other software

OS Build Version: 10.0.22631.3737.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Go to environment and create a new Dev Box.

### Expected result

Proceed on with Dev Box creation.

### Actual result

Error retrieving adaptive card. 
![Screenshot 2024-07-11 022011](https://github.com/microsoft/devhome/assets/65691598/3fa537fc-871f-4389-a2dc-0e357d682b3d)

Logs here

[2024/07/11 02:19:34.841 INF] (AzureExtension) Launched with args: -RegisterProcessAsComServer -Embedding
[2024/07/11 02:19:34.886 INF] (AzureExtension) MicrosoftWindows.Client.WebExperience_524.13200.30.0_x64__cw5n1h2txyewy  DevMode: False  Signature: Store
[2024/07/11 02:19:34.887 INF] (AzureExtension) Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe  DevMode: False  Signature: Store
[2024/07/11 02:19:34.888 INF] (AzureExtension) Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe  DevMode: False  Signature: Store
[2024/07/11 02:19:34.926 INF] (AzureExtension) Activating COM Server
[2024/07/11 02:19:35.014 INF] (AzureExtension) Services Host creation successful
[2024/07/11 02:19:38.187 INF] (DevBoxProvider) Attempting to create adaptive card session for 
[2024/07/11 02:19:38.187 INF] (DevBoxProvider) No cached Dev Boxes found for , getting new Dev Boxes
[2024/07/11 02:19:38.194 INF] (DevBoxProvider) Attempting to get all projects for 
[2024/07/11 02:19:38.210 INF] (AuthenticationHelper) ObtainTokenForLoggedInDeveloperAccount
[2024/07/11 02:19:38.221 INF] (System.Net.Http.HttpClient.Default.LogicalHandler) Start processing HTTP request POST https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01
[2024/07/11 02:19:38.222 INF] (System.Net.Http.HttpClient.Default.ClientHandler) Sending HTTP request POST https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01
[2024/07/11 02:19:38.339 ERR] (DevBoxManagementService) DevBoxHttpRequest failed: Exception
System.Net.Http.HttpRequestException: No such host is known. (management.azure.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs, ValueTask, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at AzureExtension.Services.DevBox.DevBoxManagementService.DevBoxHttpRequest(HttpClient client, Uri webUri, IDeveloperId developerId, HttpMethod method, HttpContent requestContent)
[2024/07/11 02:19:38.346 ERR] (DevBoxProvider) Unable to get the adaptive card session for the provided developerId
System.Net.Http.HttpRequestException: No such host is known. (management.azure.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError, CancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs, ValueTask, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String, Int32, HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage, HttpCompletionOption, CancellationTokenSource, Boolean, CancellationTokenSource, CancellationToken)
   at AzureExtension.Services.DevBox.DevBoxManagementService.DevBoxHttpRequest(HttpClient client, Uri webUri, IDeveloperId developerId, HttpMethod method, HttpContent requestContent)
   at AzureExtension.Services.DevBox.DevBoxManagementService.HttpsRequestToManagementPlane(Uri webUri, IDeveloperId developerId, HttpMethod method, HttpContent requestContent)
   at AzureExtension.DevBox.DevBoxProvider.GetDevBoxProjectsAsync(IDeveloperId developerId)
   at AzureExtension.DevBox.DevBoxProvider.GetDevBoxesAsync(IDeveloperId developerId)
   at AzureExtension.DevBox.DevBoxProvider.<>c__DisplayClass22_0.<<CreateAdaptiveCardSessionForDeveloperId>b__0>d.MoveNext()
[2024/07/11 02:19:44.167 INF] (AuthenticationHelper) Azure SSO failed with exception:MSAL.NetCore.4.56.0.0.MsalServiceException: 
	ErrorCode: 3399942148
Microsoft.Identity.Client.MsalServiceException: WAM Error  
 Error Code: 3399942148 
 Error Message: NoNetwork 
 WAM Error Message: (pii) 
 Internal Error Code: 557973641 
 Possible cause: no Internet connection 
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken )
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters, AcquireTokenSilentParameters, CancellationToken)
   at DevHomeAzureExtension.DeveloperId.AuthenticationHelper.AcquireWindowsAccountTokenSilently(String[] scopes)
	StatusCode: 0 
	ResponseBody:  
	Headers: 

### Included System Information

CPU: Intel(R) Core(TM) i9-14900HX
Physical Memory: 31.71GB (19.2GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.30.0_x64__cw5n1h2txyewy

**Comment by bbonaby** [comment] 2024-08-21 19:10
@jiayac  Can you confirm is this is still happening? Do you know if you had multiple accounts logged in at the same time? E.g your work account and your personal MSA?

**Comment by huzaifa-d** [comment] 2024-08-22 17:25
Closing as duplicate of #3677 , which has better repro steps

**Closed by huzaifa-d** 2024-08-22 17:25 UTC
Labels: Issue-Bug, Priority-1, Area-Environments
