### ISSUE TITLE
WSL in Machine Configuration

### ISSUE THREAD

**Issue by lasersPew** [microsoft/devhome#1772] opened 2023-10-28 13:39 UTC
### Suggested new feature or improvement

Heya! WSL is a nice addition to my workflow alongside Dev Home. Yet, this is one of the thing specific to Dev Home I somehow would love to have.

WSL is one of the very heart of most of the projects I do. Often times, when I start to develop something, I take a very long time to pick a distribution that are compatible to the project I'm doing and another for installing that selected distribution. For this, I would want to have a page where I can choose which distribution and version I would like to use. This may be the latest up to the last supported version including 1 or 2 deprecated versions, as some projects don't work on supported versions, especially legacy applications. For the sake of clarity, I would love to have it but behind a `Unsupported Versions` button. One thing you may use as an inspiration is [bostrot's wsl2-distro-manager](https://github.com/bostrot/wsl2-distro-manager).

### Scenario

This feature would be very useful especially in `Machine Configuration` page as it would greatly speedup the development process.

### Additional details

WSL may be integrated by making it an extension.

**Comment by krschau** [comment] 2023-10-30 15:23
Hi @lasersPew. I'm duping both the WSL feature requests to the main issue that we're using to track the WSL asks, since (as the automated blurb says) it is genuinely easier for us to make sure we're seeing everyone's suggestions if they're all in one place. I understand that the two issues you opened are requesting different things, and I hope you put those suggestions over in that issue.

**Comment by krschau** [comment] 2023-10-30 15:23
Duplicate of #748

**Closed by krschau** 2023-10-30 15:23 UTC
Labels: Issue-Feature, Needs-Triage
