### ISSUE TITLE
[Dashboard][Feature request] Turning off extensions should make widget disappear (or something) and not be able to be added

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#1892] opened 2023-05-18 01:07 UTC
### Steps to reproduce the bug

Description
1. have widgets on dashboard
2. turn off GitHub ext
3. widgets remain on
4. click "Add" and they still are able to be added

widgets shouldn't be present as Dev Home shouldn't 'see' the extension anymore

This is a complicated problem, and unlikely to make it for Build. We want users to know that we know that it's a problem, so we can create a public GitHub issue for it right when we release.

Can we have PM decide on functionality here? (And it's a big enough decision I think it should be documented.) The suggestion in this bug is not inherently correct (even if we decide it's the functionality we want). DevHome knows about these widgets because the extension registered the widgets with the widget platform. It has nothing to do with the extension's communication with the core app.

If you decide to do this, it severely limits third party widgets in the future. You'd be saying "to have a widget in DevHome, you have to write a DevHome extension". You couldn't write your own app and have DevHome display your widget. Obviously made up example, but if we weren't doing our own ADO widgets, ADO could never write a native client that included a widget used in DevHome. They'd HAVE to also write an extension.

**Comment by krschau** [comment] 2023-11-14 21:55
Related but not dupe of #1390

**Comment by krschau** [comment] 2024-07-11 19:07
Duplicate of #3252

**Closed by krschau** 2024-07-11 19:07 UTC
Labels: Issue-Feature, Area-Extensibility, Priority-1
