### ISSUE TITLE
Resizing Parent Window Affects Modal Dialog Control Button

### ISSUE THREAD

**Issue by RandomHandle** [microsoft/devhome#1641] opened 2023-10-02 13:44 UTC
### Dev Home version

0.503.261.0

### Windows build number

10.0.22621.2361

### Other software

OS Build Version: 10.0.22621.2361.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.21

### Steps to reproduce the bug

1. Navigate to the Dashboard in Dev Home (Preview)
2. Maximise the window using the window control buttons (top right)
3. Select 'Add Widget' button (or 'Add New Widget' link if no widgets are currently added)
4. Click the 'restore/maximise' window control button again and resize the parent window so that the modal takes up the entire vertical space of the parent window.

### Expected result

The window control button 'X' to close the modal dialog should work regardless of parent window size.

### Actual result

The modal cannot be closed using the 'X'. The parent window must be enlarged enough until the modal does not take up all the vertical space, then the modal can be closed.

### Included System Information

Physical Memory: 31.72GB (19.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.503.261.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-10-02 16:32
Duplicate of #537

**Closed by krschau** 2023-10-02 16:32 UTC
Labels: Issue-Bug, Needs-Triage
