### ISSUE TITLE
Connecting Account

### ISSUE THREAD

**Issue by Hyuria** [microsoft/devhome#936] opened 2023-05-29 15:13 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Attempt to connect to GitHub account

### Expected result

Expect browser to open to sign in to Github

### Actual result

Nothing happens, popup is waiting for browser to open

### Included System Information

CPU: AMD Ryzen 9 5900X 12-Core Processor            
Physical Memory: 31.92GB (24.52GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by manodasanW** [comment] 2023-05-30 23:31
@Hyuria Can you confirm whether on the popup you are seeing the message saying _Waiting for browser_.  From what you mention under _Actual Result_, I believe that is the case, but wanted to confirm as we have another similar issue that folks are hitting where they don't see that message and instead remain on the Sign in dialog.

Also, can you confirm what you default browser is and if one is set?

**Comment by Georgios1999** [comment] 2023-06-23 13:16
Hi @Hyuria ! When signing in to GitHub (at least, that is what's happening on me), the browser doesn't open on the **foreground** and instead opens in the _background_. Try looking for any flashing apps in the Taskbar when trying to sign in to GitHub. You can even try opening the web browser manually.

**Comment by vineeththomasalex** [comment] 2023-10-13 22:03
This is either what @Georgios1999 described or a dupe of #1544

**Closed by vineeththomasalex** 2023-10-13 22:03 UTC
Labels: Issue-Bug, Resolution-Duplicate, Priority-1, Area-Account-Sign-In
