### ISSUE TITLE
Excessive top margin space on page headers

### ISSUE THREAD

**Issue by mathewleeza** [microsoft/devhome#592] opened 2023-05-18 23:24 UTC
### Steps to reproduce the bug

Description

**Comment by crutkas** [comment] 2023-07-12 21:35
this is larger than just summary, this is just across most things, this doesn't need design as this is stock app design guidelines.
![image](https://github.com/microsoft/devhome/assets/1462282/09015bf2-7746-4cff-ab6d-f8e201540349)

**Comment by krschau** [comment] 2023-08-17 16:20
Duplicate of #869

**Closed by krschau** 2023-08-17 16:20 UTC
Labels: Issue-Task, Area-Style
