### ISSUE TITLE
Create configuration File

### ISSUE THREAD

**Issue by jvruas** [microsoft/devhome#1252] opened 2023-07-05 15:03 UTC
### Suggested new feature or improvement

Create a YAML file selecting apps installed in the current system.

### Scenario

Configure one pc, copy the configuration and use that configuration file in several computers.

**Comment by cinnamon-msft** [comment] 2023-07-05 21:56
Looks like this is a duplicate of #876 :)

**Closed by cinnamon-msft** 2023-07-05 21:56 UTC
Labels: Issue-Feature, Needs-Triage
