### ISSUE TITLE
Uninstalling a widget should uninstall the widget, not send me to "Installed apps"

### ISSUE THREAD

**Issue by timkur** [microsoft/devhome#2866] opened 2024-05-10 18:34 UTC
### Dev Home version

0.1401.495

### Windows build number

10.0.22621.3527

### Steps to reproduce the bug

In the extensions page, click to uninstall a widget

![image](https://github.com/microsoft/devhome/assets/49733346/ba0b4c1c-27fe-439c-b7fb-0a5e30103347)

### Expected result

The widget gets uninstalled

### Actual result

I'm sent to the Installed Apps page in Windows Settings where I need to go find the extension in that list to initiate the uninstall.

**Comment by krschau** [comment] 2024-05-10 19:18
Duplicate of #2386

**Closed** 2024-05-10 19:18 UTC
Labels: Issue-Bug
