### ISSUE TITLE
Widgets issue

### ISSUE THREAD

**Issue by sibex** [microsoft/devhome#3842] opened 2024-09-12 09:22 UTC
### Dev Home version

0.1701.597.0

### Windows build number

10.0.22631.4169

### Other software

OS Build Version: 10.0.22631.4169.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.7

### Steps to reproduce the bug

Just open Dev Home app

### Expected result

Installed widgets displayed on dashboard

### Actual result

No widgets displayed on dashboard, error message displayed instead

### Included System Information

CPU: AMD Ryzen 7 5800H with Radeon Graphics         
Physical Memory: 13.86GB (6.33GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.6.1.0_x64__g91dtg5srk15g (Widgets for UniGetUI (formerly WingetUI))
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHome_0.1701.597.0_x64__8wekyb3d8bbwe (Git)
Microsoft.Windows.DevHomeGitHubExtension_0.1700.597.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.23700.10.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-09-13 16:14
Duplicate of #2945

Please try this workaround while we work on the issue:
A workaround for this particular error is to go to the Windows Widget Board (keyboard shortcut: win+w) and click the + button to add a widget. You don't actually have to add one, but bringing up the dialog gets things started such that Dev Home should be back to normal.

**Closed by krschau** 2024-09-13 16:14 UTC
Labels: Issue-Bug, Needs-Triage
