### ISSUE TITLE
Dev Box Pool list not alphabetized

### ISSUE THREAD

**Issue by acangialosi** [microsoft/devhome#3592] opened 2024-08-12 23:46 UTC
### Dev Home version

0.1601.561.0

### Windows build number

10.0.22635.4010

### Other software

OS Build Version: 10.0.22635.4010.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.6

### Steps to reproduce the bug

Click create environment list
Expand project list 

### Expected result

Alphabetical list

### Actual result

Not an alphabetical list
![image](https://github.com/user-attachments/assets/53064c43-2499-4456-a010-d82cc83ab0d3)

### Included System Information

CPU: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
Physical Memory: 31.6GB (14.35GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome.Canary_0.1401.500.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeAzureExtension.Canary_0.1000.549.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Canary))
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHome_0.1601.561.0_x64__8wekyb3d8bbwe (Windows Subsystem for Linux Extension)
Microsoft.Windows.DevHomeAzureExtension_0.1100.561.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.21802.0.0_x64__cw5n1h2txyewy

**Comment by bbonaby** [comment] 2024-08-13 17:41
Hi @acangialosi, I just tested out the latest version of Dev Home: ver 0.1601.561.0 and the Azure extension ver: 0.1100.561.0. I confirmed that the pools were sorted. Can you confirm that you're using these version only? By the looks of the extensions you have installed you still have the old Canary versions and they may still be enabled. You can either uninstall them or disable them.

Let me know if the issue is resolved. This should be fixed as of the last release of the Azure extension last month, I confirmed that both my projects list and pools list are both sorted when I use those two above versions of the apps

**Comment by huzaifa-d** [comment] 2024-09-04 18:42
Reconfirmed on the latest version of Dev Home; this has been fixed. 
Please reopen if needed with additional details.

**Comment by huzaifa-d** [comment] 2024-09-04 20:37
Closed by mistake.

**Closed** 2024-09-04 21:44 UTC
Labels: Issue-Bug, Priority-3, Area-Environments
