### ISSUE TITLE
Add more than one GitHub Account

### ISSUE THREAD

**Issue by prateekch33** [microsoft/devhome#1043] opened 2023-06-04 02:18 UTC
### Suggested new feature or improvement

Option to add more than 1 GitHub Account to the Dev Home

### Scenario

I have 2 GitHub accounts one is my personal and one I used for my organization. Currently, I cannot clone my organizational repository to work on my system using dev home. I must do it manually and also, I am not able to use widgets for the same so that I can be able to monitor the things

**Comment by mikebattista** [comment] 2023-06-04 18:55
Duplicate of #918

**Closed by mikebattista** 2023-06-04 18:55 UTC
Labels: Issue-Feature, Needs-Triage
