### ISSUE TITLE
Pinned widgets are reset everytime

### ISSUE THREAD

**Issue by barinbritva** [microsoft/devhome#1381] opened 2023-08-09 15:38 UTC
### Dev Home version

0.301.198.0

### Windows build number

10.0.22621.2134

### Other software

OS Build Version: 10.0.22621.2134.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

Set up widgets, reload a PC, open Dev Home app.

### Expected result

I open Dev Home and see the widgets I set up last time

### Actual result

There is no pinned widgets

### Included System Information

Physical Memory: 31.84GB (14.03GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.300.198.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-08-09 17:27
Duplicate of #742

**Closed by krschau** 2023-08-09 17:27 UTC
Labels: Issue-Bug, Needs-Triage
