### ISSUE TITLE
Using CPU for no reason

### ISSUE THREAD

**Issue by simeyla** [microsoft/devhome#2499] opened 2024-04-01 06:44 UTC
### Dev Home version

0.1201.442.0

### Windows build number

10.0.22631.3374

### Other software

OS Build Version: 10.0.22631.3374.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

I looked at Dev Home several hours ago. 
It isn't even open now but it's showing 8% CPU usage.
This is on a brand new install on a Meteor Lake Ultra Core 9
8% CPU usage is unacceptable.

### Expected result

Not using CPU when it isn't even open

### Actual result

It was using CPU for no reason

I'm uninstalling it. You had your chance. yes I know it;'s a preview but it didn't seem to do anything useful anyway

### Included System Information

CPU: Intel(R) Core(TM) Ultra 9 185H
Physical Memory: 95.67GB (64.51GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.1201.442.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1200.442.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_424.1301.450.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-04-01 13:29
Duplicate of #1335

**Closed by krschau** 2024-04-01 13:29 UTC
Labels: Issue-Bug, Needs-Triage
