### ISSUE TITLE
Error al clonar repositorio

### ISSUE THREAD

**Issue by walthercurodelacruz** [microsoft/devhome#1757] opened 2023-10-25 15:18 UTC
### Dev Home version

0.601.285.0

### Windows build number

10.0.22621.2428

### Other software

OS Build Version: 10.0.22621.2428.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.22

### Steps to reproduce the bug

Ingresar en la opción clonar repositorio.
Escoger URL
Se clonará el repositorio pero luego ya no se puede acceder a el (Como si nunca lo hubiera clonado)

### Expected result

Tener una lista o dashboard donde se pudieran ver los repositorios clonados

### Actual result

Nunca pude encontrar los repositorios agregados.

### Included System Information

Physical Memory: 11.73GB (2.72GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.285.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-10-25 20:18
Bing translate:

Steps to reproduce the bug

Enter the clone repository option.
Choose URL
The repository will be cloned but then no longer accessible (as if you never cloned it)

Expected result
Have a list or dashboard where you can see the cloned repositories

Actual result
I was never able to find the added repositories.

**Comment by krschau** [comment] 2023-10-25 20:19
Duplicate of #702

**Closed by krschau** 2023-10-25 20:19 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by krschau** [comment] 2023-10-25 20:20
You should check out this change, which I think provides the functionality you're looking for: #1049
