### ISSUE TITLE
Ability to import local repositories

### ISSUE THREAD

**Issue by bstordrup** [microsoft/devhome#780] opened 2023-05-24 08:59 UTC
### Suggested new feature or improvement

On a machine that is already being used as development machine, it seems not possible to find and use your **existing** repositories that are already linked with remotes.

This one makes me believe that I'm about to clone a repository into the mentioned local folder
![image](https://github.com/microsoft/devhome/assets/43523397/c6c1cfb6-dfbe-4218-bd03-ffed6f7d6388)

But that folder is already a clone of the repository! I just want to import the repository so DevHome knows the local repository and the remote connected.

### Scenario

Starting to use DevHome on a machine that is already in use as developer machine with several already existing repositories cloned.

**Comment by bstordrup** [comment] 2023-05-24 19:53
> But when downloading new repos they also don't get added to a list. So there is no use in adding existing ones currently.

I think that is also a big mistake that they are not in a list so you can see what you have cloned.

**Comment by Aaron-Junker** [comment] 2023-05-24 19:55
> > But when downloading new repos they also don't get added to a list. So there is no use in adding existing ones currently.
> 
> I think that is also a big mistake that they are not in a list so you can see what you have cloned.

I think this will come in the future, as  you can see a list of repos in Explorer in the trailer.

**Comment by bstordrup** [comment] 2023-05-24 20:23
> > > But when downloading new repos they also don't get added to a list. So there is no use in adding existing ones currently.
> > 
> > 
> > I think that is also a big mistake that they are not in a list so you can see what you have cloned.
> 
> I think this will come in the future, as you can see a list of repos in Explorer in the trailer.

Guess you would need to prioritize it quite much, as there is three issue threads discussing this.

**Comment by HotCakeX** [comment] 2023-05-25 22:10
I need this too. I have huge repositories already cloned with GitHub desktop. When I clean install Windows, I don't re-downloaded all of my repositories again, GitHub desktop recognizes my locally cloned repositories when I log in to my GitHub account.

I need to be able to do the same in Dev Home.

**Comment by asklar** [comment] 2023-05-27 20:02
Duplicate of #702 (moved the tags to 702 too @cinnamon-msft)

**Comment by asklar** [comment] 2023-05-27 20:02
Duplicate of #702

**Closed by asklar** 2023-05-27 20:02 UTC
Labels: Issue-Feature, Needs-Triage, Area-Repo Management, Needs-Spec
