### ISSUE TITLE
The overlay Windows in light theme does not cover the full title bar 

### ISSUE THREAD

**Issue by ianyyu** [microsoft/devhome#1130] opened 2023-06-12 16:37 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1702

### Other software

OS Build Version: 10.0.22621.1702.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Open any overlay window

### Expected result

the overlay should fully cover the title bar 

### Actual result

![image](https://github.com/microsoft/devhome/assets/50185601/5f965a01-7403-4310-b62a-380bd9092ae8)

### Included System Information

CPU: AMD EPYC 7763 64-Core Processor                
Physical Memory: 15.95GB (7.7GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-12 17:07
Duplicate of #583

**Closed by krschau** 2023-06-12 17:07 UTC
Labels: Issue-Bug, Needs-Triage
