### ISSUE TITLE
Signing in to GitHub account

### ISSUE THREAD

**Issue by Armanj88** [microsoft/devhome#1027] opened 2023-06-02 10:14 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I was in introducing dev home part and tap connect account, and then I tap sign in to GitHub. but nothing happened.

### Expected result

I expected to open a auth page in browser

### Actual result

nothing happened

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical Memory: 7.65GB (0.4GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by joadoumie** [comment] 2023-08-10 22:06
I'm experiencing a similar issue where the sign-in flow that is triggered in this process is lost as an additional tab in one of my various browser instances, so it seems as if nothing is happening.

**Comment by vineeththomasalex** [comment] 2023-10-13 22:00
This is either what @joadoumie described above or a duplicate of #1544 .

**Closed by vineeththomasalex** 2023-10-13 22:00 UTC
Labels: Issue-Bug, Resolution-Duplicate, Priority-1, Area-Account-Sign-In
