### ISSUE TITLE
Clicking "make changes" in Dev Drive Insights causes Dev Home to hang

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#3356] opened 2024-07-03 18:50 UTC
### Dev Home version

0.1501.547.0

### Steps to reproduce the bug

Navigate to Dev Drive Insights
Have a package cache suggestion
Click "Make the change"
Click "Make changes" on the modal
![image](https://github.com/microsoft/devhome/assets/48369326/94c62d0c-33e3-4dd2-85e7-b28fd53726ae)

### Expected result

The caches should be moved and Dev Home shouldn't hang

### Actual result

Dev Home hangs and crashes. My assumption is because the default auto-filled file path doesn't exist. This PR would be good to check out: #3287

**Comment by cinnamon-msft** [comment] 2024-07-03 18:52
An update: Dev Home hung but came back to life and moved the caches:
![image](https://github.com/microsoft/devhome/assets/48369326/eb698aa3-ad52-4561-bc1e-2cc34e86fc80)

**Comment by SohamDas2021** [comment] 2024-07-08 19:36
@cinnamon-msft what is the size of the cache that was moved- I am thinking if this is a dupe of https://github.com/microsoft/devhome/issues/2925

**Closed** 2024-07-08 19:37 UTC
Labels: Issue-Bug, Priority-0, Severity-Crash, Area-DevDriveInsights
