### ISSUE TITLE
Error cloning

### ISSUE THREAD

**Issue by Kamikaze-420** [microsoft/devhome#952] opened 2023-05-30 08:26 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.23466.1001

### Other software

OS Build Version: 10.0.23466.1001.arm64fre.ni_prerelease.230522-1422
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

machine config > add repository > accept terms > fail.

### Expected result

Clone repository 

### Actual result

failed on setup

### Included System Information

Physical Memory: 7.65GB (0.79GB free)
Processor Architecture: ARMx64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_arm64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_arm64__8wekyb3d8bbwe

**Comment by cinnamon-msft** [comment] 2023-05-30 20:14
Would you mind providing a little more info here? Such as:
- Was it a URL or account repository?
- Were you signed in with GitHub?
- Did you receive an error message? If so, what was it?

Thanks!

**Comment by ilGianfri** [comment] 2023-05-31 21:33
I have the same issue, I get error code 0x80131500. In my case it was an account repository.
Any repository I tried failed. This is on Windows Dev Kit 2023

**Comment by dhoehna** [comment] 2023-06-06 21:00
Duplicate of #978

**Closed by dhoehna** 2023-06-06 21:00 UTC
Labels: Issue-Bug, Area-Machine-Config, Needs-Author-Feedback, Priority-1, Area-Machine-Config-Repo
