### ISSUE TITLE
Configured the dashboard, shut down laptop, dashboard lost

### ISSUE THREAD

**Issue by RachBreeze** [microsoft/devhome#1171] opened 2023-06-19 07:11 UTC
### Dev Home version

0.200.165.0

### Windows build number

10.0.22621.1848

### Other software

OS Build Version: 10.0.22621.1848.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

I am on Windows 11, build 22621.1848

I configured my dashboard, shut down the pc, all my widgets were gone.

Widgets added:
1) All GitHub
2) GPU

### Expected result

The build dashboard remained

### Actual result

The built dashboard was lost

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i9-12900HK
Physical Memory: 31.68GB (14.84GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-19 14:22
Duplicate of #742

**Closed by krschau** 2023-06-19 14:22 UTC
Labels: Issue-Bug, Needs-Triage
