### ISSUE TITLE
Title bar breaks when switching theme from light to dark

### ISSUE THREAD

**Issue by itsWindows11** [microsoft/devhome#711] opened 2023-05-23 16:35 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.22621.1702

### Steps to reproduce the bug

- Go to Settings page then Preferences.
- Select Light theme.
- Then, select Default (if you have dark mode enabled in Windows settings for apps).

### Expected result

Title bar appearing correctly in dark mode.

### Actual result

Title bar is not appearing in dark mode properly.

![image](https://github.com/microsoft/devhome/assets/81253203/359fcd77-8956-4b5c-a9ea-7185c31853c2)

**Comment by krschau** [comment] 2023-05-23 16:37
Duplicate of #511

**Closed by krschau** 2023-05-23 16:37 UTC
Labels: Issue-Bug, Needs-Triage
