### ISSUE TITLE
GitHub link account not working

### ISSUE THREAD

**Issue by Linx-ESP** [microsoft/devhome#2017] opened 2023-12-07 23:15 UTC
### Dev Home version

0.701.323.0

### Windows build number

10.0.22621.2715

### Other software

OS Build Version: 10.0.22621.2715.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.24

### Steps to reproduce the bug

Any menu that opens a "Link to github" or similar has a non working link/text box

### Expected result

Open github on browser

### Actual result

Nothing

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.701.323.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.700.323.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-12-11 18:25
Duplicate of https://github.com/microsoft/devhomegithubextension/issues/108

**Closed by krschau** 2023-12-11 18:25 UTC
Labels: Issue-Bug, Needs-Triage
