### ISSUE TITLE
Title bar text color isn't updated when switching theme

### ISSUE THREAD

**Issue by orlandoisay** [microsoft/devhome#834] opened 2023-05-25 04:21 UTC
### Dev Home version

0.137.141.0

### Windows build number

10.0.25370.1

### Other software

OS Build Version: 10.0.25370.1.amd64fre.zn_release.230516-0802
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

In Preferences:

1. Set theme = Dark
2. Set theme = Default

Windows theme = Light

### Expected result

Title bar should change to black.

### Actual result

Title bar color stays white.

![image](https://github.com/microsoft/devhome/assets/7746981/4ceb99e3-0f3c-4fce-b1d2-0b83764445de)

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i9-11900 @ 2.50GHz
Physical Memory: 31.61GB (17.39GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.141.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by orlandoisay** [comment] 2023-05-25 04:22
Switching to Light and then to Default works fine

**Comment by krschau** [comment] 2023-06-06 14:49
Duplicate of #511

**Closed by krschau** 2023-06-06 14:49 UTC
Labels: Issue-Bug, Needs-Triage, Priority-1, Area-Style, Area-Core
