### ISSUE TITLE
Graph updates

### ISSUE THREAD

**Issue by borg-1of1** [microsoft/devhome#1317] opened 2023-07-20 21:57 UTC
### Dev Home version

0.301.198.0

### Windows build number

10.0.22623.746

### Other software

OS Build Version: 10.0.22623.746.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.18

### Steps to reproduce the bug

Add widgets with graphs like CPU or GPU usage.  Let run.  At some point the graphs stop updating.  Attached screenshots were taken approximately a minute apart.

![Screenshot 2023-07-20 165551](https://github.com/microsoft/devhome/assets/56663946/04b5d67c-8972-4063-8498-bed6f138ee11)
![Screenshot 2023-07-20 165635](https://github.com/microsoft/devhome/assets/56663946/1c2e1234-ac35-4c48-914b-d55367bf21ce)

### Expected result

Expected graphs to continually update.

### Actual result

Graphs stop updating after some length of time...say 30 min or so.  Was not paying attention so cannot give specific amount of time. 

### Included System Information

Physical Memory: 15.89GB (5.84GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.200.165.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.301.198.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-07-21 14:28
Duplicate of #603

**Closed by krschau** 2023-07-21 14:28 UTC
Labels: Issue-Bug, Needs-Triage
