### ISSUE TITLE
Dashboard doesn't load

### ISSUE THREAD

**Issue by pjgraczyk** [microsoft/devhome#2422] opened 2024-03-15 13:07 UTC
### Dev Home version

0.1101.416.0

### Windows build number

10.0.22631.3296

### Other software

OS Build Version: 10.0.22631.3296.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

When opening the app, the dashboard is stuck at loading animation.

### Expected result

Dashboard opened with widgets

### Actual result

Dashboard loads

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Physical Memory: 15.79GB (5.4GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1101.416.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1100.422.0_x64__8wekyb3d8bbwe

Widget Service: 
MicrosoftWindows.Client.WebExperience_523.11500.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-03-15 13:57
Duplicate of #2401

**Closed by krschau** 2024-03-15 13:57 UTC
Labels: Issue-Bug, Needs-Triage
