### ISSUE TITLE
Widgets reset

### ISSUE THREAD

**Issue by Bennett-Fourr** [microsoft/devhome#1056] opened 2023-06-04 21:46 UTC
### Dev Home version

0.137.150.0

### Windows build number

10.0.22621.1778

### Other software

OS Build Version: 10.0.22621.1778.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.16

### Steps to reproduce the bug

Add a widget and then restat your comutor

### Expected result

The widget would stay

### Actual result

The widget removes

### Included System Information

CPU: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
Physical Memory: 31.58GB (21.68GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.137.150.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.137.141.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-06-05 14:26
Duplicate of #742

**Closed by krschau** 2023-06-05 14:26 UTC
Labels: Issue-Bug, Needs-Triage
