### ISSUE TITLE
Absurd CPU usage percentage

### ISSUE THREAD

**Issue by iqnite** [microsoft/devhome#3001] opened 2024-05-27 18:55 UTC
### Dev Home version

0.1401.505.0

### Windows build number

10.0.22635.3646

### Other software

OS Build Version: 10.0.22635.3646.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Open the widgets board and look at the CPU widget.

### Expected result

A CPU usage that is the same as the one shown in the Task Manager and that equals or is lower than 100%.

### Actual result

Sometimes the CPU usage percentage is correct, some other times, it's wrong, and sometimes, it shows values ABOVE 100%.
![image](https://github.com/microsoft/devhome/assets/50552317/6d469d60-d526-4006-aae7-b4ad11db23f5)

I didn't know that my processor had supernatural powers...

### Included System Information

CPU: AMD Ryzen 5 5500U with Radeon Graphics         
Physical Memory: 13.83GB (2.41GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
9932MartCliment.WingetUIWidgets_0.5.0.0_x64__g91dtg5srk15g (WingetUI Widgets (Preview))
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1401.505.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1400.505.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.0.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-06-19 13:37
Duplicate of #1220

**Closed by krschau** 2024-06-19 13:37 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
