### ISSUE TITLE
Ubuntu Quick Create and Debian do not support configuration. We should not allow that option.

### ISSUE THREAD

**Issue by KevinLaMS** [microsoft/devhome#3788] opened 2024-09-05 21:21 UTC
### Steps to reproduce the bug

Install an Ubuntu quick create image. 
Choose to configure it through DevHome.

It allows you to. It should not.

### Expected result

VMs that do not support winget configurations should not be selectable. They probably should not appear in the setup environment page

### Actual result

![image](https://github.com/user-attachments/assets/b8133f8e-d362-4cba-bd5f-95e8a9d685f0)

**Comment by shakersMSFT** [comment] 2024-09-05 21:28
duplicate of https://github.com/microsoft/devhome/issues/3513

**Closed** 2024-09-05 21:28 UTC
Labels: Issue-Bug
