### ISSUE TITLE
GitHub Repository 

### ISSUE THREAD

**Issue by Yashhh08** [microsoft/devhome#1811] opened 2023-11-02 06:05 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2506

### Other software

OS Build Version: 10.0.22631.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

After adding GitHub repo its not showing in added repository 

### Expected result

it should appear in added repositories

### Actual result

it didn't added my repository 

### Included System Information

Physical Memory: 15.63GB (7.19GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-03 15:16
Hi @Yashhh08. Can you explain more about the issue you're seeing, maybe with screenshots? Are you trying to add a repo to the list of repos you want to clone and it's disappearing before you can clone? Or do you not like how the repo isn't listed _after_ you clone? (The second thing is tracked by #702)

**Comment by Yashhh08** [comment] 2023-11-07 15:42
I have a suggestion regarding the user interface. In my opinion, after adding a repository, it should appear in the 'Added repositories' section or user should know which repositories are already added. Please let me know if I have understood the behavior correctly

**Comment by krschau** [comment] 2023-11-07 16:23
In that case, let's track it with 702.

Duplicate of #702

**Closed by krschau** 2023-11-07 16:23 UTC
Labels: Issue-Bug, Area-Machine-Config, Needs-Triage, Needs-Team-Response
