### ISSUE TITLE
allow scanning/adding of programs/tools on drive(s)

### ISSUE THREAD

**Issue by TheEndHunter** [microsoft/devhome#1119] opened 2023-06-10 15:26 UTC
### Suggested new feature or improvement

give developers the option to scan their drive(s) for existing tools and programs that may already be installed, potentially including the option to add preview versions of the tools, and/or, tools not in the existing list of programs currently supported for install(with a warning for anything that may be an un-supported configuration)

### Scenario

this would be useful in scenarios where the programs may already be installed and configured or they have a newer version installed(such as preview) and the dev wants to use that software over installing an older version.

**Comment by krschau** [comment] 2023-06-12 14:50
I'm going to dupe this to #702, but you may want to add your specific suggestion about preview versions over there!

**Comment by krschau** [comment] 2023-06-12 14:50
Duplicate of #702

**Closed by krschau** 2023-06-12 14:50 UTC
Labels: Issue-Feature, Needs-Triage
