### ISSUE TITLE
Ability to open a YAML file directly into the machine configuration yaml flow

### ISSUE THREAD

**Issue by joadoumie** [microsoft/devhome#705] opened 2023-05-23 15:59 UTC
### Suggested new feature or improvement

First, need to investigate and confirm usefulness of such a utility. Creating issue as placeholder.

It'd be helpful if a user could quickly either open a YAML file into the machine config flow of Dev Home and go through the configuration steps OR people could link to existing yaml packages that are in Dev Home.

### Scenario

Make it easier to link YAML files to Dev Home machine config flow. Can we make it easier for users who discover configuration files from documentation to quickly get in the Dev Home setup flow?

**Comment by denelon** [comment] 2023-06-05 20:49
Duplicate of #675

**Comment by joadoumie** [comment] 2023-06-06 15:19
@denelon - what are your thoughts about supporting opening a .dsc.yaml file with Dev Home? Example flow:

- User downloads dsc.yaml file
- right-click "open with" Dev Home 
- Dev Home is launched and opens directly to the DSC flow

**Comment by denelon** [comment] 2023-06-06 15:38
@joadoumie I'm not sure if a protocol handler supports double "dots". We probably don't want to associate ".yaml" files with Dev Home as most users will already have an IDE or advanced text editor associated with ".yaml" files.

**Comment by joadoumie** [comment] 2023-06-06 15:42
That makes sense. If protocol handler could handle the double dots I think it could be an interesting flow to double-click on.

**Comment by joadoumie** [comment] 2023-08-01 15:01
It looks like there is not a way (at least that I could find) to handle the double dots. The result is something like this **if** you have an application already set as default to handle .yaml files: 

![devhome-file-activation](https://github.com/microsoft/devhome/assets/98557455/e997f9e4-5774-479c-baa9-46dfae1d50b7)

**Comment by joadoumie** [comment] 2023-08-11 21:45
Reopening issue as it does not seem fully related to the issue it was marked against as a dup.

**Closed** 2024-03-25 19:50 UTC
Labels: Issue-Feature, Area-Machine-Config, In-PR, Area-Machine-Config-DSC, Area-Activation
