### ISSUE TITLE
The "Preview" installed on my computer without my approval

### ISSUE THREAD

**Issue by no-good-usernames-left** [microsoft/devhome#3371] opened 2024-07-05 14:15 UTC
### Suggested new feature or improvement

The short version is don't install random crap if I didn't solicit for it in the first place!

The long one is the same + I want less bloat and crap in Windows, not more and this is 110% bloat and crap I don't need for the smooth and stable operation of my system!

### Scenario

I ran updates on Win10 on my work PC and this app appeared/installed all on it's own. 

### Additional details

If I didn't want it, don't install it, this isn't rocket science...

I had to use the winget uninstall to remove it because I didn't need it for my daily business workflow and speak with authority that this app will NOT be randomly be dumped onto people's computers

**Comment by krschau** [comment] 2024-07-08 15:40
Duplicate of #1615

**Closed by krschau** 2024-07-08 15:40 UTC
Labels: Issue-Feature, Needs-Triage
