### ISSUE TITLE
Azure DevOps

### ISSUE THREAD

**Issue by trdsolutions** [microsoft/devhome#815] opened 2023-05-24 19:34 UTC
### Suggested new feature or improvement

I would really like to see, that DevHome will support Azure DevOps as well.

### Scenario

Besides the administration of GitHub account and repos, Azure DevOps account and repos can be configured.

**Comment by Aaron-Junker** [comment] 2023-05-24 19:47
Duplicate of #521

**Comment by krschau** [comment] 2023-05-24 21:11
Duplicate of #521

**Closed by krschau** 2023-05-24 21:11 UTC
Labels: Issue-Feature, Needs-Triage
