### ISSUE TITLE
CoreWidgetProvider.HelpersSystemData exception

### ISSUE THREAD

**Issue by darioinova** [microsoft/devhome#3383] opened 2024-07-09 09:50 UTC
### Dev Home version

0.1501.533.0

### Windows build number

10.0.22631.3810

### Other software

OS Build Version: 10.0.22631.3810.amd64fre.ni_release.220506-1250
.NET Version: .NET 8.0.5

### Steps to reproduce the bug

Just opening the Dashboard with the CPU widget

### Expected result

show the GPU widget correctly

### Actual result

The type initializer for 'CoreWidgetProvider.HelpersSystemData' threw an exception.

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i7-1265U
Physical Memory: 15.69GB (0.76GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Core Widget Extension)
Microsoft.Windows.DevHome_0.1501.533.0_x64__8wekyb3d8bbwe (Hyper-V Extension)
Microsoft.Windows.DevHomeGitHubExtension_0.1500.533.0_x64__8wekyb3d8bbwe (Dev Home GitHub Extension (Preview))
Microsoft.Windows.DevHomeAzureExtension_0.1000.533.0_x64__8wekyb3d8bbwe (Dev Home Azure Extension (Preview))

Widget Service: 
MicrosoftWindows.Client.WebExperience_524.13200.30.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-07-09 14:53
Duplicate of #3259

**Closed by krschau** 2024-07-09 14:53 UTC
Labels: Issue-Bug, Needs-Triage
