### ISSUE TITLE
Add ability to move Widgets 

### ISSUE THREAD

**Issue by vb2ae** [microsoft/devhome#927] opened 2023-05-29 01:37 UTC
### Suggested new feature or improvement

Add ability to move Widgets so you can place them in way that fits the way you work

### Scenario

Add ability to move Widgets so you can place them in way that fits the way you work

**Comment by krschau** [comment] 2023-05-30 16:28
Duplicate of #673

**Closed by krschau** 2023-05-30 16:28 UTC
Labels: Issue-Feature, Needs-Triage
