### ISSUE TITLE
Core widget title colors need adjusting

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/devhome#1473] opened 2023-08-31 21:32 UTC
### Dev Home version

0.5

### Steps to reproduce the bug

Pin a core widget (CPU, GPU, network, memory)

### Actual result

Title text color needs to be lighter
![MicrosoftTeams-image (9)](https://github.com/microsoft/devhome/assets/48369326/311f9f32-1915-4358-b616-1105a658f390)

**Comment by krschau** [comment] 2023-09-08 15:40
Duplicate of #1468

**Closed by krschau** 2023-09-08 15:40 UTC
Labels: Issue-Bug, Area-Widgets, Needs-Triage, Area-Craftsmanship, Craft-Red
