### ISSUE TITLE
Restarting the app results in animated widgets (e.g., GPU, CPU, memory) being "stuck"

### ISSUE THREAD

**Issue by localden** [microsoft/devhome#728] opened 2023-05-23 17:10 UTC
![animation-home](https://github.com/microsoft/devhome/assets/53200638/3225919e-760b-456f-bc9e-e33599b593d2)

**Comment by krschau** [comment] 2023-05-23 17:12
At least related to, maybe a dupe of, #603

**Comment by localden** [comment] 2023-05-23 17:12
After that, clicking **End Process** on any of the items in the **CPU** section does nothing.

**Comment by localden** [comment] 2023-05-23 17:12
@krschau likely related, but in this case it can be easily reproduced by restarting the app.

**Comment by krschau** [comment] 2024-08-20 15:08
Fixed by #3524

**Closed by krschau** 2024-08-20 15:08 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
