### ISSUE TITLE
Network dashboard does not include wired connection

### ISSUE THREAD

**Issue by SJang1** [microsoft/devhome#2248] opened 2024-02-11 09:37 UTC
### Dev Home version

0.1001.389.0

### Windows build number

10.0.26052.1100

### Other software

OS Build Version: 10.0.26052.1100.amd64fre.ge_release.240202-1419
.NET Version: .NET 8.0.1

### Steps to reproduce the bug

Add Network Status dashboard on Dashboard page

### Expected result

Ethernet (Wired) connection should show up

### Actual result

Wired connection does not show up, and only Wi-Fi connection shows up. There is no button to switch it.

### Included System Information

CPU: Intel(R) Core(TM) i9-14900KF
Memory: 127.78GB (113.47GB free)

### Included Extensions Information

Microsoft.Windows.DevHome_0.1001.389.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.1000.393.0_x64__8wekyb3d8bbwe

MicrosoftWindows.Client.WebExperience_524.1301.160.0_x64__cw5n1h2txyewy

**Comment by krschau** [comment] 2024-02-13 14:39
Duplicate of #2207
That fix will put the button back, then you should be able to switch to your wired connection (mine comes up).

**Closed by krschau** 2024-02-13 14:39 UTC
Labels: Issue-Bug, Area-Widgets, Priority-2
