### ISSUE TITLE
GitHub Releases should have artifacts mirroring the version deployed to the Microsoft Store

### ISSUE THREAD

**Issue by snickler** [microsoft/devhome#1165] opened 2023-06-16 23:07 UTC
### Suggested new feature or improvement

Currently, the latest preview release for Dev Home is 0.200.165.0. 

![image](https://github.com/microsoft/devhome/assets/4016293/dd32ddd3-a626-4345-ba2c-563bb1c2e1e4)

On the Microsoft Store page the "What's new in this version" states to look at the GitHub Releases page for more information, which is currently only showing details for 0.137.141.0.

![image](https://github.com/microsoft/devhome/assets/4016293/cea6ee6f-f00c-4a42-8285-e3f61146a235)

![image](https://github.com/microsoft/devhome/assets/4016293/53db8fdb-70af-4fa7-931f-673e32002ee4)

### Scenario

To know which features are released in each build.

**Comment by cinnamon-msft** [comment] 2023-07-19 23:28
We post our release notes with our releases on GitHub, so the latest updates should appear on our releases page. We can't really update the Store listing with each release because of the pipeline we use for publishing new builds. I'm going to close this as by design since we don't have a great way around this, plus Terminal follows the same practice :)

**Closed by cinnamon-msft** 2023-07-19 23:28 UTC
Labels: Issue-Feature, Needs-Triage
