### ISSUE TITLE
WIDGET BUG

### ISSUE THREAD

**Issue by colonelescobar** [microsoft/devhome#1852] opened 2023-11-10 15:38 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22631.2506

### Other software

OS Build Version: 10.0.22631.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

1. go to dashboard 2. add new widget 3.click the cancel button.

### Expected result

widget window should close when cancel button is clicked

### Actual result

window doesn't close and remains open, acting like its part of the main window. double clicking it enlarges and minimizes the whole window.

### Included System Information

Physical Memory: 15.78GB (6.15GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe

**Comment by krschau** [comment] 2023-11-13 19:52
Duplicate of #537

**Closed by krschau** 2023-11-13 19:52 UTC
Labels: Issue-Bug, Area-Widgets, Priority-1
