### ISSUE TITLE
Machine configuration and Environments take about one minute to load

### ISSUE THREAD

**Issue by jiayac** [microsoft/devhome#2764] opened 2024-04-29 18:39 UTC
### Steps to reproduce the bug

Open Dev Home and navigate to machine configuration/Environments

### Actual result

After waiting for more than one minute, the page starts to display

**Comment by huzaifa-d** [comment] 2024-04-29 18:52
Closing as duplicate as pointed out by the bot.

**Comment by krschau** [comment] 2024-05-01 16:42
Duplicate of #2736

**Closed by krschau** 2024-05-01 16:42 UTC
Labels: Issue-Bug, Needs-Triage
