### ISSUE TITLE
Why does nothing happen you click on the close button in the Dashboard>Add New Widget

### ISSUE THREAD

**Issue by skanda890** [microsoft/devhome#1875] opened 2023-11-11 05:23 UTC
### Dev Home version

0.601.297.0

### Windows build number

10.0.22621.2506

### Other software

OS Build Version: 10.0.22621.2506.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.23

### Steps to reproduce the bug

Why does nothing happen when you click on the close button in the Dashboard>Add New Widget?

### Expected result

It should close that menu.

### Actual result

Nothing happens.

### Included System Information

Physical Memory: 11.89GB (3.46GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.600.283.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.601.297.0_x64__8wekyb3d8bbwe

**Comment by skanda890** [comment] 2023-11-11 05:24
Can you remove the 'Issue-Bug' label and label this as 'Issue-Question' or is this a bug.

**Comment by krschau** [comment] 2023-11-13 20:21
Duplicate of #537

**Closed by krschau** 2023-11-13 20:21 UTC
Labels: Issue-Bug, Needs-Triage

**Comment by skanda890** [comment] 2023-11-14 08:13
Okay.
